export default {
  pt: {
    header_title: 'Arquivo LdoD',
    user_password: 'Cambiar la Contraseña',
    header_login: 'Iniciar Sessão',
    header_logout: 'Sair',

    header_about: 'Acerca',
    header_videos: 'Vídeos',
    header_tutorials: 'Tutoriais e Oficinas',
    header_faq: 'Perguntas Frequentes',
    header_encoding: 'Codificação de Texto',
    header_bibliography: 'Bibliografia',
    header_book: 'Livro',
    header_conduct: 'Code of Conduct',
    header_contact: 'Contact Us',
    header_copyright: 'Copyright',
    header_acknowledgements: 'Agradecimentos',
    header_privacy: 'Política de Privacidade',
    header_team: 'Equipa Editorial',

    general_reading: 'Leitura',
    general_reading_sequences: 'Sequências de Leitura',
    general_reading_visual: 'Livro Visual',
    general_citations_twitter: 'Citações no Twitter',

    header_documents: 'Documentos',
    authorial_source: 'Testemunhos',
    fragment_codified: 'Fragmentos Codificados',


    header_editions: 'Edições',
    general_editor_prado: 'Jacinto do Prado Coelho',
    general_editor_zenith: 'Richard Zenith',
    general_editor_cunha: 'Teresa Sobral Cunha',
    general_editor_pizarro: 'Jerónimo Pizarro',
    anot: 'LdoD-JPC-Anot',
    mallet: 'LdoD-Jogo-Class',
    class: 'LdoD-Mallet',
    twitter: 'LdoD-Twitter',
    
    header_search: "Pesquisa",
    header_search_simple: "Pesquisa Simples",
    header_search_advanced: "Pesquisa Avançada",

    error: 'Algo correu mal. Tente novamente mais tarde',
  },
  en: {
    header_title: 'LdoD Archive',
    user_password: 'Change Password',
    header_login: 'Login',
    header_logout: 'Logout',
    header_archive: '',

    header_about: 'About',
    header_videos: 'Videos',
    header_tutorials: 'Tutorials and Workshops',
    header_faq: 'Frequently Asked Questions',
    header_encoding: 'Text Encoding',
    header_bibliography: 'Bibliography',
    header_book: 'Book',
    header_contact: 'Contacto',
    header_conduct: 'Código de Conduta',
    header_copyright: 'Copyright',
    header_privacy: 'Privacy Policy',
    header_team: 'Editorial Team',
    header_acknowledgements: 'Acknowledgements',

    general_reading: 'Reading',
    general_reading_sequences: 'Reading Sequences',
    general_reading_visual: 'Visual Book',
    general_citations_twitter: 'Citations on Twitter',

    header_documents: 'Documents',
    authorial_source: 'Witnesses',
    fragment_codified: 'Encoded Fragments',

    header_editions: 'Editions',
    general_editor_prado: 'Jacinto do Prado Coelho',
    general_editor_zenith: 'Richard Zenith',
    general_editor_cunha: 'Teresa Sobral Cunha',
    general_editor_pizarro: 'Jerónimo Pizarro',
    anot: 'LdoD-JPC-Anot',
    mallet: 'LdoD-Jogo-Class',
    class: 'LdoD-Mallet,',
    twitter: 'LdoD-Twitter',

    header_search: "Search",
    header_search_simple: "Simple Search",
    header_search_advanced: "Advanced Search",

    error: 'Something went wrong. Try again later',

  },
  es: {
    header_title: 'Archivo LdoD',
    user_password: 'Alterar Senha',
    header_login: 'Iniciar Sesión',
    header_logout: 'Cerrar',

    header_about: 'Acerca',
    header_videos: 'Vídeos',
    header_tutorials: 'Tutoriales y Talleres',
    header_faq: 'Preguntas Frecuentes',
    header_encoding: 'Codificación de Texto',
    header_bibliography: 'Bibliografía',
    header_book: 'Libro',
    header_conduct: 'Código de Conducta',
    header_contact: 'Contacto',
    header_copyright: 'Copyright',
    header_privacy: 'Política de Privacidad',
    header_team: 'Equipo Editorial',
    header_acknowledgements: 'Agradecimientos',

    general_reading: 'Lectura',
    general_reading_sequences: 'Secuencias de lectura',
    general_reading_visual: 'Libro Visual',
    general_citations_twitter: 'Citas en Twitter',

    header_documents: 'Documentos',
    authorial_source: 'Testimonios',
    fragment_codified: 'Fragmentos Codificados',

    header_editions: 'Ediciones',
    general_editor_prado: 'Jacinto do Prado Coelho',
    general_editor_zenith: 'Richard Zenith',
    general_editor_cunha: 'Teresa Sobral Cunha',
    general_editor_pizarro: 'Jerónimo Pizarro',
    anot: 'LdoD-JPC-Anot',
    mallet: 'LdoD-Jogo-Class',
    class: 'LdoD-Mallet,',
    twitter: 'LdoD-Twitter',

    header_search: "Búsqueda",
    header_search_simple: "Búsqueda Sencilla",
    header_search_advanced: "Búsqueda Avanzada",

    error: 'Algo salió mal. Vuelve a intentarlo más tarde',
  },
};
