export default {
  pt: {
    search: 'Pesquisar',
    simpleSearch: 'Pesquisa Simples',
    completeSearch: 'Pesquisa completa',
    titleSearch: 'Pesquisa por título',
    searchFor: 'Procurar por...',
    fontTypes: 'Tipos de fonte',
    coelho: 'Jacinto Prado Coelho',
    cunha: 'Teresa Sobral Cunha',
    zenith: 'Ricardo Zenith',
    pizarro: 'Jerónimo Pizarro',
    BNP: 'Testemunhos',
    fragment: 'Fragmento',
    interpts: 'Interpretações',

    advancedSearch: 'Pesquisa avançada',
    criteriaMatchAll: 'De acordo com todos os seguintes critérios',
    criteriaMatchAtLeastOne:
      'De acordo com pelo menos um dos seguintes critérios',
    edition: 'Edição',
    manuscript: 'Manuscrito',
    typeScript: 'Datiloscrito',
    published: 'Publicado',
    heteronym: 'Heterónimo',
    taxonomies: 'Taxonomias',
    virtualEditions: 'Edições Virtuais',
    date: 'Data',
    text: 'Texto',
    includedIn: 'Incluídos em',
    excludedFrom: 'Excluídos de',
    all: 'Todas',
    simpleResultsLabels:  {
      fragment: 'Fragmento',
      interpts: 'Interpretações'
    }
  },
  en: {
    search: 'Search',
    simpleSearch: 'Simple Search',
    completeSearch: 'Full Search',
    titleSearch: 'Search by title',
    searchFor: 'Search for...',
    fontTypes: 'Source types',
    coelho: 'Jacinto Prado Coelho',
    cunha: 'Teresa Sobral Cunha',
    zenith: 'Ricardo Zenith',
    pizarro: 'Jerónimo Pizarro',
    BNP: 'Witnesses',
    fragment: 'Fragment',
    interpts: 'Interpretations',

    advancedSearch: 'Advanced Search',
    criteriaMatchAll: 'Match all of the following',
    criteriaMatchAtLeastOne: 'Match any of the following',
    edition: 'Edición',
    manuscript: 'Manuscript',
    typeScript: 'Typescript',
    published: 'Published',
    heteronym: 'Heteronym',
    taxonomies: 'Taxonomies',
    virtualEditions: 'Virtual editions',
    date: 'Date',
    text: 'Text',
    includedIn: 'Included in',
    excludedFrom: 'Excluded from',
    all: 'All',
    simpleResultsLabels: {
      fragment: 'Fragment',
      interpts: 'Interpretations'
    }
  },
  es: {
    search: 'Pesquisar',
    simpleSearch: 'Búsqueda Sencilla',
    completeSearch: 'Búsqueda Completa',
    titleSearch: 'Búsqueda por título',
    searchFor: 'Buscar por...',
    fontTypes: 'Tipos de fuente',
    coelho: 'Jacinto Prado Coelho',
    cunha: 'Teresa Sobral Cunha',
    zenith: 'Ricardo Zenith',
    pizarro: 'Jerónimo Pizarro',
    BNP: 'Testimonios',
    fragment: 'Fragmento',
    interpts: 'Interpretaciones',

    advancedSearch: 'Búsqueda Avanzada',
    criteriaMatchAll: 'Coincidir todos de los siguientes criterios',
    criteriaMatchAtLeastOne:
      'Coincidir con pelo menos uno de los siguientes criterios',
    edition: 'Edición',
    manuscript: 'Manuscrito',
    typeScript: 'Mecanografiado',
    published: 'Publicado',
    heteronym: 'Heterónimo',
    taxonomies: 'Taxonomías',
    virtualEditions: 'Ediciónes Virtuales',
    date: 'Fecha',
    text: 'Texto',
    includedIn: 'Incluidos en',
    excludedFrom: 'Excluidos de',
    all: 'Todas',
    simpleResultsLabels: {
      fragment: 'Fragmento',
      interpts: 'Interpretaciones'
    }
  },
};
