export default {
  sessionListHeaders: [
    'userName',
    'firstName',
    'lastName',
    'lastRequest',
    'sessionId',
  ],
  usersListHeaders: [
    'userName',
    'firstName',
    'lastName',
    'enabled',
    'listOfRoles',
    'lastLogin',
    'active',
    'actions',
  ],
  pt: {
    TRUE: 'Sim',
    FALSE: 'Não',
    users: 'Utilizadores',
    sessions: 'Sessões',
    userName: 'Nome de utilizador',
    firstName: 'Primeiro nome',
    lastName: 'Apelido',
    lastRequest: 'Último Pedido',
    sessionId: 'ID da Sessão',
    enabled: 'Confirmado',
    listOfRoles: 'Papeis',
    lastLogin: 'Último acesso',
    actions: 'Acções',
    active: 'Ativo',
    edit: 'Editar',
    remove: 'Apagar',
  },
  en: {
    TRUE: 'Yes',
    FALSE: 'No',
    users: 'Users',
    sessions: 'Sessions',
    userName: 'Username',
    firstName: 'First Name',
    lastName: 'Last Name',
    lastRequest: 'Last Request',
    sessionId: 'Session ID',
    enabled: 'Enabled',
    listOfRoles: 'Roles',
    lastLogin: 'Last login',
    actions: 'Actions',
    active: 'Active',
    edit: 'Edit',
    remove: 'Delete',
  },
  es: {
    users: 'Usuarios',
    sessions: 'Sesiones',
    userName: 'Nombre de usuario',
    firstName: 'Primer nombre',
    lastName: 'Apellido',
    lastRequest: 'Última Petición',
    sessionId: 'ID de sesión',
  },
};
