export default {
  sessionListHeaders: [
    'userName',
    'firstName',
    'lastName',
    'lastRequest',
    'sessionId',
  ],
  usersListHeaders: [
    'userName',
    'firstName',
    'lastName',
    'enabled',
    'listOfRoles',
    'lastLogin',
    'active',
    'actions',
  ],
  pt: {
    TRUE: 'Sim',
    FALSE: 'Não',
    users: 'Utilizadores',
    user: 'Utilizador',
    admin: 'Administrador',
    sessions: 'Sessões',
    userName: 'Nome de utilizador',
    firstName: 'Primeiro nome',
    lastName: 'Apelido',
    lastRequest: 'Último Pedido',
    sessionId: 'ID da Sessão',
    enabled: 'Confirmado',
    listOfRoles: 'Papeis',
    lastLogin: 'Último acesso',
    actions: 'Acções',
    active: 'Ativo',
    edit: 'Editar utilizador',
    remove: 'Eliminar utilizador',
    editUserHeader: 'Alterar utilizador',
    update: 'Atualizar',
    email: 'Endereço eletrónico',
    newPassword: 'Nova Senha',
    toggleActiveMode: 'Alterar estado ativo',
    changeLdodMode: 'Alterar modo do LdoD',
    deleteUserSessions: 'Eliminar sessões de utilizador',
    userMode: 'Modo utilizador',
    adminMode: 'Modo administrador',
  },
  en: {
    TRUE: 'Yes',
    FALSE: 'No',
    users: 'Users',
    user: 'User',
    admin: 'Administrator',
    sessions: 'Sessions',
    userName: 'Username',
    firstName: 'First Name',
    lastName: 'Last Name',
    lastRequest: 'Last Request',
    sessionId: 'Session ID',
    enabled: 'Enabled',
    listOfRoles: 'Roles',
    lastLogin: 'Last login',
    actions: 'Actions',
    active: 'Active',
    edit: 'Edit user',
    remove: 'Delete user',
    editUserHeader: 'Edit user',
    update: 'Update',
    email: 'Email',
    newPassword: 'New Password',
    toggleActiveMode: 'Toggle active state',
    changeLdodMode: 'Change LdoD mode',
    deleteUserSessions: 'Delete user sessions',
    userMode: 'User mode',
    adminMode: 'Administrator mode',
  },
  es: {
    TRUE: 'Sí',
    FALSE: 'No',
    users: 'Usuarios',
    user: 'Usuario',
    admin: 'Administrador',
    sessions: 'Sesiones',
    userName: 'Nombre de usuario',
    firstName: 'Primer nombre',
    lastName: 'Apellido',
    lastRequest: 'Última Petición',
    sessionId: 'ID de sesión',
    enabled: 'Activado',
    listOfRoles: 'Funciones',
    lastLogin: 'Último acceso',
    actions: 'Acciones',
    active: 'Activo',
    edit: 'Editar usuario',
    remove: 'Eliminar usuario',
    editUserHeader: 'Editar usuario',
    update: 'Actualizar',
    email: 'Correo electrónico',
    newPassword: 'Nueva contraseña',
    toggleActiveMode: 'Cambiar estado activo',
    changeLdodMode: 'Cambiar el modo LdoD',
    deleteUserSessions: 'Eliminar sesiones de usuario',
    userMode: 'Modo de usuario',
    adminMode: 'Modo administrador',
  },
};
