export default {
  header_title: 'LdoD Archive',
  user_password: 'Change Password',
  header_login: 'Login',
  header_logout: 'Logout',

  header_about: 'About',
  header_videos: 'Videos',
  header_tutorials: 'Tutorials and Workshops',
  header_faq: 'Frequently Asked Questions',
  header_encoding: 'Text Encoding',
  header_bibliography: 'Bibliography',
  header_book: 'Book',
  header_contact: 'Contacto',
  header_conduct: 'Código de Conduta',
  header_copyright: 'Copyright',
  header_privacy: 'Privacy Policy',
  header_team: 'Editorial Team',
  header_acknowledgements: 'Acknowledgements',

  general_reading: 'Reading',
  general_reading_sequences: 'Reading Sequences',
  general_reading_visual_external: 'Visual Book (External)',
  general_reading_visual_integrated: 'Visual Book (Integrated)',
  general_citations_twitter: 'Citations on Twitter',

  header_documents: 'Documents',
  authorial_source: 'Witnesses',
  fragment_codified: 'Encoded Fragments',

  header_editions: 'Editions',
  general_editor_prado: 'Jacinto do Prado Coelho',
  general_editor_zenith: 'Richard Zenith',
  general_editor_cunha: 'Teresa Sobral Cunha',
  general_editor_pizarro: 'Jerónimo Pizarro',
  anot: 'LdoD-JPC-Anot',
  mallet: 'LdoD-Jogo-Class',
  class: 'LdoD-Mallet,',
  twitter: 'LdoD-Twitter',

  header_search: 'Search',
  header_search_simple: 'Simple Search',
  header_search_advanced: 'Advanced Search',

  header_virtual: 'Virtual',
  header_virtualeditions: 'Virtual Editions',
  general_classificationGame: 'Classification Game',

  header_admin: 'Admin',
  fragments_management: 'Manage Fragments',
  user_management: 'Manage users',
  virtual_editions_management: 'Manage Virtual Editions',
  tweets_management: 'Manage Tweets',
  error: 'Something went wrong. Try again later',
};
