export default {
  headers: [
    'date',
    'fragment',
    'sourceLink',
    'infoRanges',
    'annotations',
    'retweets',
    'location',
    'country',
    'username',
    'profile',
    'image',
  ],
  pt: {
    title: (value) => `Gerir Tweets (${value})`,
    generate: 'Gerar Citações',
    remove: (tweets) => `Apagar Tweets (${tweets})`,
    tableInfo: ({ cits, ranges }) =>
      `Citações: ${cits}, Citações com info range: ${ranges}`,
    date: 'Data',
    fragment: 'Fragmento',
    sourceLink: 'Tweet',
    infoRanges: 'Info Ranges',
    annotations: 'Número de Anotações',
    retweets: 'Número de Retweets',
    location: 'Localização',
    country: 'País',
    username: 'Utilizador',
    profile: 'Perfil do Utilizador',
    image: 'Imagem do Utilizador',
  },
  en: {
    title: (value) => `Manage Tweets (${value})`,
    generate: 'Generate Citations',
    remove: (tweets) => `Delete Tweets (${tweets})`,
    tableInfo: ({ cits, ranges }) =>
      `Citations: ${cits}, Citations with info range: ${ranges}`,
    date: 'Date',
    fragment: 'Fragment',
    sourceLink: 'Tweet',
    infoRanges: 'Info Ranges',
    annotations: 'Number of Annotations',
    retweets: 'Number of Retweets',
    location: 'Location',
    country: 'Country',
    username: 'Username',
    profile: 'User Profile',
    image: 'User image',
  },
  es: {
    title: (value) => `Administrar Tweets (${value})`,
    generate: 'Generar Citas',
    remove: (tweets) => `Eliminar Tweets (${tweets})`,
    tableInfo: ({ cits, ranges }) =>
      `Citas: ${cits}, Citas com info range: ${ranges}`,
    date: 'Data',
    fragment: 'Fragmento',
    sourceLink: 'Tweet',
    infoRanges: 'Info Ranges',
    annotations: 'Localização Geográfica',
    retweets: 'País',
    location: 'Localização',
    country: 'País',
    username: 'Utilizador',
    profile: 'Perfil do Utilizador',
    image: 'Imagem do Utilizador',
  },
};
