/** @format */

export default {
	en: {
		header_title: 'LdoD Archive',
		user_password: 'Change Password',
		header_login: 'Login',
		header_logout: 'Logout',
		header_about: 'About',
		header_videos: 'Videos',
		header_tutorials: 'Tutorials and Workshops',
		header_faq: 'Frequently Asked Questions',
		header_encoding: 'Text Encoding',
		header_bibliography: 'Bibliography',
		header_book: 'Book',
		header_contact: 'Contacto',
		header_conduct: 'Código de Conduta',
		header_copyright: 'Copyright',
		header_privacy: 'Privacy Policy',
		header_team: 'Editorial Team',
		header_acknowledgements: 'Acknowledgements',
		general_reading: 'Reading',
		general_reading_sequences: 'Reading Sequences',
		general_reading_visual_external: 'Visual Book (External)',
		general_reading_visual_integrated: 'Visual Book (Integrated)',
		general_citations_twitter: 'Citations on Twitter',

		header_documents: 'Documents',
		authorial_source: 'Witnesses',
		fragment_codified: 'Encoded Fragments',

		header_editions: 'Editions',
		general_editor_prado: 'Jacinto do Prado Coelho',
		general_editor_zenith: 'Richard Zenith',
		general_editor_cunha: 'Teresa Sobral Cunha',
		general_editor_pizarro: 'Jerónimo Pizarro',
		anot: 'LdoD-JPC-Anot',
		mallet: 'LdoD-Jogo-Class',
		class: 'LdoD-Mallet,',
		twitter: 'LdoD-Twitter',

		header_search: 'Search',
		header_search_simple: 'Simple Search',
		header_search_advanced: 'Advanced Search',

		header_virtual: 'Virtual',
		header_virtualeditions: 'Virtual Editions',
		general_classificationGame: 'Classification Game',

		header_admin: 'Admin',
		fragments_management: 'Manage Fragments',
		user_management: 'Manage users',
		virtual_editions_management: 'Manage Virtual Editions',
		tweets_management: 'Manage Tweets',
		error: 'Something went wrong. Try again later',
	},
	pt: {
		header_title: 'Arquivo LdoD',
		user_password: 'Alterar senha',
		header_login: 'Iniciar Sessão',
		header_logout: 'Sair',

		header_about: 'Acerca',
		header_videos: 'Vídeos',
		header_tutorials: 'Tutoriais e Oficinas',
		header_faq: 'Perguntas Frequentes',
		header_encoding: 'Codificação de Texto',
		header_bibliography: 'Bibliografia',
		header_book: 'Livro',
		header_conduct: 'Código de conduta',
		header_contact: 'Contacto',
		header_copyright: 'Copyright',
		header_acknowledgements: 'Agradecimentos',
		header_privacy: 'Política de Privacidade',
		header_team: 'Equipa Editorial',

		general_reading: 'Leitura',
		general_reading_sequences: 'Sequências de Leitura',
		general_reading_visual_external: 'Livro Visual (externo)',
		general_reading_visual_integrado: 'Livro Visual (integrado)',
		general_citations_twitter: 'Citações no Twitter',

		header_documents: 'Documentos',
		authorial_source: 'Testemunhos',
		fragment_codified: 'Fragmentos Codificados',

		header_editions: 'Edições',
		general_editor_prado: 'Jacinto do Prado Coelho',
		general_editor_zenith: 'Richard Zenith',
		general_editor_cunha: 'Teresa Sobral Cunha',
		general_editor_pizarro: 'Jerónimo Pizarro',
		anot: 'LdoD-JPC-Anot',
		mallet: 'LdoD-Jogo-Class',
		class: 'LdoD-Mallet',
		twitter: 'LdoD-Twitter',

		header_search: 'Pesquisa',
		header_search_simple: 'Pesquisa Simples',
		header_search_advanced: 'Pesquisa Avançada',

		header_virtual: 'Virtual',
		header_virtualeditions: 'Edições Virtuais',
		general_classificationGame: 'Jogo de Classificação',

		header_admin: 'Admin',
		fragments_management: 'Gerir Fragmentos',
		user_management: 'Gerir utilizadores',
		virtual_editions_management: 'Gerir Edições Virtuais',
		tweets_management: 'Gerir Tweets',
		error: 'Algo correu mal. Tente novamente mais tarde',
	},
	es: {
		header_title: 'Archivo LdoD',
		user_password: 'Cambiar la Contraseña',
		header_login: 'Iniciar Sesión',
		header_logout: 'Cerrar',

		header_about: 'Acerca',
		header_videos: 'Vídeos',
		header_tutorials: 'Tutoriales y Talleres',
		header_faq: 'Preguntas Frecuentes',
		header_encoding: 'Codificación de Texto',
		header_bibliography: 'Bibliografía',
		header_book: 'Libro',
		header_conduct: 'Código de Conducta',
		header_contact: 'Contacto',
		header_copyright: 'Copyright',
		header_privacy: 'Política de Privacidad',
		header_team: 'Equipo Editorial',
		header_acknowledgements: 'Agradecimientos',

		general_reading: 'Lectura',
		general_reading_sequences: 'Secuencias de lectura',
		general_reading_visual_externo: 'Libro Visual (Externo)',
		general_reading_visual_integrado: 'Libro Visual (Integrado)',

		general_citations_twitter: 'Citas en Twitter',

		header_documents: 'Documentos',
		authorial_source: 'Testimonios',
		fragment_codified: 'Fragmentos Codificados',

		header_editions: 'Ediciones',
		general_editor_prado: 'Jacinto do Prado Coelho',
		general_editor_zenith: 'Richard Zenith',
		general_editor_cunha: 'Teresa Sobral Cunha',
		general_editor_pizarro: 'Jerónimo Pizarro',
		anot: 'LdoD-JPC-Anot',
		mallet: 'LdoD-Jogo-Class',
		class: 'LdoD-Mallet,',
		twitter: 'LdoD-Twitter',

		header_search: 'Búsqueda',
		header_search_simple: 'Búsqueda Sencilla',
		header_search_advanced: 'Búsqueda Avanzada',

		header_virtual: 'Virtual',
		header_virtualeditions: 'Ediciones Virtuales',
		general_classificationGame: 'Juego de Clasificación',

		header_admin: 'Admin',
		fragments_management: 'Administrar Fragmentos',
		user_management: 'Administrar Usuarios',
		virtual_editions_management: 'Administrar Ediciones Virtuales',
		tweets_management: 'Administrar Tweets',
		error: 'Algo salió mal. Vuelve a intentarlo más tarde',
	},
};
