/** @format */

export default [
	{
		editor: 'Jerónimo Pizarro',
		text: 'E eu offereço-te este livro porque sei que elle é bello e inutil.',
		number: '17',
		path: 'Fr449/inter/Fr449_WIT_ED_CRIT_P',
	},
	{
		editor: 'Jacinto do Prado Coelho',
		text: 'Senti-me agora respirar como se houvesse practicado uma cousa nova, ou atrazada.',
		number: '188',
		path: 'Fr157/inter/Fr157_WIT_ED_CRIT_C',
	},
	{
		editor: 'Teresa Sobral Cunha',
		text: 'Em mim foi sempre menor a intensidade das sensações que a intensidade da sensação delas.',
		number: '283',
		path: 'Fr309/inter/Fr309_WIT_ED_CRIT_SC',
	},
	{
		editor: 'Richard Zenith',
		text: 'O silêncio que sai do som da chuva espalha-se, num crescendo de monotonia cinzenta, pela rua estreita que fito.',
		number: '41',
		path: 'Fr175/inter/Fr175_WIT_ED_CRIT_Z',
	},
	{
		editor: 'Jerónimo Pizarro',
		text: 'A grande terra, que serve os mortos, serviria, menos maternalmente, esses papeis.',
		number: '387',
		path: 'Fr159.b/inter/Fr159_b_WIT_ED_CRIT_P_1',
	},
	{
		editor: 'Teresa Sobral Cunha',
		text: 'Em cada pingo de chuva a minha vida falhada chora na natureza.',
		number: '266',
		path: 'Fr390/inter/Fr390_WIT_ED_CRIT_SC',
	},
	{
		editor: 'Jacinto do Prado Coelho',
		text: 'Como nos dias em que a trovoada se prepara e os ruidos da rua fallam alto com uma voz solitária.',
		number: '45',
		path: 'Fr042/inter/Fr042_WIT_ED_CRIT_C',
	},
	{
		editor: 'Teresa Sobral Cunha',
		text: 'Ninguém estava quem era, e o patrão Vasques apareceu à porta do gabinete para pensar em dizer qualquer coisa.',
		number: '441',
		path: 'Fr043/inter/Fr043_WIT_ED_CRIT_SC',
	},
	{
		editor: 'Richard Zenith',
		text: "'Vem aí uma grande trovoada', disse o Moreira, e voltou a página do Razão.",
		number: '183',
		path: 'Fr044/inter/Fr044_WIT_ED_CRIT_Z',
	},
	{
		editor: 'Jerónimo Pizarro',
		text: 'E então, em plena vida, é que o sonho tem grandes cinemas.',
		number: '262',
		path: 'Fr149/inter/Fr149_WIT_ED_CRIT_P',
	},
	{
		editor: 'Jerónimo Pizarro',
		text: 'Lêr é sonhar pela mão de outrem.',
		number: '586',
		path: 'Fr554/inter/Fr554_WIT_ED_CRIT_P',
	},
	{
		editor: 'Jacinto do Prado Coelho',
		text: 'Devo ao ser guarda-livros grande parte do que posso sentir e pensar como a negação e a fuga do cargo.',
		number: '133',
		path: 'Fr198/inter/Fr198_WIT_ED_CRIT_C',
	},
	{
		editor: 'Teresa Sobral Cunha',
		text: 'Durmo sobre os cotovelos onde o corrimão me doe, e sei de nada como um grande prometimento.',
		number: '380',
		path: 'Fr030/inter/Fr030_WIT_ED_CRIT_SC',
	},
	{
		editor: 'Richard Zenith',
		text: 'Sentado á janela, contemplo com os sentidos todos esta coisa nenhuma da vida universal que está lá fora.',
		number: '50',
		path: 'Fr118/inter/Fr118_WIT_ED_CRIT_Z',
	},
	{
		editor: 'Jerónimo Pizarro',
		text: 'Já me cansa a rua, mas não, não me cansa - tudo é rua na vida.',
		number: '284',
		path: 'Fr523/inter/Fr523_WIT_ED_CRIT_P',
	},
	{
		editor: 'Jacinto do Prado Coelho',
		text: 'Mergulhou na sombra como quem entra na porta onde chega.',
		number: '485',
		path: 'Fr306a/inter/Fr306a_WIT_ED_CRIT_C',
	},
	{
		editor: 'Jacinto do Prado Coelho',
		text: 'Para mim os pormenores são coisas, vozes, lettras.',
		number: '163',
		path: 'Fr255/inter/Fr255_WIT_ED_CRIT_C',
	},
	{
		editor: 'Teresa Sobral Cunha',
		text: 'Entre mim e a vida há um vidro ténue.',
		number: '171',
		path: 'Fr447/inter/Fr447_WIT_ED_CRIT_SC',
	},
	{
		editor: 'Richard Zenith',
		text: 'Não toquemos na vida nem com as pontas dos dedos.',
		number: '284',
		path: 'Fr452/inter/Fr452_WIT_ED_CRIT_Z',
	},
	{
		editor: 'Jerónimo Pizarro',
		text: 'Não era isto, porém, que eu queria dizer.',
		number: '394',
		path: 'Fr264/inter/Fr264_WIT_ED_CRIT_P',
	},
	{
		editor: 'Jacinto do Prado Coelho',
		text: 'Minha alma está hoje triste até ao corpo.',
		number: '167',
		path: 'Fr269/inter/Fr269_WIT_ED_CRIT_C',
	},
	{
		editor: 'Jacinto do Prado Coelho',
		text: 'Eu não sei quem tu és, mas sei ao certo o que sou?',
		number: '254',
		path: 'Fr285/inter/Fr285_WIT_ED_CRIT_C',
	},
	{
		editor: 'Teresa Sobral Cunha',
		text: 'Pasmo sempre quando acabo qualquer coisa.',
		number: '711',
		path: 'Fr009/inter/Fr009_WIT_ED_CRIT_SC',
	},
	{
		editor: 'Richard Zenith',
		text: 'É uma oleografia sem remédio.',
		number: '25',
		path: 'Fr010/inter/Fr010_WIT_ED_CRIT_Z',
	},
	{
		editor: 'Jerónimo Pizarro',
		text: 'Toda a vida é um somno.',
		number: '197',
		path: 'Fr027/inter/Fr027_WIT_ED_CRIT_P',
	},
	{
		editor: 'Richard Zenith',
		text: 'Não consegui nunca ver-me de fora.',
		number: '338',
		path: 'Fr028/inter/Fr028_WIT_ED_CRIT_Z',
	},
	{
		editor: 'Jacinto do Prado Coelho',
		text: 'Jogar ás escondidas com a nossa consciencia de viver.',
		number: '370',
		path: 'Fr437/inter/Fr437_WIT_ED_CRIT_C',
	},
	{
		editor: 'Teresa Sobral Cunha',
		text: 'A arte livra-nos ilusoriamente da sordidez de sermos.',
		number: '456',
		path: 'Fr163/inter/Fr163_WIT_ED_CRIT_SC',
	},
	{
		editor: 'Richard Zenith',
		text: 'As coisas sonhadas só têm o lado de cá.',
		number: '346',
		path: 'Fr510/inter/Fr510_WIT_ED_CRIT_Z',
	},
	{
		editor: 'Jerónimo Pizarro',
		text: 'Sou uma placa photographica prolixamente impressionavel.',
		number: '59',
		path: 'Fr456/inter/Fr456_WIT_ED_CRIT_P',
	},
];
