component_depth: 1

languages:
  - java
  - groovy
  - javascript

exclude:
  - .*/webapp/resources/.*
  - .*/webapp/classification-game/.*
  - .*/webapp/ldod-visual/.*
  - .*/classification-game/.*
  - .*/ldod-visual/.*
