services:
  reverse-proxy:
    build: ./proxy-server
    network_mode: host

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'edition'
      MYSQL_USER: 'raimundo'
      MYSQL_PASSWORD: 'raimundo'
      MYSQL_ROOT_PASSWORD: 'raimundo'
      MYSQL_TCP_PORT: 3307

    network_mode: host

    volumes:
      - my-db:/var/lib/mysql

  docker-monolith:
    build: ./edition-ldod
    restart: on-failure
    depends_on:
      - db
    network_mode: host
    environment:
      dbAlias: jdbc:mysql//db:3307/edition?useSSL=false&useUnicode=true&amp;characterEncoding=UTF-8&amp;clobCharacterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull;
      dbUsername: raimundo
      dbPassword: raimundo

    volumes:
      - /opt/ldod/corpus/:/opt/ldod/corpus
      - /opt/ldod/corpus/files/:/opt/ldod/corpus/files/
      - /opt/ldod/corpus/stoplist-pt.txt:/opt/ldod/corpus/stoplist-pt.txt
      - /opt/ldod/inters/:/opt/ldod/inters/
      - /opt/ldod/facsimiles/:/opt/ldod/facsimiles/
      - /opt/ldod/encoding/:/opt/ldod/encoding/
      - /opt/ldod/export/:/opt/ldod/export/
      - /opt/ldod/indexer/:/opt/ldod/indexer/
      - /opt/ldod/tests/:/opt/ldod/tests/
      - /opt/ldod/social/aware/:/opt/ldod/social/aware/

  server:
    build: ./ldod-mfes/shell/
    restart: on-failure
    command: npm run docker
    network_mode: host

volumes:
  my-db:
