services:
  reverse-proxy:
    build: ./proxy-server
    network_mode: host

  server:
    build: ./ldod-mfes/shell/server/
    command: node server.mjs
    volumes:
      - .:/user/server
    network_mode: host
