version: '3.3'
services:
  db_service:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'edition'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'darfo'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'darfo'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'darfo'

    networks:
      - backend

    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3307'
    expose:
      # Opens port 3307 on the container
      - '3307'
      # Where our data will be persisted
#    volumes:
#      - my-db:/var/lib/mysql



  docker-service:
    image: docker-service
    restart: on-failure
    depends_on:
      - db_service
      - db_text
      - docker-text
      - db_user
      - docker-user
      - db_virtual
      - docker-virtual

    networks:
      - backend

    ports:
      - 8080:8080

    environment:
      dbAlias: jdbc:mysql://db_service:3306/edition?useUnicode=true&amp;characterEncoding=UTF-8&amp;clobCharacterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull;useSSL=false
      # Database username and password
      dbUsername: 'darfo'
      dbPassword: 'darfo'

    volumes:
      - /opt/ldod/corpus/:/opt/ldod/corpus
      - /opt/ldod/corpus/files/:/opt/ldod/corpus/files/
      - /opt/ldod/corpus/stoplist-pt.txt:/opt/ldod/corpus/stoplist-pt.txt
      - /opt/ldod/inters/:/opt/ldod/inters/
      - /opt/ldod/facsimiles/:/opt/ldod/facsimiles/
      - /opt/ldod/encoding/:/opt/ldod/encoding/
      - /opt/ldod/export/:/opt/ldod/export/
      - /opt/ldod/indexer/:/opt/ldod/indexer/
      - /opt/ldod/tests/:/opt/ldod/tests/
      - /opt/ldod/social/aware/:/opt/ldod/social/aware/

  db_text:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'text'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'darfo'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'darfo'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'darfo'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3308:3308'
    networks:
      - backend

    expose:
      # Opens port 3307 on the container
      - '3308'
      # Where our data will be persisted
#    volumes:
#      - my-db:/var/lib/mysql


  docker-text:
    image: docker-text
    restart: on-failure
    depends_on:
      - db_text
    networks:
      - backend
    ports:
      - 8081:8081

    environment:
      dbAlias: jdbc:mysql://db_text:3306/text?useUnicode=true&amp;characterEncoding=UTF-8&amp;clobCharacterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull;useSSL=false
        # Database username and password
      dbUsername: 'darfo'
      dbPassword: 'darfo'

    volumes:
        - /opt/ldod/corpus/:/opt/ldod/corpus/
        - /opt/ldod/corpus/files/:/opt/ldod/corpus/files/
        - /opt/ldod/corpus/stoplist-pt.txt:/opt/ldod/corpus/stoplist-pt.txt
        - /opt/ldod/inters/:/opt/ldod/inters/
        - /opt/ldod/facsimiles/:/opt/ldod/facsimiles/
        - /opt/ldod/encoding/:/opt/ldod/encoding/
        - /opt/ldod/export/:/opt/ldod/export/
        - /opt/ldod/indexer/:/opt/ldod/indexer/
        - /opt/ldod/tests/:/opt/ldod/tests/
        - /opt/ldod/social/aware/:/opt/ldod/social/aware/

  db_user:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'user'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'darfo'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'darfo'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'darfo'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3309:3309'
    networks:
      - backend

    expose:
      # Opens port 3309 on the container
      - '3309'
        # Where our data will be persisted
        #    volumes:
        #      - my-db:/var/lib/mysql

  docker-user:
    image: docker-user
    restart: on-failure
    depends_on:
      - db_user
    ports:
      - 8082:8082

    networks:
      - backend

    environment:
      dbAlias: jdbc:mysql://db_user:3306/user?useUnicode=true&amp;characterEncoding=UTF-8&amp;clobCharacterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull;useSSL=false
        # Database username and password
      dbUsername: 'darfo'
      dbPassword: 'darfo'

    volumes:
      - /opt/ldod/corpus/:/opt/ldod/corpus/
      - /opt/ldod/corpus/files/:/opt/ldod/corpus/files/
      - /opt/ldod/corpus/stoplist-pt.txt:/opt/ldod/corpus/stoplist-pt.txt
      - /opt/ldod/inters/:/opt/ldod/inters/
      - /opt/ldod/facsimiles/:/opt/ldod/facsimiles/
      - /opt/ldod/encoding/:/opt/ldod/encoding/
      - /opt/ldod/export/:/opt/ldod/export/
      - /opt/ldod/indexer/:/opt/ldod/indexer/
      - /opt/ldod/tests/:/opt/ldod/tests/
      - /opt/ldod/social/aware/:/opt/ldod/social/aware/


  db_virtual:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'virtual1'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'darfo'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'darfo'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'darfo'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3310:3310'
    networks:
      - backend

    expose:
      # Opens port 3309 on the container
      - '3310'
        # Where our data will be persisted
      #    volumes:
      #      - my-db:/var/lib/mysql


  docker-virtual:
    image: docker-virtual
    restart: on-failure
    depends_on:
      - db_virtual
    ports:
      - 8083:8083

    networks:
      - backend

    environment:
      dbAlias: jdbc:mysql://db_virtual:3306/virtual1?useUnicode=true&amp;characterEncoding=UTF-8&amp;clobCharacterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull;useSSL=false
      # Database username and password
      dbUsername: 'darfo'
      dbPassword: 'darfo'

    volumes:
      - /opt/ldod/corpus/:/opt/ldod/corpus/
      - /opt/ldod/corpus/files/:/opt/ldod/corpus/files/
      - /opt/ldod/corpus/stoplist-pt.txt:/opt/ldod/corpus/stoplist-pt.txt
      - /opt/ldod/inters/:/opt/ldod/inters/
      - /opt/ldod/facsimiles/:/opt/ldod/facsimiles/
      - /opt/ldod/encoding/:/opt/ldod/encoding/
      - /opt/ldod/export/:/opt/ldod/export/
      - /opt/ldod/indexer/:/opt/ldod/indexer/
      - /opt/ldod/tests/:/opt/ldod/tests/
      - /opt/ldod/social/aware/:/opt/ldod/social/aware/

  db_recommendation:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'recommendation'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'darfo'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'darfo'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'darfo'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3311:3311'
    networks:
      - backend

    expose:
      # Opens port 3309 on the container
      - '3311'
      # Where our data will be persisted
      #    volumes:
      #      - my-db:/var/lib/mysql


  docker-recommendation:
     image: docker-recommendation
     restart: on-failure
     depends_on:
        - db_recommendation
     ports:
        - 8084:8084

     networks:
        - backend

     environment:
       dbAlias: jdbc:mysql://db_recommendation:3306/recommendation?useUnicode=true&amp;characterEncoding=UTF-8&amp;clobCharacterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull;useSSL=false
        # Database username and password
       dbUsername: 'darfo'
       dbPassword: 'darfo'

     volumes:
        - /opt/ldod/corpus/:/opt/ldod/corpus/
        - /opt/ldod/corpus/files/:/opt/ldod/corpus/files/
        - /opt/ldod/corpus/stoplist-pt.txt:/opt/ldod/corpus/stoplist-pt.txt
        - /opt/ldod/inters/:/opt/ldod/inters/
        - /opt/ldod/facsimiles/:/opt/ldod/facsimiles/
        - /opt/ldod/encoding/:/opt/ldod/encoding/
        - /opt/ldod/export/:/opt/ldod/export/
        - /opt/ldod/indexer/:/opt/ldod/indexer/
        - /opt/ldod/tests/:/opt/ldod/tests/
        - /opt/ldod/social/aware/:/opt/ldod/social/aware/

  db_game:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'game'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'darfo'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'darfo'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'darfo'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3312:3312'
    networks:
      - backend

    expose:
      # Opens port 3309 on the container
      - '3312'
      # Where our data will be persisted
      #    volumes:
      #      - my-db:/var/lib/mysql


  docker-game:
    image: docker-game
    restart: on-failure
    depends_on:
      - db_game
    ports:
      - 8085:8085

    networks:
      - backend

    environment:
      dbAlias: jdbc:mysql://db_game:3306/game?useUnicode=true&amp;characterEncoding=UTF-8&amp;clobCharacterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull;useSSL=false
      # Database username and password
      dbUsername: 'darfo'
      dbPassword: 'darfo'

    volumes:
      - /opt/ldod/corpus/:/opt/ldod/corpus/
      - /opt/ldod/corpus/files/:/opt/ldod/corpus/files/
      - /opt/ldod/corpus/stoplist-pt.txt:/opt/ldod/corpus/stoplist-pt.txt
      - /opt/ldod/inters/:/opt/ldod/inters/
      - /opt/ldod/facsimiles/:/opt/ldod/facsimiles/
      - /opt/ldod/encoding/:/opt/ldod/encoding/
      - /opt/ldod/export/:/opt/ldod/export/
      - /opt/ldod/indexer/:/opt/ldod/indexer/
      - /opt/ldod/tests/:/opt/ldod/tests/
      - /opt/ldod/social/aware/:/opt/ldod/social/aware/

  docker-activemq:
    image: rmohr/activemq
    restart: on-failure
    networks:
      - backend
    ports:
    - 61616:61616
    - 8161:8161

networks:
  backend:
    driver: bridge

# Names our volume
volumes:
  my-db: