<h3>1. La norma XML TEI</h3>
<p>Todas las transcripciones del <em>Archivo LdoD </em>est&aacute;n codificadas de acuerdo con las <a href="http://www.tei-c.org/Guidelines/" target="new"><em>TEI Guidelines</em></a> (Text Encoding and Interchange). Estas directrices designan una norma de  codificaci&oacute;n de textos desarrollada desde 1988 por un consorcio de  instituciones &mdash; el <a href="http://www.tei-c.org/index.xml" target="new">Text Encoding Initiative Consortium</a>. La norma TEI define un amplio conjunto de elementos y atributos en el lenguaje XML (<a href="https://en.wikipedia.org/wiki/XML" target="new">Extensible Markup Language</a>) que permiten representar caracter&iacute;sticas estructurales, concetuales y de  visualizaci&oacute;n de los textos. Teniendo en cuenta que el formato XML es un  lenguaje de codificaci&oacute;n de textos legible por m&aacute;quinas y humanos, la norma TEI  puede describirse como un m&eacute;todo de an&aacute;lisis textual para el procesamiento  digital. Se aprovecha de la interoperabilidad del formato XML para describir  detalladamente hechos y eventos textuales, a trav&eacute;s de una sintaxis y sem&aacute;ntica  espec&iacute;ficas. Se trata de una convenci&oacute;n muy poderosa, compuesta por m&oacute;dulos de  codificaci&oacute;n para todos los tipos de problemas de representaci&oacute;n de estructuras  y formas textuales &mdash; desde los inicios de la escritura hasta los documentos  electr&oacute;nicos actuales. La actual versi&oacute;n de las <em>Guidelines for Electronic  Text Encoding and Interchange</em> (TEI P5) se public&oacute; en noviembre de 2007 y se  actualiza peri&oacute;dicamente. En el momento en que escribimos, la &uacute;ltima  actualizaci&oacute;n se realiz&oacute; en julio de 2017 (versi&oacute;n 3.2.0).</p>
<p>
<strong>&nbsp;</strong>
</p>
<h3>2. XML TEI aplicado al <em>Libro del desasosiego</em></h3>
<p>
  En el caso del <em>Archivo  LdoD</em>, el esquema de codificaci&oacute;n desarrollado implic&oacute; la adopci&oacute;n del  m&eacute;todo de segmentaci&oacute;n paralela y la creaci&oacute;n de un aparato cr&iacute;tico que trata  todas las transcripciones como variaciones textuales. Por lo tanto, es posible  comparar autom&aacute;ticamente entre s&iacute; no s&oacute;lo variaciones que ocurren en los  testimonios, sino tambi&eacute;n variaciones que ocurren entre las transcripciones de  un testimonio en las diferentes ediciones. Aunque los testimonios est&aacute;n  marcados como tal, todas las variaciones (sean de los originales, sean de las  ediciones) se procesan en un mismo plano. A nivel de la codificaci&oacute;n textual,  esta decisi&oacute;n expresa el principio te&oacute;rico que subyace al<em> Archivo LdoD:</em> el de mostrar el <em>Libro  del desasosiego</em> como proyecto autoral y como proyecto editorial, haciendo  posible observar la transformaci&oacute;n del archivo en ediciones como un proceso  din&aacute;mico de generaci&oacute;n de variaciones textuales.</p>
  
<p>La matriz de codificaci&oacute;n XML TEI permite comprender lo  que en nuestro modelo de virtualizaci&oacute;n del <em>Libro  del desasosiego</em> describimos como la dimensi&oacute;n gen&eacute;tica, es decir, el  proceso de inscripci&oacute;n autoral (escrita y reescrita), y aquello que designamos la  dimensi&oacute;n social, esto es, el proceso hist&oacute;rico de reinscripci&oacute;n editorial y  socializaci&oacute;n de los textos (edici&oacute;n y reedici&oacute;n) bajo formas editoriales y  bibliogr&aacute;ficas espec&iacute;ficas (Portela y Silva, 2014). Por su parte, la dimensi&oacute;n  virtual (que es una designaci&oacute;n de la socializaci&oacute;n textual del <em>Libro del desasosiego</em> en el contexto  espec&iacute;fico del <em>Archivo LdoD</em>) consiste  en la posibilidad de construir ediciones virtuales a trav&eacute;s de la combinaci&oacute;n  de las unidades textuales definidas por las interpretaciones autorales y/o por las interpretaciones editoriales  (heredando por lo tanto la estructura XML TEI de esas unidades). El dinamismo  del <em>Archivo LdoD</em> depende de la  modularizaci&oacute;n producida por su modelo de datos, pero tambi&eacute;n de la  versatilidad en la comparaci&oacute;n de transcripciones garantizada por su modelo de  codificaci&oacute;n textual.</p>
<p>
  Por lo tanto, la codificaci&oacute;n XML TEI se utiliza simult&aacute;neamente  en su potencial representacional &mdash; es decir, en la posibilidad de una  descripci&oacute;n granular de eventos espec&iacute;ficos en la superficie de inscripci&oacute;n &mdash; y  en su potencial relacional &mdash; es decir, en la posibilidad de lectura instant&aacute;nea  de micro y macro-variaciones a diferentes escalas textuales dentro del corpus.  Es como si todas las transcripciones de todos los testimonios y de todas las  ediciones formaran parte de un solo &aacute;rbol, haciendo palabras, signos de  puntuaci&oacute;n, espacios en blanco, divisiones de p&aacute;rrafo y divisiones de texto  comparables entre s&iacute;. La exhaustividad y complejidad de la codificaci&oacute;n de las  variaciones permite transitar recursivamente entre tres escalas: escala del  car&aacute;cter, de la se&ntilde;al de puntuaci&oacute;n y del espacio en blanco como unidades  m&iacute;nimas de inscripci&oacute;n; escala de la palabra, de la frase, del p&aacute;rrafo y del  bloque textual como unidades sem&aacute;nticas; y escala de la secuencia ordenada de  textos y del libro como instanciaci&oacute;n discursiva y material de una cierta idea  de la obra.</p>
  <p>
<strong>&nbsp;</strong>
</p>
<h3>3. Criterios de codificaci&oacute;n</h3>
<p>
El equipo del <em>Archivo  LdoD </em>defini&oacute; un conjunto de criterios de codificaci&oacute;n de los diversos actos  de inscripci&oacute;n autoral y editorial. Estos criterios est&aacute;n, a veces,  condicionados por la necesidad de simplificar el procesamiento y la  visualizaci&oacute;n de las marcaciones. Esta secci&oacute;n explica las principales opciones  para garantizar el equilibrio entre el rigor textual y sem&aacute;ntico de la  marcaci&oacute;n, por un lado, as&iacute; como la legibilidad de la visualizaci&oacute;n de la capa  gen&eacute;tica y de las comparaciones entre transcripciones, por otro. Aunque haya un  componente mim&eacute;tico topogr&aacute;fico en las marcaciones de los testimonios, este est&aacute;  subordinado al modelo abstracto de datos cuya funci&oacute;n principal es garantizar  la comparabilidad de las transcripciones y ordenaciones de los documentos de  cada edici&oacute;n. Nuestro objetivo principal no es imitar los documentos sino  modelarlos para procesamiento.</p>

<p><strong>Codificaci&oacute;n  de espacios y de l&iacute;neas de divisi&oacute;n</strong><br>
  Los espacios entre p&aacute;rrafos, entre t&iacute;tulo y texto, y  entre bloques de texto <em>se marcaron en sus  proporciones relativas</em>, tanto en lo que se refiere a los testimonios, como  a lo que se refiere a las ediciones. En lugar de una sangr&iacute;a de la primera  l&iacute;nea del p&aacute;rrafo, hemos optado por un espacio de intervalo entre todos los  p&aacute;rrafos, con el objetivo de mejorar la legibilidad de las transcripciones en  la lectura en pantalla. Todos los dem&aacute;s espacios corresponden a espacios que  constan de los testimonios y de las ediciones. Todas las l&iacute;neas de divisi&oacute;n  corresponden tambi&eacute;n a l&iacute;neas que constan de los testimonios y de las  ediciones. Espacios y l&iacute;neas son elementos importantes en la articulaci&oacute;n de  las divisiones internas y externas de cada texto.</p>
  
<p><strong>Codificaci&oacute;n  de eliminados</strong><br>
  La marcaci&oacute;n de texto eliminado (&lt;del&gt;) se hizo con  los valores &ldquo;overstrike&rdquo; y &ldquo;overtyped.&rdquo; Ambos se visualizan a trav&eacute;s de una  l&iacute;nea sobre la palabra borrada.</p>
  
<p><strong>Codificaci&oacute;n  de acrecentados</strong><br>
  La marcaci&oacute;n de los acrecentados (&lt;add&gt;) se hizo  con los valores &ldquo;below&rdquo;, &ldquo;above&rdquo;, &ldquo;inline&rdquo;,  &ldquo;top&rdquo;, &ldquo;bottom&rdquo; y &ldquo;margin&rdquo;,  que definen la posici&oacute;n (&lt;place&gt;) del acrecentado relativamente al  segmento de texto al que se aplica o al lugar en que aparece en la p&aacute;gina. El  valor &ldquo;margin&rdquo; fue generalmente reservado para texto a&ntilde;adido en los m&aacute;rgenes,  pero<em> no para texto que contin&uacute;a en los  m&aacute;rgenes</em>, como a menudo sucede. En estos casos el cambio de lugar del texto  en la p&aacute;gina es se&ntilde;alado s&oacute;lo por quiebra de l&iacute;nea o por quiebra de l&iacute;nea y un  espacio.</p>
  
<p><strong>Codificaci&oacute;n  de sustituciones</strong><br>
  La codificaci&oacute;n de sustituciones (&lt;subst&gt;) implica  la marcaci&oacute;n de un elemento eliminado &lt;del&gt; y de un elemento acrecentado  &lt;add&gt;. La visualizaci&oacute;n simple de la transcripci&oacute;n del testimonio puede a  veces sugerir que un elemento es un acrecentado, ya que es precedido por la  se&ntilde;al &#8743;, utilizado para se&ntilde;alar los inseridos.  En estos casos, la ambig&uuml;edad puede ser aclarada si se seleccionan  simult&aacute;neamente las casillas &ldquo;mostrar eliminados&rdquo;, &ldquo;realzar acrecentados&rdquo; y &ldquo;realzar  sustituciones&rdquo;. En el segundo p&aacute;rrafo del testimonio <a href="https://ldod.uc.pt/fragments/fragment/Fr044/inter/Fr044_WIT_MS_Fr044a_51" target="new">BNP/E3 1-50r</a>, por ejemplo,  la interfaz muestra un acrecentado (dean- teira &#8743;d&rsquo;ella) cuando el testimonio s&oacute;lo tiene la cancelaci&oacute;n de  la terminaci&oacute;n plural (dean- teira d&rsquo;ellas). En este caso, la opci&oacute;n de  marcaci&oacute;n implic&oacute; explicitar la sustituci&oacute;n de &ldquo;d&rsquo;ellas&rdquo; por &ldquo;d&rsquo;ella&rdquo; (como si  hubiera, de hecho, un acrecentado), ya que &eacute;sta es la implicaci&oacute;n sem&aacute;ntica de  la eliminaci&oacute;n. Esta regla de marcaci&oacute;n<em> se aplic&oacute; a todas las ocurrencias en las que la eliminaci&oacute;n de una parte de la  palabra la transforma en otra palabra, por ejemplo, un n&uacute;mero plural en un  n&uacute;mero singular o un g&eacute;nero masculino en un g&eacute;nero femenino.</em> Aunque no haya  un a&ntilde;adido, la alteraci&oacute;n es gr&aacute;fica y sem&aacute;nticamente marcada como si hubiera.  La desambiguaci&oacute;n de estas opciones de codificaci&oacute;n implica se&ntilde;alar, al mismo  tiempo, las casillas &ldquo;mostrar eliminados&rdquo;, &ldquo;realzar acrecentados&rdquo; y &ldquo;mostrar  sustituciones&rdquo;, as&iacute; como la colaci&oacute;n con el facs&iacute;mil digital. Esta opci&oacute;n fue  tomada por motivos de visualizaci&oacute;n, ya que el marcado de letras aisladas  resultar&iacute;a en la presentaci&oacute;n de un espacio antes y despu&eacute;s de la letra,  perjudicando la legibilidad. Las opciones &ldquo;mostrar eliminados&rdquo; y &ldquo;realzar  acrecentado&rdquo; no se sincronizaron (lo que ayudar&iacute;a a aclarar esa ambig&uuml;edad) ya  que su aplicaci&oacute;n independiente permite ver m&aacute;s claramente los distintos lugares  de revisi&oacute;n.</p>
  
<p><strong>Codificaci&oacute;n de variantes</strong><br>
  La marcaci&oacute;n de las variantes se visualiza a trav&eacute;s de la  presencia simult&aacute;nea de las alternativas en un color diferente al del resto del  texto. Cuando se pasa sobre cada variante, surge el valor de probabilidad que  le est&aacute; asociado, que resulta de la divisi&oacute;n de la unidad por el n&uacute;mero de  variantes textuales. En el primer p&aacute;rrafo del testimonio <a href="https://ldod.uc.pt/fragments/fragment/Fr044/inter/Fr044_WIT_MS_Fr044a_51" target="new">BNP/E3 1-50r</a>, por ejemplo, la interfaz muestra las variantes &ldquo;rancor&rdquo; y  &ldquo;torpor&rdquo; con una probabilidad de ser excluidas de 0.5 cada una (&ldquo;excl 0.5&rdquo;).  Cuando hay tres variantes, la distribuci&oacute;n es generalmente una combinaci&oacute;n de  0.3, 0.3 y 0.4. Sin embargo, hay casos en que la necesidad de combinar la  marcaci&oacute;n topogr&aacute;fica con la marcaci&oacute;n de variantes <em>implic&oacute; la utilizaci&oacute;n de m&aacute;s valores que el n&uacute;mero de variantes  efectivas</em>, ya que las quiebras de l&iacute;nea no pueden ser marcados dentro de  los valores de probabilidad y es necesario volver a marcar la variante como  variante despu&eacute;s de cada quiebra de l&iacute;nea. En estos casos, el valor de la  probabilidad indicado es arbitrario y debe ajustarse para reflejar el n&uacute;mero de  variantes y no el n&uacute;mero de quiebras de l&iacute;nea, como sucede. Se trata de una  situaci&oacute;n que se deriva de la imposibilidad de encajar esas dos jerarqu&iacute;as de  marcaci&oacute;n.</p>
  
<p><strong>Codificaci&oacute;n  de variaciones</strong><br>
  La codificaci&oacute;n adoptada permite adem&aacute;s observar todas  las variaciones existentes entre las interpretaciones, o sea, permite comparar  la nueva transcripci&oacute;n de los testimonios con la transcripci&oacute;n Prado  Coelho-1982 con la transcripci&oacute;n Sobral Cunha-2008 con la transcripci&oacute;n  Zenith-2012 con la transcripci&oacute;n Pizarro-2010 para cada fragmento del <em>Libro del desasosiego.</em> El aparato  cr&iacute;tico (&lt;app&gt;) de estas variaciones fue clasificado de acuerdo con cinco  tipolog&iacute;as (&lt;type&gt;): &ldquo;orthographic&rdquo; para identificar variaciones  ortogr&aacute;ficas; &ldquo;punctuation&rdquo; para se&ntilde;alar variaciones de puntuaci&oacute;n; &ldquo;paragraph&rdquo;  para marcar variaciones en la divisi&oacute;n de p&aacute;rrafos; &ldquo;style&rdquo; para identificar  variaciones de estilo tipogr&aacute;fico (por ejemplo, uso de cursiva o de  may&uacute;sculas); y &ldquo;substantive&rdquo; para indicar diferencias en la palabra transcrita (por  ejemplo, cuando los expertos optan por variantes divergentes o leen de forma  diferente determinado paso). Las variaciones marcadas (que se refieren a las  diferencias existentes<em> en el conjunto de  todas las interpretaciones de un determinado fragmento</em>) son visibles tanto  a trav&eacute;s del realce de color, como a trav&eacute;s de la tabla de variaciones relativa  a cada comparaci&oacute;n.</p>
<p>
<strong>&nbsp;</strong>
</p>
<h3>4. Informaci&oacute;n adicional</h3>
  Quien est&eacute; interesado en una descripci&oacute;n detallada de las  opciones de codificaci&oacute;n puede consultar la matriz de un archivo XML comentado <strong><a target="_blank" href="/encoding/LdoD_XML-Template_ES.xml">AQU&Iacute;</a></strong>. Se sugiere tambi&eacute;n la lectura del art&iacute;culo siguiente: Ant&oacute;nio Rito Silva y Manuel Portela, &ldquo;<a href="http://jtei.revues.org/1171" target="new">TEI4LdoD:  Textual Encoding and Social Editing in Web 2.0 Environments.</a>&rdquo; <em>Journal of the Text Encoding Initiative</em> 8 (2014-2015).</p>
<p>&nbsp;</p>
<p>[actualizado 08-09-2017]
</p>
