export const messages = {
    pt: {
        Different_changePasswordForm: 'As senhas não são iguais',
        DoNotMatch_changePasswordForm: 'Senha errada',
        Email: 'O endereço de correio eletrónico não está correto',
        Exist_editUserForm: 'Nome de utilizador existe',
        NotEmpty: 'Campo obrigatório',
        size: 'Deve conter no mínimo 6 caracteres',
        alphabetic_error: 'Deve ser alfabético',
        authorial: 'Testemunho',
        authorial_source: 'Testemunhos',
        category_add: 'Adicionar Categoria',
        corpus_load: 'Carregar Corpus',
        corpus_load_title: 'Carregar Ficheiro TEI com Corpus',
        criteira_mediasource_facebook: 'Facebook',
        criteira_mediasource_nomediasource: 'Nenhuma rede social',
        criteira_mediasource_twitter: 'Twitter',
        criteira_timewindow_begindate: 'Data de início das citações',
        criteira_timewindow_enddate: 'Data de fim das citações',
        criteria_frequency: 'Frequência mínima',
        criteria_frequency_manage: 'Escolha um número mínimo de vezes que os fragmentos tenham sido citados',
        criteria_geolocation: 'Localização Geográfica',
        criteria_geolocation_Angola: 'Angola',
        criteria_geolocation_Brazil: 'Brasil',
        criteria_geolocation_Japan: 'Japão',
        criteria_geolocation_Lebanon: 'Líbano',
        criteria_geolocation_Mozambique: 'Moçambique',
        criteria_geolocation_Portugal: 'Portugal ',
        criteria_geolocation_Spain: 'Espanha',
        criteria_geolocation_UnitedKingdom: 'Inglaterra',
        criteria_geolocation_UnitedStates: 'Estados Unidos',
        criteria_geolocation_everycountry: 'Todos os países',
        criteria_geolocation_manage: 'Escolha o país do qual pretende recolher as citações',
        criteria_geolocation_nocountry: 'Nenhum país',
        criteria_mediasource: 'Rede Social	 ',
        criteria_mediasource_manage: 'Escolha a rede social da qual pretende recolher as citações',
        criteria_timewindow: 'Janela temporal	 ',
        criteria_timewindow_begindate_manage: 'Escolha a data de início de recolha de citações',
        criteria_timewindow_enddate_manage: 'Escolha a data de fim de recolha de citações',
        deletefragment_header: 'Apagar Fragmento',
        deletefragment_title: 'Escolha o fragmento a apagar',
        edition_experts: 'Edições dos Peritos',
        edituserform_newusername_pattern: 'Deve ser alfanumérico',
        exceptions_error: 'Ocorreu um erro:',
        exceptions_title: 'Exceções do LdoD',
        fragment: 'Fragmento',
        fragment_alignspace: 'Alinhar Espaços',
        fragment_base: 'Testemunho Base:',
        fragment_codified: 'Fragmentos Codificados',
        fragment_compare: 'Testemunho a Comparar:',
        fragment_delete: 'Apagar Fragmento',
        fragment_highlightdifferences: 'Realçar Diferenças',
        fragment_highlightinserted: 'Realçar Inseridos',
        fragment_highlightsubstitutions: 'Realçar Substituições',
        fragment_linebyline: 'Linha-a-linha',
        fragment_load: 'Carregar Fragmento',
        fragment_load_title: 'Carregar Ficheiro TEI com Fragmento',
        fragment_load_titleAll: 'Carregar Vários Ficheiros TEI com Vários Fragmentos',
        fragment_showdeleted: 'Mostrar Apagados',
        fragment_showfacs: 'Fac-símile',
        fragment_shownotes: 'Mostrar Notas',
        fragment_tt_additions: 'Realça texto inserido por Fernando Pessoa ',
        fragment_tt_deletions: 'Mostra texto apagado por Fernando Pessoa ',
        fragment_tt_highlights: 'Realça variações entre as transcrições em comparação',
        fragment_tt_image: 'Imagem dos documentos originais',
        fragment_tt_information: 'Mostra a informação sobre as fontes das transcrições ',
        fragment_tt_substitution: 'Realça texto apagado e substituído por Fernando Pessoa',
        fragment_variationstable: 'Tabela de Variações',
        fragment_visualization: 'Atributos de Visualização:',
        fragmentlist_showdetails: 'Mostrar Detalhes',
        fragmentlist_title: 'Fragmentos do LdoD',
        fragments: 'Fragmentos',
        fragments_load: 'Carregar Fragmentos',
        game_classification_description_empty: 'Introduza a descrição',
        game_classification_inter_null: 'Selecione uma interpretação',
        general_LdoDLabel: 'Marca LdoD',
        general_access: 'Acesso',
        general_access_denied: 'Acesso recusado',
        general_add: 'Adicionar',
        general_annotations: 'Anotações',
        general_associate: 'Associar',
        general_author: 'Autor',
        general_back: 'Voltar',
        general_cancel: 'Cancelar',
        general_categories: 'Categorias',
        general_category: 'Categoria',
        general_category_exists: 'Já existe essa categoria',
        general_category_extracted: 'Categoria Extraída',
        general_category_merged: 'Categorias Combinadas',
        general_citations: 'Citações',
        general_citations_twitter: 'Citações no Twitter',
        general_classificationGame: 'Jogo de Classificação',
        general_classificationGame_visitWebsite: 'Clique aqui para visitar o Jogo de Classificação',
        general_close: 'Fechar',
        general_columns: 'Colunas',
        general_contributionsOf: 'Contributos de',
        general_country: 'País',
        general_create: 'Criar',
        general_date: 'Data',
        general_delete: 'Apagar',
        general_deleteconfirmation: 'Tem a certeza?',
        general_deprecated: 'Obsoleta',
        general_description: 'Descrição',
        general_deselect: 'Desselecionar',
        general_dimensions: 'Dimensões',
        general_edit: 'Editar',
        general_edition: 'Edição',
        general_editor: 'Editor',
        general_editors: 'Editores',
        general_export: 'Exportar',
        general_extract: 'Extrair',
        general_facsimiles: 'Fac-símiles',
        general_format: 'Formato',
        general_generate: 'Gerar',
        general_heteronym: 'Heterónimo',
        general_heteronym_notassigned: 'Não atribuído',
        general_identification: 'Identificação',
        general_information: 'Informação',
        general_join: 'Participar',
        general_journal: 'Revista',
        general_language: 'Língua',
        general_leaf: 'Folha',
        general_loading: 'Procurando...',
        general_manage: 'Gerir',
        general_manager: 'Gestor',
        general_manuscript: 'Manuscrito',
        general_material: 'Material',
        general_merge: 'Juntar',
        general_name: 'Nome',
        general_no: 'Não',
        general_note: 'Nota',
        general_number_of: 'Número de',
        general_operation: 'Operação',
        general_paper: 'Papel',
        general_participant: 'Participante',
        general_percentage: 'Percentagem',
        general_players: 'Jogadores',
        general_points: 'Pontos',
        general_position: 'Posição',
        general_printed: 'Impresso',
        general_private: 'Privado',
        general_public: 'Público',
        general_public_pages: 'Páginas Públicas',
        general_published: 'Publicado',
        general_published_place: 'Local de Publicação',
        general_reading: 'Leitura',
        general_reading_start: 'Iniciar',
        general_recommendation: 'Recomendação',
        general_recommendation_config: 'Configuração das Recomendações',
        general_recommendations: 'Recomendações',
        general_remove: 'Retirar',
        general_removeAll: 'Retirar Todos',
        general_reset: 'Reiniciar',
        general_reset_list: 'Reiniciar a lista de recomendações anteriores',
        general_responsible: 'Responsável',
        general_save: 'Guardar',
        general_searching: 'Pesquisando...',
        general_searching_for: 'Procurar por...',
        general_sections: 'Secções',
        general_select: 'Selecionar',
        general_selected: 'Selecionado',
        general_signin: 'Entrar',
        general_sort_automatic: 'Ordenação Assistida',
        general_sort_manual: 'Ordenação Manual',
        general_sources: 'Fontes',
        general_structure: 'Estrutura',
        general_submit: 'Submeter',
        general_tags: 'Etiquetas',
        general_taxonomies: 'Taxonomias',
        general_taxonomies_manage: 'Gerir Taxonomias',
        general_taxonomies_number_iterations: 'Iterações',
        general_taxonomies_number_topics: 'Tópicos',
        general_taxonomies_number_words: 'Palavras',
        general_taxonomies_threshold_categories: 'Corte',
        general_taxonomy: 'Taxonomia',
        general_text: 'Texto',
        general_title: 'Título',
        general_transcription: 'Transcrição',
        general_type: 'Tipo',
        general_typescript: 'Datiloscrito',
        general_undo: 'Desfazer',
        general_update: 'Atualizar',
        general_useOfTag: 'Utilização da etiqueta',
        general_usedIn: 'Usado em',
        general_uses: 'Usa',
        general_weight: 'Peso',
        general_winner: 'Vencedor',
        general_words: 'Palavras',
        general_yes: 'Sim',
        header_about: 'Acerca',
        header_acknowledgements: 'Agradecimentos',
        header_privacy: 'Política de Privacidade',
        header_team: 'Equipa Editorial',
        header_admin: 'Admin',
        header_archive: 'Arquivo LdoD',
        header_articles: 'Artigos',
        header_authorialsources: 'Testemunhos',
        header_bibliography: 'Bibliografia',
        header_communities: 'Comunidades',
        header_conduct_accept: 'Ao registar-me como utilizador do Arquivo LdoD, aceito o código de conduta abaixo',
        header_conduct_error: 'Deve concordar com o código de conduta',
        header_contact: 'Contacto',
        header_conduct: 'Código de Conduta',
        header_copyright: 'Copyright',
        header_documents: 'Documentos',
        header_editions: 'Edições',
        header_editorialnotes: 'Notas Editoriais',
        header_encoding: 'Codificação de Texto',
        header_faq: 'Perguntas Frequentes',
        header_funded: 'Financiado',
        header_listfragments: 'Lista de Fragmentos',
        header_login: 'Iniciar Sessão',
        header_logout: 'Sair',
        header_manageeditions: 'Gerir Edições Virtuais',
        header_objectives: 'Objetivos',
        header_search: 'Pesquisa',
        header_search_advanced: 'Pesquisa Avançada',
        header_search_list: 'Lista de Fragmentos',
        header_search_similarfragments: 'Fragmentos Semelhantes',
        header_search_simple: 'Pesquisa Simples',
        header_sponsors: 'Apoios',
        header_title: 'Arquivo LdoD',
        header_videos: 'Vídeos',
        header_virtual: 'Virtual',
        header_virtualeditions: 'Edições Virtuais',
        info_experts: 'O mesmo testemunho pode ser interpretado como mais do que um texto pelos editores. Estas variações na divisão de fragmentos baseiam-se quer em marcações autógrafas (traços horizontais ou espaços entre blocos de texto), quer em interpretações sobre a proximidade semântica dos blocos textuais.',
        info_highlighting: 'O gradiente de cor aumenta consoante o número de diferenças entre as transcrições em comparação',
        info_virtualeditions: 'As edições virtuais contêm fragmentos escolhidos pelos seus editores a partir de outras edições.',
        info_virtualeditions_authenticate: 'Para criar uma edição virtual ou colaborar numa edição virtual existente é necessário autenticar-se',
        inserted: 'Inserido',
        interpretations: 'Interpretações',
        load: 'Carrregar',
        loading: 'A carregar',
        login_error: 'Não foi possível entrar, por favor, verifique o seu o nome de utilizador ou a senha...',
        login_password: 'Senha',
        login_username: 'Nome de utilizador',
        navigation_edition: 'Edição',
        okmessage_title: 'Sucesso:',
        pagenotfound_message: 'LdoD: Esta página não existe...',
        participantsForm_message2: 'Pedidos de Adesão',
        recommendation: 'Recomendações',
        recommendation_criteria: 'Critérios de Ordenação',
        recommendation_fragments: 'Fragmentos recomendados',
        recommendation_iteration: 'Iteração',
        recommendation_iterativeSort: 'Ordenação recursiva',
        recommendation_recommend: 'Recomendar',
        recommendation_recommended: 'Recomendada',
        recommendation_recommendedEdition: 'Edicão Recomendada',
        recommendation_setinitial: 'Colocar como Inicial',
        recommendation_similarFragments: 'Fragmentos Semelhantes',
        search: 'Pesquisar',
        search_addcriteria: 'Adicionar Critério',
        search_authorial: 'Testemunhos',
        search_complete: 'Pesquisa completa',
        search_date_begin: 'Desde',
        search_date_dated: 'Datado',
        search_date_end: 'Até',
        search_date_unDated: 'Não datado',
        search_inclusion_excludedFrom: 'Excluídos de',
        search_inclusion_includedIn: 'Incluídos em',
        search_keyword: 'Palavras-chave',
        search_ldod_with: 'Com marca LdoD',
        search_ldod_without: 'Sem marca LdoD',
        search_noResults: 'A pesquisa não produziu resultados',
        search_option_all: 'Todas',
        search_option_noAttribution: 'Não atríbuído',
        search_removecriteria: 'Remover Critério',
        search_rule_matchAll: 'De acordo com todos os seguintes critérios',
        search_rule_matchOne: 'De acordo com pelo menos um dos seguintes critérios',
        search_source: 'Tipos de fonte',
        search_text: 'Texto',
        search_title: 'Pesquisa por título',
        signup: 'Registo',
        signup_confirmation: 'O seu pedido foi submetido para autorização. Em caso de aceitação, um email de confirmação será enviado para a sua caixa de correio. A confirmação deve ocorrer no espaço de 24 horas.',
        signup_errorMessage: 'A sua conta {0} ainda não está associada com uma conta do Arquivo do LdoD. Registe-se por favor.',
        signup_message: 'Registar-se como utilizador do Arquivo LdoD',
        signup_token_authorized: 'Autorizado',
        signup_token_authorized_not: 'Não autorizado',
        signup_token_expired: 'O token de confirmação expirou',
        signup_token_invalid: 'O token de confirmação não é válido.',
        sourcelist_tt_LdoDLabel: 'Marcação explícita feita por Fernando Pessoa de que o documento pertence ao LdoD',
        sourcelist_tt_columns: 'Número de colunas por página da fonte',
        sourcelist_tt_date: 'Data inscrita ou atribuída ao fragmento',
        sourcelist_tt_dimensions: 'Descreve as dimensões dos testemunhos',
        sourcelist_tt_documents: 'Lista de Testemunhos',
        sourcelist_tt_facsimiles: 'Imagem dos documentos originais',
        sourcelist_tt_sources: 'Fac-símiles dos documentos originais de Fernando Pessoa (manuscritos, datiloscritos ou impressos)',
        sourcelist_tt_transcription: 'Transcrição topográfica feita pela equipa do Arquivo LdoD',
        sourcelist_tt_type: 'Descreve o tipo de documento como manuscrito, datiloscrito ou impresso',
        tableofcontents_editionof: 'Edição de',
        tableofcontents_fragmentsof: 'Fragmentos Atribuídos a ',
        tableofcontents_number: 'Número',
        tableofcontents_page: 'Página',
        tableofcontents_title: 'Título',
        tableofcontents_tt_date: 'Data inscrita ou atribuída ao fragmento',
        tableofcontents_tt_heteronym: 'Atribuição de heterónimo segundo o editor',
        tableofcontents_tt_number: 'Número do fragmento na edição',
        tableofcontents_tt_page: 'Página em que o fragmento se encontra',
        tableofcontents_tt_reading: 'Começar a ler o LdoD com recomendações',
        tableofcontents_tt_taxonomy: 'Taxonomia usada na edição',
        tableofcontents_tt_title: 'Título ou incipit do fragmento',
        tableofcontents_tt_usesEditions: 'Edições cuja transcrição e anotação são usadas',
        tableofcontents_tt_volume: 'Volume em que o fragmento se encontra',
        tableofcontents_usesEdition: 'Usa Edição',
        tableofcontents_usesEditions: 'Usa Edições',
        tableofcontents_volume: 'Volume',
        taxonomies_tt_catcut: 'Percentagem mínima necessária para um fragmento ser incluído num agrupamento (tem impacto no algoritmo de geração)',
        taxonomies_tt_combinedcategories: 'Categoria resultante do agrupamento de 2 ou mais categorias',
        taxonomies_tt_create: 'A taxonomia gerada agrupa os fragmentos de acordo com os parâmetros',
        taxonomies_tt_extractedcategory: 'Nova categoria resultante da seleção de um subconjunto fragmentos da categoria atual',
        taxonomies_tt_fragments: 'Fragmentos que pertencem à categoria',
        taxonomies_tt_name: 'Nome',
        taxonomies_tt_nrofiterations: 'Número de vezes que o algoritmo de geração executa para produzir resultados (tem impacto no algoritmo de geração, devendo ser superior a 1500)',
        taxonomies_tt_nroftopics: 'Número de grupos de fragmentos a gerar (tem impacto no algoritmo de geração; deve ser inferior ao número total de fragmentos na edição virtual)',
        taxonomies_tt_nrofwords: 'Número de palavras a usar no nome da categoria (não tem impacto no algoritmo de geração, serve apenas para definir o número de palavras a usar)',
        taxonomy_annotation: 'Anotar Fragmentos',
        taxonomy_annotation_all: 'Utilizadores Registados',
        taxonomy_annotation_members: 'Editores da Edição',
        taxonomy_manage: 'Gestão da Taxonomia',
        taxonomy_manage_members: 'Editores da Edição',
        taxonomy_manage_owners: 'Gestores da Edição',
        taxonomy_vocabulary: 'Vocabulário',
        taxonomy_vocabulary_closed: 'Fechado',
        taxonomy_vocabulary_open: 'Aberto',
        topics_generate_long: 'Adição de categorias aplicando um algoritmo de geração de tópicos',
        topics_generate_short: 'Gerar Tópicos',
        topics_topic: 'Tópico',
        user_active: 'Ativo',
        user_agree: 'Concordo',
        user_duplicateUsername: 'já está a ser usado',
        user_edit: 'Alterar utilizador',
        user_email: 'Endereço eletrónico',
        user_enabled: 'Confirmado',
        user_firstName: 'Primeiro nome',
        user_lastLogin: 'Último acesso',
        user_lastName: 'Apelido',
        user_list: 'Utilizadores',
        user_manage: 'Gestão de Utilizadores',
        virtual_editions_manage: 'Manage Virtual Editions',
        twitter_manage: 'Manage Tweets',
        user_one: 'A edição virtual deve ter pelo menos um participante',
        user_password: 'Alterar Senha',
        user_password_current: 'Senha atual',
        user_password_new: 'Nova senha',
        user_password_retype: 'Digite novamente a senha',
        user_role: 'Papel',
        user_role_admin: 'Administrador',
        user_role_user: 'Utilizador',
        user_roles: 'Papéis',
        user_unknown: 'Utilizador desconhecido',
        user_user: 'Utilizador',
        validateCreateCategoryForm_value: 'Falta o nome da categoria',
        validateGenerateTopics_iterations_positive: 'O número de iterações positivo deve ser positivo',
        validateGenerateTopics_iterations_value: 'Falta o número de iterações',
        validateGenerateTopics_threshold_range: 'Valor de corte deve ser entre 0 e 100',
        validateGenerateTopics_threshold_value: 'Falta o valor de corte',
        validateGenerateTopics_topics_number: 'Falta o número de tópicos a gerar',
        validateGenerateTopics_topics_positive: 'O número de tópicos deve ser positivo e menor que 100',
        validateGenerateTopics_words_number: 'Falta o número de palavras a incluir no nome da categoria',
        validateGenerateTopics_words_positive: 'O número de palavras deve ser positivo e menor que 10',
        virtual: 'Virtual',
        virtual_editions: 'Edições Virtuais',
        virtualcompare_comment: 'Comentário',
        virtualcompare_quote: 'Citação',
        virtualcompare_title: 'Comparação de anotações de edições virtuais',
        virtualcompare_user: 'Utilizador',
        virtualedition: 'Edição Virtual',
        virtualedition_acronym_alphanumeric: 'A sigla deve ser alfanumérica',
        virtualedition_acronym_blanks: 'A sigla tem espaços...',
        virtualedition_acronym_duplicate: 'Já existe uma edição virtual com essa sigla...',
        virtualedition_acronym_empty: 'Deve ser atribuído um valor à sigla...',
        virtualedition_acronym_length: 'Sigla com mais de 10 carateres',
        virtualedition_synopsis: 'Sinopse',
        virtualedition_title_empty: 'Deve ser introduzido um valor no título...',
        virtualedition_tt_access: 'Privado – A edição apenas pode ser visualizada pelos seus editores; Público – A edição é publicamente visível',
        virtualedition_tt_acronym: 'Sigla única que identifica a edição',
        virtualedition_tt_addFragment: 'Adicionar fragmentos',
        virtualedition_tt_create: 'Cria uma edição que pode ser colaborativamente construída pelos seus editores',
        virtualedition_tt_cut: 'Cortar',
        virtualedition_tt_date: 'Data de criação da edição',
        virtualedition_tt_delete: 'Remover a edição',
        virtualedition_tt_deleteFragment: 'Apagar fragmentos ',
        virtualedition_tt_edit: 'Alterar propriedades da edição',
        virtualedition_tt_join: 'Participar na edição (necessita de autenticação)',
        virtualedition_tt_manage: 'Aceder à gestão da edição (necessita autenticação)',
        virtualedition_tt_manage_annotations: 'Quem pode anotar os fragmentos',
        virtualedition_tt_manage_categories: 'Quem pode gerir as categorias: criar, apagar, alterar nome, juntar duas categorias e dividir uma categoria em duas',
        virtualedition_tt_manage_vocabulary: 'Vocabulário aberto: novas categorias podem ser criadas durante a anotação. Vocabulário fechado: durante a anotação apenas pode ser usado o conjunto de categorias pré-definido.',
        virtualedition_tt_movebottom: 'Mover para o fundo',
        virtualedition_tt_movedown: 'Mover para baixo',
        virtualedition_tt_moveposition: 'Mover para posição',
        virtualedition_tt_movetop: 'Mover para o topo',
        virtualedition_tt_moveup: 'Mover para cima',
        virtualedition_tt_participants: 'Adicionar ou remover editores da edição',
        virtualedition_tt_paste: 'Colar',
        virtualedition_tt_save: 'Guardar',
        virtualedition_tt_select: 'Edição fica acessível através do menu de topo Edições',
        virtualedition_tt_title: 'Título da edição',
        virtualedition_tt_use: 'A edição virtual usa todas as transcrições da edição escolhida',
        virtualeditionlist_acronym: 'Sigla',
        virtualeditionlist_createtitle: 'Criar uma nova Edição Virtual',
        virtualeditionlist_editvirtual: 'Editar Edição Virtual',
        virtualeditionlist_name: 'Título',
        virtualeditionlist_title: 'Edições Virtuais',
        general_reading_sequences: 'Sequências de Leitura',
        general_reading_visual: 'Livro Visual',
        general_editor_prado: 'Jacinto do Prado Coelho',
        general_editor_zenith: 'Richard Zenith',
        general_editor_cunha: 'Teresa Sobral Cunha',
        general_editor_pizarro: 'Jerónimo Pizarro',
        header_tutorials: 'Tutoriais e Oficinas',
        virtual_anot: 'LDOD-JPC-ANOT',
        virtual_class: 'LDOD-JOGO-CLASS',
        virtual_mallet: 'LDOD-MALLET',
        virtual_twitter: 'LDOD-TWITTER',
        header_book: 'Livro',
    },
    en: {
        Different_changePasswordForm: 'The passwords do not match',
        DoNotMatch_changePasswordForm: 'Wrong password',
        Email: 'Not a well-formed email address',
        Exist_editUserForm: 'Username already exists',
        NotEmpty: 'Required',
        size: 'Must be at least 6 characters',
        alphabetic_error: 'Must be alphabetic',
        authorial: 'Witness',
        authorial_source: 'Witnesses',
        category_add: 'Add Category',
        corpus_load: 'Load Corpus',
        corpus_load_title: 'Load TEI Corpus File',
        criteira_mediasource_facebook: 'Facebook',
        criteira_mediasource_nomediasource: 'No social network',
        criteira_mediasource_twitter: 'Twitter',
        criteira_timewindow_begindate: 'Begin date of citations',
        criteira_timewindow_enddate: 'End date of citations',
        criteria_frequency: 'Minimum frequency',
        criteria_frequency_manage: 'Choose the minimum number of times that the fragments have been cited',
        criteria_geolocation: 'Geographic Location',
        criteria_geolocation_Angola: 'Angola',
        criteria_geolocation_Brazil: 'Brazil',
        criteria_geolocation_Japan: 'Japan',
        criteria_geolocation_Lebanon: 'Lebanon',
        criteria_geolocation_Mozambique: 'Mozambique',
        criteria_geolocation_Portugal: 'Portugal ',
        criteria_geolocation_Spain: 'Spain',
        criteria_geolocation_UnitedKingdom: 'England',
        criteria_geolocation_UnitedStates: 'United States',
        criteria_geolocation_everycountry: 'Every country',
        criteria_geolocation_manage: 'Choose the country you want to collect citations from',
        criteria_geolocation_nocountry: 'No country',
        criteria_mediasource: 'Social Network\u0009 ',
        criteria_mediasource_manage: 'Choose the social network you want to collect citations from',
        criteria_timewindow: 'Time Window\u0009 ',
        criteria_timewindow_begindate_manage: 'Choose the begin date for collecting citations',
        criteria_timewindow_enddate_manage: 'Choose the end date for collecting citations',
        deletefragment_header: 'Delete Fragment',
        deletefragment_title: 'Choose fragment to delete',
        edition_experts: 'Expert Editions',
        edituserform_newusername_pattern: 'Should be alphanumeric',
        exceptions_error: 'Error:',
        exceptions_title: 'LdoD Exceptions',
        fragment: 'Fragment',
        fragment_alignspace: 'Align Spaces',
        fragment_base: 'Base Witness:',
        fragment_codified: 'Encoded Fragments',
        fragment_compare: 'Witness to Compare:',
        fragment_delete: 'Delete Fragment',
        fragment_highlightdifferences: 'Highlight Differences',
        fragment_highlightinserted: 'Highligh Inserted',
        fragment_highlightsubstitutions: 'Highlight Substitutions',
        fragment_linebyline: 'Line-by-line',
        fragment_load: 'Load Fragment',
        fragment_load_title: 'Load TEI Fragment File',
        fragment_load_titleAll: 'Load Several Files with Several TEI Fragments',
        fragment_showdeleted: 'Show Deleted',
        fragment_showfacs: 'Facsimile',
        fragment_shownotes: 'Show Notes',
        fragment_tt_additions: 'Highlights additions by Fernando Pessoa ',
        fragment_tt_deletions: 'Shows deletions by Fernando Pessoa ',
        fragment_tt_highlights: 'Highlights variations in compared transcriptions ',
        fragment_tt_image: 'Image of the original documents',
        fragment_tt_information: 'Shows information about transcription sources',
        fragment_tt_substitution: 'Highlights passages deleted for substitution by Fernando Pessoa',
        fragment_variationstable: 'Variations Table',
        fragment_visualization: 'Visualization Attributes:',
        fragmentlist_showdetails: 'Show Details',
        fragmentlist_title: 'LdoD Fragments',
        fragments: 'Fragments',
        fragments_load: 'Load Fragments',
        game_classification_description_empty: 'Description is missing',
        game_classification_inter_null: 'Select an interpretation',
        general_LdoDLabel: 'LdoD Label',
        general_access: 'Access',
        general_access_denied: 'Access denied',
        general_add: 'Add',
        general_annotations: 'Annotations',
        general_associate: 'Associate',
        general_author: 'Author',
        general_back: 'Back',
        general_cancel: 'Cancel',
        general_categories: 'Categories',
        general_category: 'Category',
        general_category_exists: 'The category already exists ',
        general_category_extracted: 'Extrat Category',
        general_category_merged: 'Merged Categories',
        general_citations: 'Citations',
        general_citations_twitter: 'Citations on Twitter',
        general_classificationGame: 'Classification Game',
        general_classificationGame_visitWebsite: 'Click here to go to the Classification Game',
        general_close: 'Close',
        general_columns: 'Columns',
        general_contributionsOf: 'Contributions of',
        general_country: 'Country',
        general_create: 'Create',
        general_date: 'Date',
        general_delete: 'Delete',
        general_deleteconfirmation: 'Are you sure?',
        general_deprecated: 'Deprecated',
        general_description: 'Description',
        general_deselect: 'Deselect',
        general_dimensions: 'Dimensions',
        general_edit: 'Edit',
        general_edition: 'Edition',
        general_editor: 'Editor',
        general_editors: 'Editors',
        general_export: 'Export',
        general_extract: 'Extract',
        general_facsimiles: 'Facsimiles',
        general_format: 'Format',
        general_generate: 'Generate',
        general_heteronym: 'Heteronym',
        general_heteronym_notassigned: 'Not assigned',
        general_identification: 'Identification',
        general_information: 'Information',
        general_join: 'Join',
        general_journal: 'Journal',
        general_language: 'Language',
        general_leaf: 'Leaf',
        general_loading: 'Searching...',
        general_manage: 'Manage',
        general_manager: 'Manager',
        general_manuscript: 'Manuscript',
        general_material: 'Material',
        general_merge: 'Merge',
        general_name: 'Name',
        general_no: 'No',
        general_note: 'Note',
        general_number_of: 'Number of',
        general_operation: 'Operation',
        general_paper: 'Paper',
        general_participant: 'Participant',
        general_percentage: 'Percentage',
        general_players: 'Players',
        general_points: 'Points',
        general_position: 'Position',
        general_printed: 'Printed',
        general_private: 'Private',
        general_public: 'Public',
        general_public_pages: 'Public Pages',
        general_published: 'Published',
        general_published_place: 'Publication Place',
        general_reading: 'Reading',
        general_reading_start: 'Start',
        general_recommendation: 'Recommendation',
        general_recommendation_config: 'Configuration of Recommendations',
        general_recommendations: 'Recommendations',
        general_remove: 'Remove',
        general_removeAll: 'Remove All',
        general_reset: 'Reset',
        general_reset_list: 'Reset the list of previous recommendations',
        general_responsible: 'Responsible',
        general_save: 'Save',
        general_searching: 'Searching...',
        general_searching_for: 'Search for...',
        general_sections: 'Sections',
        general_select: 'Select',
        general_selected: 'Selected',
        general_signin: 'Sign In',
        general_sort_automatic: 'Assisted Sorting',
        general_sort_manual: 'Manual Sort',
        general_sources: 'Sources',
        general_structure: 'Structure',
        general_submit: 'Submit',
        general_tags: 'Tags',
        general_taxonomies: 'Taxonomies',
        general_taxonomies_manage: 'Manage Taxonomies',
        general_taxonomies_number_iterations: 'Iterations',
        general_taxonomies_number_topics: 'Topics',
        general_taxonomies_number_words: 'Words',
        general_taxonomies_threshold_categories: 'Threshold',
        general_taxonomy: 'Taxonomy',
        general_text: 'Text',
        general_title: 'Title',
        general_transcription: 'Transcription',
        general_type: 'Type',
        general_typescript: 'Typescript',
        general_undo: 'Undo',
        general_update: 'Update',
        general_useOfTag: 'Uses of tag',
        general_usedIn: 'Used in',
        general_uses: 'Uses',
        general_weight: 'Weight',
        general_winner: 'Winner',
        general_words: 'Words',
        general_yes: 'Yes',
        header_about: 'About',
        header_privacy: 'Privacy Policy',
        header_team: 'Editorial Team',
        header_acknowledgements: 'Acknowledgements',
        header_admin: 'Admin',
        header_archive: 'LdoD Archive',
        header_articles: 'Articles',
        header_authorialsources: 'Witnesses',
        header_bibliography: 'Bibliography',
        header_book: 'Book',
        header_communities: 'Communities',
        header_conduct_accept: 'By registering as a user of the LdoD Archive, I accept the code of conduct below',
        header_conduct_error: 'You have to agree with the code of conduct',
        header_conduct: 'Code of Conduct',
        header_contact: 'Contact Us',
        header_copyright: 'Copyright',
        header_documents: 'Documents',
        header_editions: 'Editions',
        header_editorialnotes: 'Editorial Notes',
        header_encoding: 'Text Encoding',
        header_faq: 'Frequently Asked Questions',
        header_funded: 'Funded',
        header_listfragments: 'List of Fragments',
        header_login: 'Login',
        header_logout: 'Logout',
        header_manageeditions: 'Manage Virtual Editions',
        header_objectives: 'Objectives',
        header_search: 'Search',
        header_search_advanced: 'Advanced Search',
        header_search_list: "Fragment's List",
        header_search_similarfragments: 'Similar Framgments',
        header_search_simple: 'Simple Search',
        header_sponsors: 'Sponsors',
        header_title: 'LdoD Archive',
        header_videos: 'Videos',
        header_virtual: 'Virtual',
        header_virtualeditions: 'Virtual Editions',
        info_experts: 'The same witness can be interpreted as more than one text by the editors. Variations in fragment division are based either upon autograph marks (such as horizontal rulers or spaces between text blocks) or upon interpretations about semantic relations between text blocks.',
        info_highlighting: 'Colour gradient increases according to the number of differences across compared editions',
        info_virtualeditions: 'Virtual editions contain fragments selected by their editors from other editions.',
        info_virtualeditions_authenticate: 'To create a new virtual edition or collaborate in an existing virtual edition, it is necessary to authenticate',
        inserted: 'Inserted',
        interpretations: 'Interpretations',
        load: 'Load',
        loading: 'Loading',
        login_error: 'Could not sign in, please check your login/password...',
        login_password: 'Password',
        login_username: 'Username',
        navigation_edition: 'Edition',
        okmessage_title: 'Success:',
        pagenotfound_message: 'LdoD: Page not found...',
        participantsForm_message2: 'Membership Applications',
        recommendation: 'Recommendations',
        recommendation_criteria: 'Sorting Criteria',
        recommendation_fragments: 'Recommended fragments',
        recommendation_iteration: 'Iteration',
        recommendation_iterativeSort: 'Recursive sorting',
        recommendation_recommend: 'Recommend',
        recommendation_recommended: 'Recommended',
        recommendation_recommendedEdition: 'Recommended Edition',
        recommendation_setinitial: 'Set as Initial',
        recommendation_similarFragments: 'Similar Fragments',
        search: 'Search',
        search_addcriteria: 'Add Criterion',
        search_authorial: 'Witnesses',
        search_complete: 'Full search',
        search_date_begin: 'From',
        search_date_dated: 'Dated',
        search_date_end: 'To',
        search_date_unDated: 'Undated',
        search_inclusion_excludedFrom: 'Excluded from',
        search_ldod_with: 'With LdoD mark',
        search_ldod_without: 'Without LdoD mark',
        search_noResults: 'Search produced no results',
        search_option_all: 'All',
        search_option_noAttribution: 'No attribution',
        search_removecriteria: 'Remove Criterion',
        search_rule_matchAll: 'Match all of the following',
        search_rule_matchOne: 'Match any of the following',
        search_source: 'Source types',
        search_text: 'Text',
        search_title: 'Search by title',
        signup: 'Sign up',
        signup_confirmation: 'Your request was submitted for authorization_ In case of approval, an email from the e-address {0} will be sent to your mailbox_ The confirmation should occur within the next 24 hours_',
        signup_errorMessage: 'Your {0} account is not associated with a LdoD Archive account_ Please sign up_',
        signup_message: 'Register as a LdoD Archive user',
        signup_token_authorized: 'Authorized',
        signup_token_authorized_not: 'Not Authorized',
        signup_token_expired: 'The confirmation token has expired',
        signup_token_invalid: 'The confirmation token is invalid_',
        sourcelist_tt_LdoDLabel: 'Explicit marking by Fernando Pessoa stating that the document belongs to the LdoD',
        sourcelist_tt_columns: 'Number of columns by page in the source',
        sourcelist_tt_date: 'Date inscribed or ascribed to the fragment',
        sourcelist_tt_dimensions: 'Describes the dimensions of the witnesses',
        sourcelist_tt_documents: 'List of Witnesses',
        sourcelist_tt_facsimiles: 'Image of original documents',
        sourcelist_tt_sources: 'Facsimiles of original documents by Fernando Pessoa (handwritten, typewritten or printed) ',
        sourcelist_tt_transcription: 'Topographic transcription made by the LdoD Archive team',
        sourcelist_tt_type: 'Describes the type of document as manuscript, typescript or printed',
        tableofcontents_editionof: 'Edition of',
        tableofcontents_fragmentsof: 'Fragments Assigned to',
        tableofcontents_number: 'Number',
        tableofcontents_page: 'Page',
        tableofcontents_title: 'Title',
        tableofcontents_tt_date: 'Date inscribed or ascribed to the fragment',
        tableofcontents_tt_heteronym: 'Heteronym attribution according to the editor',
        tableofcontents_tt_number: 'Fragment number in the edition',
        tableofcontents_tt_page: 'Page where the fragment can be found',
        tableofcontents_tt_reading: 'Start reading the LdoD with recommendations',
        tableofcontents_tt_taxonomy: 'Taxonomy used in the edition',
        tableofcontents_tt_title: 'Title or incipit of the fragment',
        tableofcontents_tt_usesEditions: 'Editions whose transcription and annotation are used\n',
        tableofcontents_tt_volume: 'Volume where the fragment can be found',
        tableofcontents_usesEdition: 'Uses Edition',
        tableofcontents_usesEditions: 'Uses Editions',
        tableofcontents_volume: 'Volume',
        taxonomies_tt_catcut: 'Minimum required percentage for a fragment to be included in a group (relevant for the generation algorithm)',
        taxonomies_tt_combinedcategories: 'Category resulting from the grouping of 2 or more categories',
        taxonomies_tt_create: 'The generated taxonomy aggregates fragments according the parameters',
        taxonomies_tt_extractedcategory: 'New category resulting from the selection of a subset of fragments belonging to the current category',
        taxonomies_tt_fragments: 'Fragments belonging to the category',
        taxonomies_tt_name: 'Name',
        taxonomies_tt_nrofiterations: 'Number of times that the generation algorithm has to execute in order to produce results (relevant for the generation algorithm; it must be above 1500)',
        taxonomies_tt_nroftopics: 'Number of fragment groups to be generated (relevant for the generation algorithm; it must be lower than total number of fragments in the virtual edition)',
        taxonomies_tt_nrofwords: 'Number of words to be used in the category name (does not have impact on the generation algorithm, it only defines the number of words that will be used)',
        taxonomy_annotation: 'Annotate Fragments',
        taxonomy_annotation_all: 'Registered Users',
        taxonomy_annotation_members: 'Edition Editors',
        taxonomy_manage: 'Taxonomy Management',
        taxonomy_manage_members: 'Edition Editors',
        taxonomy_manage_owners: 'Edition Managers',
        taxonomy_vocabulary: 'Vocabulary',
        taxonomy_vocabulary_closed: 'Closed',
        taxonomy_vocabulary_open: 'Open',
        topics_generate_long: 'Add categories using a topic modeling algorithm',
        topics_generate_short: 'Generate Topics',
        topics_topic: 'Topic',
        user_active: 'Active',
        user_agree: 'Agree',
        user_duplicateUsername: 'already in use',
        user_edit: 'Edit user',
        user_email: 'Email',
        user_enabled: 'Enabled',
        user_firstName: 'First name',
        user_lastLogin: 'Last login',
        user_lastName: 'Surname',
        user_list: 'Users',
        user_manage: 'Manage Users',
        virtual_editions_manage: 'Manage Virtual Editions',
        twitter_manage: 'Manage Tweets',
        user_one: 'Virtual edition should have at least one participant',
        user_password: 'Change Password',
        user_password_current: 'Current password',
        user_password_new: 'New password',
        user_password_retype: 'Retype password',
        user_role: 'Role',
        user_role_admin: 'Admin',
        user_role_user: 'User',
        user_roles: 'Roles',
        user_unknown: 'Unknown user',
        user_user: 'User',
        validateCreateCategoryForm_value: 'The category name is missing',
        validateGenerateTopics_iterations_positive: 'The number of iterations should be positive',
        validateGenerateTopics_iterations_value: 'Number of iterations is missing',
        validateGenerateTopics_threshold_range: 'Treshold value should be between 0 and 100',
        validateGenerateTopics_threshold_value: 'The threshold value is missing',
        validateGenerateTopics_topics_number: 'Number of topics to be generated is missing',
        validateGenerateTopics_topics_positive: 'The number of topics should be greater than one and less than 100',
        validateGenerateTopics_words_number: 'The number of words to be part of the category name is missing',
        validateGenerateTopics_words_positive: 'The number of words should be greater than one and less than 10',
        virtual: 'Virtual',
        virtual_editions: 'Virtual Editions',
        virtualcompare_comment: 'Comment',
        virtualcompare_quote: 'Quote',
        virtualcompare_title: "Comparison of virtual editions' annotations",
        virtualcompare_user: 'User',
        virtualedition: 'Virtual Edition',
        virtualedition_acronym_alphanumeric: 'Acronym field should be alphanumeric',
        virtualedition_acronym_blanks: 'Acronym field has spaces...',
        virtualedition_acronym_duplicate: 'There is already a virtual edition with this acronym...',
        virtualedition_acronym_empty: 'Acronym field requires a value...',
        virtualedition_acronym_length: 'Acronym length greater than 10',
        virtualedition_synopsis: 'Synopsys',
        virtualedition_title_empty: 'Title field requires a value...',
        virtualedition_tt_access: 'Private \u2013 The edition can only be seen by its editors; Public \u2013 The edition is publicly visible',
        virtualedition_tt_acronym: 'Unique acronym that identifies an edition',
        virtualedition_tt_addFragment: 'Add fragments',
        virtualedition_tt_create: 'Creates an edition that can be collaboratively constructed by its editors',
        virtualedition_tt_cut: 'Cut',
        virtualedition_tt_date: 'Date of the creation of the edition',
        virtualedition_tt_delete: 'Remove the edition',
        virtualedition_tt_deleteFragment: 'Delete fragments',
        virtualedition_tt_edit: 'Change edition properties',
        virtualedition_tt_join: 'Join the edition (requires authentication)',
        virtualedition_tt_manage: 'Access the management of the edition (requires authentication)',
        virtualedition_tt_manage_annotations: 'Who can annotate the fragments',
        virtualedition_tt_manage_categories: 'Who can manage the categories: create, delete, update name, merge two categories and split one category into two',
        virtualedition_tt_manage_vocabulary: 'Open vocabulary: new categories can be created when annotating. Closed vocabulary: during annotations only a predefined set of categories can be used.',
        virtualedition_tt_movebottom: 'Move to bottom',
        virtualedition_tt_movedown: 'Move down',
        virtualedition_tt_moveposition: 'Move to position',
        virtualedition_tt_movetop: 'Move to top',
        virtualedition_tt_moveup: 'Move up',
        virtualedition_tt_participants: 'Add or remove editors to an edition',
        virtualedition_tt_paste: 'Paste',
        virtualedition_tt_save: 'Save',
        virtualedition_tt_select: 'Edition becomes accessible at level of the Editions top menu',
        virtualedition_tt_title: 'Title of the edition',
        virtualedition_tt_use: 'The virtual edition uses all the transcriptions from the selected edition',
        virtualeditionlist_acronym: 'Acronym',
        virtualeditionlist_createtitle: 'Create a new Virtual Edition',
        virtualeditionlist_editvirtual: 'Edit Virtual Edition',
        virtualeditionlist_name: 'Title',
        virtualeditionlist_title: 'Virtual Editions',
        general_reading_sequences: 'Reading Sequences',
        general_reading_visual: 'Visual Book',
        general_editor_prado: 'Jacinto do Prado Coelho',
        general_editor_zenith: 'Richard Zenith',
        general_editor_cunha: 'Teresa Sobral Cunha',
        general_editor_pizarro: 'Jerónimo Pizarro',
        header_tutorials: 'Tutorials and Workshops',
        virtual_anot: 'LDOD-JPC-ANOT',
        virtual_class: 'LDOD-JOGO-CLASS',
        virtual_mallet: 'LDOD-MALLET',
        virtual_twitter: 'LDOD-TWITTER',
    },
    es: {
        Different_changePasswordForm: 'La contraseña no coincide',
        DoNotMatch_changePasswordForm: 'La contraseña introducida es incorrecta',
        Email: 'No es una dirección de correo bien formada',
        Exist_editUserForm: 'Nombre de usuario ya existe',
        NotEmpty: 'Campo obligatorio',
        size: 'Debe contener al menos 6 caracteres',
        alphabetic_error: 'Debe ser alfabético',
        authorial: 'Testimonio',
        authorial_source: 'Testimonios',
        category_add: 'Añadir Categoría',
        corpus_load: 'Cargar Corpus',
        corpus_load_title: 'Cargar Fichero TEI con Corpus',
        criteira_mediasource_facebook: 'Facebook',
        criteira_mediasource_nomediasource: 'Ninguna red social',
        criteira_mediasource_twitter: 'Twitter',
        criteira_timewindow_begindate: 'Fecha de inicio de las citas',
        criteira_timewindow_enddate: 'Fecha de fin de las citas',
        criteria_frequency: 'Frecuencia mínima',
        criteria_frequency_manage: 'Elija un nï¿½mero mínimo de veces que los fragmentos hayan sido citados',
        criteria_geolocation: 'Localización Geográfica',
        criteria_geolocation_Angola: 'Angola',
        criteria_geolocation_Brazil: 'Brasil',
        criteria_geolocation_Japan: 'Japón',
        criteria_geolocation_Lebanon: 'Líbano',
        criteria_geolocation_Mozambique: 'Moçambique',
        criteria_geolocation_Portugal: 'Portugal',
        criteria_geolocation_Spain: 'España',
        criteria_geolocation_UnitedKingdom: 'Inglaterra',
        criteria_geolocation_UnitedStates: 'Estados Unidos',
        criteria_geolocation_everycountry: 'Todos los paises',
        criteria_geolocation_manage: 'Elegir el país del que desea recoger las citas',
        criteria_geolocation_nocountry: 'Ningún país',
        criteria_mediasource: 'Red Social',
        criteria_mediasource_manage: 'Elegir la red social de la que desea recoger citas',
        criteria_timewindow: 'Ventana temporal',
        criteria_timewindow_begindate_manage: 'Seleccione la fecha de inicio de la recogida de citas',
        criteria_timewindow_enddate_manage: 'Seleccione la fecha de fin de la recogida de citas',
        deletefragment_header: 'Eliminar Fragmento',
        deletefragment_title: 'Elija el fragmento a eliminar',
        edition_experts: 'Ediciones de los Especialistas',
        edituserform_newusername_pattern: 'Debe ser alfanumérico',
        exceptions_error: 'Error:',
        exceptions_title: 'Excepciones del LdoD',
        fragment: 'Fragmento',
        fragment_alignspace: 'Alinear Espacios',
        fragment_base: 'Testimonio Base:',
        fragment_codified: 'Fragmentos Codificados',
        fragment_compare: 'Testimonio a Comparar:',
        fragment_delete: 'Eliminar Fragmento',
        fragment_highlightdifferences: 'Realzar Diferencias',
        fragment_highlightinserted: 'Realzar Acrecentados',
        fragment_highlightsubstitutions: 'Realzar Sustituciones',
        fragment_linebyline: 'Línea a línea',
        fragment_load: 'Cargar Fragmento',
        fragment_load_title: 'Cargar Fichero TEI con Fragmento',
        fragment_load_titleAll: 'Cargar Varios Ficheros TEI con Varios Fragmentos',
        fragment_showdeleted: 'Mostrar Eliminados',
        fragment_showfacs: 'Facsimile',
        fragment_shownotes: 'Mostrar Notas',
        fragment_tt_additions: 'Realza texto añadido por Fernando Pessoa',
        fragment_tt_deletions: 'Muestra texto eliminado por Fernando Pessoa',
        fragment_tt_highlights: 'Realza variaciones entre las transcripciones en comparación',
        fragment_tt_image: 'Imagen de los documentos originales',
        fragment_tt_information: 'Muestra la información sobre las fuentes de las transcripciones',
        fragment_tt_substitution: 'Realza texto eliminado y substituido por Fernando Pessoa',
        fragment_variationstable: 'Tabla de Variaciones',
        fragment_visualization: 'Atributos de Visualización:',
        fragmentlist_showdetails: 'Mostrar Detalles',
        fragmentlist_title: 'Fragmentos del LdoD',
        fragments: 'Fragmentos',
        fragments_load: 'Cargar Fragmento',
        game_classification_description_empty: 'Falta la descripción',
        game_classification_inter_null: 'Seleccione una interpretación',
        general_LdoDLabel: 'Marca LdoD',
        general_access: 'Acceso',
        general_access_denied: 'Acceso denegado',
        general_add: 'Añadir',
        general_annotations: 'Anotaciones',
        general_associate: 'Asociar',
        general_author: 'Autor',
        general_back: 'Retorno',
        general_cancel: 'Cancelar',
        general_categories: 'Categorías',
        general_category: 'Categoría',
        general_category_exists: 'Ya existe una categoría',
        general_category_extracted: 'Categoría Extraída',
        general_category_merged: 'Categorías Fusionadas',
        general_citations: 'Citas',
        general_citations_twitter: 'Citas en Twitter',
        general_classificationGame: 'Juego de clasificación',
        general_classificationGame_visitWebsite: 'Haga clic aquÃ­ para ir al Juego de ClasificaciÃ³n',
        general_close: 'Cerrar',
        general_columns: 'Columnas',
        general_contributionsOf: 'Contribuciones de',
        general_country: 'País',
        general_create: 'Crear',
        general_date: 'Fecha',
        general_delete: 'Eliminar',
        general_deleteconfirmation: '¿Estás seguro?',
        general_deprecated: 'Desaprobado',
        general_description: 'Descripción',
        general_deselect: 'Deseleccionar',
        general_dimensions: 'Dimensiones',
        general_edit: 'Editar',
        general_edition: 'Edición',
        general_editor: 'Editor',
        general_editors: 'Editores',
        general_export: 'Exportar',
        general_extract: 'Extraer',
        general_facsimiles: 'Facsimiles',
        general_format: 'Formato',
        general_generate: 'Generar',
        general_heteronym: 'Heterónimo',
        general_heteronym_notassigned: 'No assignado',
        general_identification: 'Identificación',
        general_information: 'Informácion',
        general_join: 'Participar',
        general_journal: 'Revista',
        general_language: 'Idioma',
        general_leaf: 'Hoja',
        general_loading: 'Buscando...',
        general_manage: 'Gerir',
        general_manager: 'Gestor',
        general_manuscript: 'Manuscrito',
        general_material: 'Material',
        general_merge: 'Fundir',
        general_name: 'Nombre',
        general_no: 'No',
        general_note: 'Nota',
        general_number_of: 'Número de',
        general_operation: 'Operación',
        general_paper: 'Papel',
        general_participant: 'PartÃ­cipe',
        general_percentage: 'Porcentaje',
        general_players: 'Jugadores',
        general_points: 'Puntos',
        general_position: 'Posición',
        general_printed: 'Impreso',
        general_private: 'Privado',
        general_public: 'Público',
        general_public_pages: 'Páginas Públicas',
        general_published: 'Publicado',
        general_published_place: 'Lugar de la Publicación',
        general_reading: 'Lectura',
        general_reading_start: 'Empezar',
        general_recommendation: 'Recomendación',
        general_recommendation_config: 'Configuración de las Recomendaciones',
        general_recommendations: 'Recomendaciones',
        general_remove: 'Retirar',
        general_removeAll: 'Retirar Todos',
        general_reset: 'Reiniciar',
        general_reset_list: 'Reiniciar la lista de recomendaciones anteriores',
        general_responsible: 'Responsable',
        general_save: 'Guardar',
        general_searching: 'Buscando...',
        general_searching_for: 'Buscar por...',
        general_sections: 'Secciones',
        general_select: 'Seleccionar',
        general_selected: 'Seleccionado',
        general_signin: 'Ingresar',
        general_sort_automatic: 'Ordenación Asistida',
        general_sort_manual: 'Ordenación Manual',
        general_sources: 'Fuentes',
        general_structure: 'Estructura',
        general_submit: 'Enviar',
        general_tags: 'Etiquetas',
        general_taxonomies: 'Taxonomías',
        general_taxonomies_manage: 'Gerir Taxonomías',
        general_taxonomies_number_iterations: 'Iteraciones',
        general_taxonomies_number_topics: 'Temas',
        general_taxonomies_number_words: 'Palabras',
        general_taxonomies_threshold_categories: 'Límite',
        general_taxonomy: 'Taxonomía',
        general_text: 'Texto',
        general_title: 'Título',
        general_transcription: 'Transcripción',
        general_type: 'Tipo',
        general_typescript: 'Mecanografiado',
        general_undo: 'Deshacer',
        general_update: 'Actualizar',
        general_useOfTag: 'Usos de la etiqueta',
        general_usedIn: 'Usado en',
        general_uses: 'Usa',
        general_weight: 'Peso',
        general_winner: 'Ganador',
        general_words: 'Palabras',
        general_yes: 'Si',
        header_about: 'Acerca',
        header_privacy: 'Política de Privacidad',
        header_team: 'Equipo Editorial',
        header_acknowledgements: 'Agradecimientos',
        header_admin: 'Admin',
        header_archive: 'Archivo LdoD',
        header_articles: 'Artículos',
        header_authorialsources: 'Testimonios',
        header_bibliography: 'Bibliografía',
        header_communities: 'Comunidades',
        header_conduct_accept: 'Al registrarme como usuario del Archivo LdoD, acepto el código de conducta abajo',
        header_conduct_error: 'Debe aceptar el código de conducta',
        header_conduct: 'Código de Conducta',
        header_contact: 'Contacto',
        header_copyright: 'Copyright',
        header_documents: 'Documentos',
        header_editions: 'Ediciones',
        header_editorialnotes: 'Notas Editoriales',
        header_encoding: 'Codificación de Texto',
        header_faq: 'Preguntas Frecuentes',
        header_funded: 'Financiado',
        header_listfragments: 'Lista de Fragmentos',
        header_login: 'Iniciar Sesión',
        header_logout: 'Cerrar',
        header_manageeditions: 'Gestionar Ediciones Virtuales',
        header_objectives: 'Objectivos',
        header_search: 'Búsqueda',
        header_search_advanced: 'Búsqueda Avanzada',
        header_search_list: 'Lista de Fragmentos',
        header_search_similarfragments: 'Fragmentos Similares',
        header_search_simple: 'Búsqueda Sencilla',
        header_sponsors: 'Apoyos',
        header_title: 'Archivo LdoD',
        header_videos: 'Vídeos',
        header_virtual: 'Virtual',
        header_virtualeditions: 'Ediciones Virtuales',
        info_experts: 'El mismo testimonio puede ser interpretado como más de un texto según los editores. Estas variaciones en la división de los fragmentos se basan bien en marcaciones autógrafas (trazos horizontales o espacios entre bloques del texto), bien en interpretaciones sobre la proximidad semántica de los bloques textuales.',
        info_highlighting: 'El gradiente de color aumenta según el número de diferencias entre las transcripciones en comparación',
        info_virtualeditions: 'Las ediciones virtuales contienen fragmentos escogidos por sus editores a partir de otras ediciones.',
        info_virtualeditions_authenticate: 'Para crear una edición virtual o colaborar en una edición virtual existente, debe autenticarse',
        inserted: 'Insertado',
        interpretations: 'Interpretaciones',
        load: 'Cargar',
        loading: 'Cargando',
        login_error: 'No se pudo iniciar la sesión, compruebe su nombre de usuario / contraseña, por favor...',
        login_password: 'Contraseña',
        login_username: 'Nombre de usuario',
        navigation_edition: 'Edición',
        okmessage_title: 'Éxito:',
        pagenotfound_message: 'LdoD: Esta página no existe',
        participantsForm_message2: 'Solicitud de Adhesión',

        recommendation: 'Recomendaciones',
        recommendation_criteria: 'Criterios de Ordenación',
        recommendation_fragments: 'Fragmentos recomendadas',
        recommendation_iteration: 'Iteración',
        recommendation_iterativeSort: 'Ordenamiento recursivo',
        recommendation_recommend: 'Recomendar',
        recommendation_recommended: 'Recomendada',
        recommendation_recommendedEdition: 'Edición Recomendada',
        recommendation_setinitial: 'Definir como Inicial',
        recommendation_similarFragments: 'Fragmentos Similares',
        search: 'Buscar',
        search_addcriteria: 'Añadir Criterio',
        search_authorial: 'Testimonios',
        search_complete: 'Búsqueda completa',
        search_date_begin: 'Desde',
        search_date_dated: 'Fechado',
        search_date_end: 'Hasta',
        search_date_unDated: 'Sin fecha',
        search_inclusion_excludedFrom: 'Excluidos de',
        search_inclusion_includedIn: 'Incluidos en',
        search_keyword: 'Palabras clave',
        search_ldod_with: 'Con marca LdoD',
        search_ldod_without: 'Sin marca LdoD',
        search_noResults: 'La búsqueda no produjo resultados',
        search_option_all: 'Todas',
        search_option_noAttribution: 'Ninguna atribución',
        search_removecriteria: 'Eliminar Criterio',
        search_rule_matchAll: 'Coincidir todos de los siguientes criterios',
        search_rule_matchOne: 'Coincidir con pelo menos uno de los siguientes criterios',
        search_source: 'Tipos de fuente',
        search_text: 'Texto',
        search_title: 'Búsqueda por título',
        signup: 'Regístrar',
        signup_confirmation: 'Su solicitud fue enviada para autorización. En caso de aprobación, un correo electrónico de la dirección electrónica {0} será enviado a su buzón de correo. La confirmación debe ocurrir dentro de las próximas 24 horas.',
        signup_errorMessage: 'Su cuenta {0} no está asociada con una cuenta de Archivo LdoD. Por favor regístrese.',
        signup_message: 'Registrarse como usuario del Archivo LdoD',
        signup_token_authorized: 'Autorizado',
        signup_token_authorized_not: 'No autorizado',
        signup_token_expired: 'El token de confirmación ha expirado',
        signup_token_invalid: 'El token de confirmación no es válido.',
        sourcelist_tt_LdoDLabel: 'Marcación explícita hecha por Fernando Pessoa para señalar que el documento pertenece al LdoD',
        sourcelist_tt_columns: 'Número de columnas por página de la fuente',
        sourcelist_tt_date: 'Fecha inscrita o atribuida al fragmento',
        sourcelist_tt_dimensions: 'Describe las dimensiones de los testimonios',
        sourcelist_tt_documents: 'Lista de Testimonios',
        sourcelist_tt_facsimiles: 'Imagen de los documentos originales',
        sourcelist_tt_sources: 'Facsímiles de los documentos originales de Fernando Pessoa (manuscritos, mecanografiados o impresos)',
        sourcelist_tt_transcription: 'Transcripción topográfica realizada por el equipo del Archivo LdoD',
        sourcelist_tt_type: 'Describe el tipo de documento como manuscrito, mecanografiado o impreso',
        tableofcontents_editionof: 'Edición de',
        tableofcontents_fragmentsof: 'Fragmentos Atribuidos a',
        tableofcontents_number: 'Número',
        tableofcontents_page: 'Página',
        tableofcontents_title: 'Título',
        tableofcontents_tt_date: 'Fecha inscrita o atribuida al fragmento',
        tableofcontents_tt_heteronym: 'Atribución de heterónimo según el editor',
        tableofcontents_tt_number: 'Número del fragmento en la edición',
        tableofcontents_tt_page: 'Página en la que el fragmento se encuentra',
        tableofcontents_tt_reading: 'Empezar a leer el LdoD con recomendaciones',
        tableofcontents_tt_taxonomy: 'Taxonomía utilizada en la edición',
        tableofcontents_tt_title: 'Título o incipit del fragmento',
        tableofcontents_tt_usesEditions: 'Ediciónes cuya transcripción y anotación se utilizan',
        tableofcontents_tt_volume: 'Volumen en que el fragmento se encuentra',
        tableofcontents_usesEdition: 'Utiliza Edicion',
        tableofcontents_usesEditions: 'Utiliza Ediciones',
        tableofcontents_volume: 'Volumen',
        taxonomies_tt_catcut: 'Porcentaje mínimo necesario para que un fragmento sea incluido en un grupo (tiene impacto en el algoritmo de generacíon)',
        taxonomies_tt_combinedcategories: 'Categoría resultante de la agrupación de dos o más categorías',
        taxonomies_tt_create: 'La taxonomia generada agrupa los fragmentos de acuerdo con los parámetros',
        taxonomies_tt_extractedcategory: 'Nueva categoría resultante de la selección de un subconjunto de fragmentos de la categoría actual',
        taxonomies_tt_fragments: 'Fragmentos que pertenecen a la categoría',
        taxonomies_tt_name: 'Nombre',
        taxonomies_tt_nrofiterations: 'Número de veces que el algoritmo de generación ejecuta para producir resultados (tiene impacto en el algoritmo de generacíon, debe ser superior a 1500)',
        taxonomies_tt_nroftopics: 'Número de grupos de fragmentos a generar (tiene impacto en el algoritmo de generacíon; debe ser menor que el número total de fragmentos en la edición virtual)',
        taxonomies_tt_nrofwords: 'Número de palabras utilizadas en el nombre de la categoría (no tiene impacto en el algoritmo de generacíon, sólo sirve para definir el número de palabras a utilizar)',
        taxonomy_annotation: 'Anotar Fragmentos',
        taxonomy_annotation_all: 'Usuarios Registrados',
        taxonomy_annotation_members: 'Editores de la Edición',
        taxonomy_manage: 'Gestión de Taxonomía',
        taxonomy_manage_members: 'Editores de la Edición',
        taxonomy_manage_owners: 'Gerentes de Edición',
        taxonomy_vocabulary: 'Vocabulario',
        taxonomy_vocabulary_closed: 'Cerrado',
        taxonomy_vocabulary_open: 'Abierto',
        topics_generate_long: 'Añadir categorías aplicando un algoritmo de generación de tópicos',
        topics_generate_short: 'Generar Tópicos',
        topics_topic: 'Tópico',
        user_active: 'Activo',
        user_agree: 'Accepto',
        user_duplicateUsername: 'ya está en uso',
        user_edit: 'Editar usuario',
        user_email: 'Correo electrónico',
        user_enabled: 'Confirmado',
        user_firstName: 'Primer nombre',
        user_lastLogin: 'Último acceso',
        user_lastName: 'Apellido',
        user_list: 'Usuarios',
        user_manage: 'Gestión de Usuarios',
        virtual_editions_manage: 'Manage Virtual Editions',
        twitter_manage: 'Manage Tweets',
        user_one: 'Edición virtual debe tener al menos un participante',
        user_password: 'Cambiar la Contraseña',
        user_password_current: 'Contraseña actual',
        user_password_new: 'Nueva contraseña',
        user_password_retype: 'Vuelva a escribir la contraseña',
        user_role: 'Rol',
        user_role_admin: 'Administrador',
        user_role_user: 'Usuario',
        user_roles: 'Roles',
        user_unknown: 'Usuario desconocido',
        user_user: 'Usuario',
        validateCreateCategoryForm_value: 'Falta el nombre de la categoría',
        validateGenerateTopics_iterations_positive: 'El número positivo de iteraciones debe ser positivo',
        validateGenerateTopics_iterations_value: 'Faltar el número de iteraciones',
        validateGenerateTopics_threshold_range: 'Valor límite debe estar entre 0 y 100',
        validateGenerateTopics_threshold_value: 'Falta el valor límite',
        validateGenerateTopics_topics_number: 'Falta el número de tópicos a generar',
        validateGenerateTopics_topics_positive: 'El número de tópicos debe ser positivo y menor que 100',
        validateGenerateTopics_words_number: 'Falta el número de palavras a incluir en el nombre de la categoría',
        validateGenerateTopics_words_positive: 'El um número de palabras debe ser positivo y menor que 10',
        virtual: 'Virtual',
        virtual_editions: 'Ediciónes Virtuales',
        virtualcompare_comment: 'Comentario',
        virtualcompare_quote: 'Cita',
        virtualcompare_title: 'Comparación de anotaciones de ediciones virtuales',
        virtualcompare_user: 'Usuario',
        virtualedition: 'Edición Virtual',
        virtualedition_acronym_alphanumeric: 'Campo siglas debe ser alfanumérico',
        virtualedition_acronym_blanks: 'Campo siglas tiene espaciós ...',
        virtualedition_acronym_duplicate: 'Ya existe una edición virtual con esta sigla ...',
        virtualedition_acronym_empty: 'Campo sigla necesita un valor ...',
        virtualedition_acronym_length: 'Sigla con más de 10 caracteres',
        virtualedition_synopsis: 'Sinopsis',
        virtualedition_title_empty: 'Campo título necesita un valor ...',
        virtualedition_tt_access: 'Privado – La edición sólo puede ser visualizada por sus editores; Público – La edición es públicamente visible',
        virtualedition_tt_acronym: 'Sigla única que identifica la edición',
        virtualedition_tt_addFragment: 'Añadir fragmentos',
        virtualedition_tt_create: 'Crear una edición que puede ser colaborativamente construida por sus editores.',
        virtualedition_tt_cut: 'Cortar',
        virtualedition_tt_date: 'Fecha de creación de la edición',
        virtualedition_tt_delete: 'Eliminar la edición',
        virtualedition_tt_deleteFragment: 'Eliminar fragmentos',
        virtualedition_tt_edit: 'Cambiar las propiedades de la edición',
        virtualedition_tt_join: 'Participar en la edición (requiere autenticación)',
        virtualedition_tt_manage: 'Acceder a la gestión de la edición (requiere autenticación)',
        virtualedition_tt_manage_annotations: 'Quién puede anotar los fragmentos',
        virtualedition_tt_manage_categories: 'Quién puede administrar las categorías: crear, eliminar, actualizar nombre, combinar dos categorías y dividir una categoría en dos',
        virtualedition_tt_manage_vocabulary: 'Vocabulario abierto: se pueden crear nuevas categorías al anotar. Vocabulario cerrado: durante la anotación sólo se puede utilizar un conjunto predefinido de categorías.',
        virtualedition_tt_movebottom: 'Mover hacia la parte inferior',
        virtualedition_tt_movedown: 'Mover una posición hacia abajo',
        virtualedition_tt_moveposition: 'Mover hacia la posición',
        virtualedition_tt_movetop: 'Mover hacia la parte superior',
        virtualedition_tt_moveup: 'Mover una posición hacia arriba',
        virtualedition_tt_participants: 'Añadir o remover editores de la edición ',
        virtualedition_tt_paste: 'Pegar',
        virtualedition_tt_save: 'Guardar',
        virtualedition_tt_select: 'La edición queda accesible a través del menu superior Ediciones',
        virtualedition_tt_title: 'Título de la edición',
        virtualedition_tt_use: 'La edición virtual usa todas las transcripciones de la edición escogida',
        virtualeditionlist_acronym: 'Sigla',
        virtualeditionlist_createtitle: 'Crear una nueva Edición Virtual',
        virtualeditionlist_editvirtual: 'Editar Edición Virtual',
        virtualeditionlist_name: 'Título',
        virtualeditionlist_title: 'Ediciones Virtuales',
        general_reading_sequences: 'Secuencias de lectura',
        general_reading_visual: 'Libro Visual',
        general_editor_prado: 'Jacinto do Prado Coelho',
        general_editor_zenith: 'Richard Zenith',
        general_editor_cunha: 'Teresa Sobral Cunha',
        general_editor_pizarro: 'Jerónimo Pizarro',
        header_tutorials: 'Tutoriales y Talleres',
        virtual_anot: 'LDOD-JPC-ANOT',
        virtual_class: 'LDOD-JOGO-CLASS',
        virtual_mallet: 'LDOD-MALLET',
        virtual_twitter: 'LDOD-TWITTER',
        header_book: 'Libro',
    },
};