export const ADD_FRAGMENT = "ADD_FRAGMENT";
export const SET_FRAGMENT_INDEX = "SET_FRAGMENT_INDEX";
export const SET_CURRENT_VISUALIZATION = "SET_CURRENT_VISUALIZATION";
export const ADD_HISTORY_ENTRY = "ADD_HISTORY_ENTRY";
export const SET_ALL_FRAGMENTS_LOADED = "SET_ALL_FRAGMENTS_LOADED";
export const SET_OUT_OF_LANDING_PAGE = "SET_OUT_OF_LANDING_PAGE";
