export const ADD_FRAGMENT = "ADD_FRAGMENT";
export const SET_FRAGMENT_INDEX = "SET_FRAGMENT_INDEX";
export const SET_CURRENT_VISUALIZATION = "SET_CURRENT_VISUALIZATION";
export const ADD_HISTORY_ENTRY = "ADD_HISTORY_ENTRY";
export const SET_ALL_FRAGMENTS_LOADED = "SET_ALL_FRAGMENTS_LOADED";
export const SET_OUT_OF_LANDING_PAGE = "SET_OUT_OF_LANDING_PAGE";
export const SET_HISTORY_ENTRY_COUNTER = "SET_HISTORY_ENTRY_COUNTER";
export const SET_RECOMMENDATION_ARRAY = "SET_RECOMMENDATION_ARRAY";
export const SET_RECOMMENDATION_INDEX = "SET_RECOMMENDATION_INDEX";
export const SET_FRAGMENTS_HASHMAP = "SET_FRAGMENTS_HASHMAP";
export const SET_CURRENT_FRAGMENT_MODE = "SET_CURRENT_FRAGMENT_MODE";
export const SET_RECOMMENDATION_LOADED = "SET_RECOMMENDATION_LOADED";

export const SET_VISUALIZATION_TECHNIQUE = "SET_VISUALIZATION_TECHNIQUE";
export const SET_SEMANTIC_CRITERIA = "SET_SEMANTIC_CRITERIA";
export const SET_SEMANTIC_CRITERIA_DATA = "SET_SEMANTIC_CRITERIA_DATA";
export const SET_SEMANTIC_CRITERIA_DATA_LOADED = "SET_SEMANTIC_CRITERIA_DATA_LOADED";

export const SET_POTENTIAL_VISUALIZATION_TECHNIQUE = "SET_POTENTIAL_VISUALIZATION_TECHNIQUE";
export const SET_POTENTIAL_SEMANTIC_CRITERIA = "SET_POTENTIAL_SEMANTIC_CRITERIA";
export const SET_POTENTIAL_SEMANTIC_CRITERIA_DATA = "SET_POTENTIAL_SEMANTIC_CRITERIA_DATA";

export const SET_FRAGMENTS_SORTED_BY_DATE = "SET_FRAGMENTS_SORTED_BY_DATE";

export const SET_DISPLAY_TEXT_SKIMMING = "SET_DISPLAY_TEXT_SKIMMING";

export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_CURRENT_CATEGORY = "SET_CURRENT_CATEGORY";
export const SET_POTENTIAL_CATEGORY = "SET_POTENTIAL_CATEGORY";

export const SET_HISTORY = "SET_HISTORY";

export const SET_DATES_EXIST = "SET_DATES_EXIST"

export const SET_GOLDEN_ARRAY = "SET_GOLDEN_ARRAY"
