/** @format */

export default {
	sessionListHeaders: ['username', 'firstName', 'lastName', 'lastRequest', 'sessionId'],
	usersListHeaders: [
		'username',
		'firstName',
		'lastName',
		'enabled',
		'roles',
		'lastLogin',
		'active',
		'actions',
	],
	pt: {
		TRUE: 'Sim',
		FALSE: 'Não',
		users: 'Utilizadores',
		user: 'Utilizador',
		admin: 'Administrador',
		sessions: 'Sessões',
		username: 'Nome de utilizador',
		firstName: 'Primeiro nome',
		lastName: 'Apelido',
		lastRequest: 'Último Pedido',
		sessionId: 'ID da Sessão',
		enabled: 'Confirmado',
		roles: 'Papeis',
		lastLogin: 'Último acesso',
		actions: 'Acções',
		active: 'Ativo',
		tooltipActions: 'Editar/Eliminar',
		editUserHeader: 'Alterar utilizador',
		update: 'Atualizar',
		email: 'Endereço eletrónico',
		newPassword: 'Nova Senha',
		toggleActiveMode: 'Alterar estado ativo',
		changeLdodMode: 'Alterar modo do LdoD',
		deleteUserSessions: 'Eliminar sessões de utilizador',
		userMode: 'Modo utilizador',
		adminMode: 'Modo administrador',
		uploadUsers: 'Carregar Utilizadores',
		exportUsers: 'Exportar Utilizadores',
	},
	en: {
		TRUE: 'Yes',
		FALSE: 'No',
		users: 'Users',
		user: 'User',
		admin: 'Administrator',
		sessions: 'Sessions',
		username: 'Username',
		firstName: 'First Name',
		lastName: 'Last Name',
		lastRequest: 'Last Request',
		sessionId: 'Session ID',
		enabled: 'Enabled',
		roles: 'Roles',
		lastLogin: 'Last login',
		actions: 'Actions',
		active: 'Active',
		tooltipActions: 'Edit/Delete',
		editUserHeader: 'Edit user',
		update: 'Update',
		email: 'Email',
		newPassword: 'New Password',
		toggleActiveMode: 'Toggle active state',
		changeLdodMode: 'Change LdoD mode',
		deleteUserSessions: 'Delete user sessions',
		userMode: 'User mode',
		adminMode: 'Administrator mode',
		uploadUsers: 'Upload Users',
		exportUsers: 'Export Users',
	},
	es: {
		TRUE: 'Sí',
		FALSE: 'No',
		users: 'Usuarios',
		user: 'Usuario',
		admin: 'Administrador',
		sessions: 'Sesiones',
		username: 'Nombre de usuario',
		firstName: 'Primer nombre',
		lastName: 'Apellido',
		lastRequest: 'Última Petición',
		sessionId: 'ID de sesión',
		enabled: 'Confirmado',
		roles: 'Funciones',
		lastLogin: 'Último acceso',
		actions: 'Acciones',
		active: 'Activo',
		tooltipActions: 'Editar/Eliminar',
		editUserHeader: 'Editar usuario',
		update: 'Actualizar',
		email: 'Correo electrónico',
		newPassword: 'Nueva contraseña',
		toggleActiveMode: 'Cambiar estado activo',
		changeLdodMode: 'Cambiar el modo LdoD',
		deleteUserSessions: 'Eliminar sesiones de usuario',
		userMode: 'Modo de usuario',
		adminMode: 'Modo administrador',
		uploadUsers: 'Carregar Usuarios',
		exportUsers: 'Exportar Usuarios',
	},
};
