export default {
  pt: {
    advancedSearch: 'Pesquisa Avançada',
    criteriaAnd: 'De acordo com todos os seguintes critérios',
    criteriaOr: 'De acordo com pelo menos um dos seguintes critérios',
    edition: 'Edição',
    manuscript: 'Manuscrito',
    typescript: 'Datiloscrito',
    published: 'Publicado',
    heteronym: 'Heterónimo',
    taxonomies: 'Taxonomias',
    virtualEditions: 'Edições Virtuais',
    date: 'Data',
    text: 'Texto',
    includedIn: 'Incluídos em',
    excludedFrom: 'Excluídos de',
    all: 'Todas',
    search: 'Pesquisar',
    criteriaType: 'Tipos de Critério',
    editions: 'Edições',
    heteronyms: 'Heterónimos',
    editionInclusion: 'Inclusão na edição',
    dated: 'Datado',
    notDated: 'Não datado',
    beginDate: 'Desde',
    endDate: 'Até',
  },
  en: {
    advancedSearch: 'Advanced Search',
    criteriaAnd: 'Match all of the following',
    criteriaOr: 'Match any of the following',
    edition: 'Edition',
    manuscript: 'Manuscript',
    typescript: 'Typescript',
    published: 'Published',
    heteronym: 'Heteronym',
    taxonomies: 'Taxonomies',
    virtualEditions: 'Virtual Editions',
    date: 'Date',
    text: 'Text',
    includedIn: 'Included in',
    excludedFrom: 'Excluded from',
    all: 'All',
    search: 'Search',
    criteriaType: 'Criteria Types',
    editions: 'Editions',
    heteronyms: 'Heteronyms',
    editionInclusion: 'Edition inclusion',
    dated: 'Dated',
    notDated: 'Not dated',
    beginDate: 'From',
    endDate: 'to',
  },
  es: {
    advancedSearch: 'Búsqueda Avanzada',
    criteriaAnd: 'Coincidir todos de los siguientes criterios',
    criteriaOr: 'Coincidir con pelo menos uno de los siguientes criterios',
    edition: 'Edición',
    manuscript: 'Manuscrito',
    typescript: 'Mecanografiado',
    published: 'Publicado',
    heteronym: 'Heterónimo',
    taxonomies: 'Taxonomías',
    virtualEditions: 'Ediciónes Virtuales',
    date: 'Fecha',
    text: 'Texto',
    includedIn: 'Incluidos em',
    excludedFrom: 'Excluidos de',
    all: 'Todas',
    search: 'Buscar',
    criteriaType: 'Tipos de Critério',
    editions: 'Ediciónes',
    heteronyms: 'Heterónimos',
    editionInclusion: 'Inclusion en edición',
    dated: 'Datado',
    notDated: 'No datado',
    beginDate: 'Desde',
    endDate: 'Até',
  },
};
