export default {
  pt: {
    authorial_source: 'Testemunhos',
    source_info:
      'Fac-símiles dos documentos originais de Fernando Pessoa (manuscritos, datiloscritos ou impressos)',
    sourceTableLabels: {
      title: 'Documentos',
      transcription: 'Transcrição',
      date: 'Data',
      sourceType: 'Tipo',
      hadLdoDLabel: 'Marca LdoD',
      dimensionDtoList: 'Dimensões',
      surfaceString: 'Fac-símiles',
    },
    otherType: {
      PRINTED: 'Impresso',
      MANUSCRIPT: 'Manuscrito()',
    },
    MANUSCRIPT: {
      pen: 'Manuscrito(PEN)',
      pencil: 'Manuscrito(PENCIL)',
      'black-ink': 'Datiloscrito(BLACK_INK)',
      'blue-ink': 'Datiloscrito(BLUE_INK)',
    },
    false: 'Não',
    true: 'Sim',

    fragment_codified: 'Fragmentos Codificados',
    fragmentsTableLabels: {
      title: 'Título',
      JPC: 'Jacinto do Prado Coelho',
      TSC: 'Teresa Sobral Cunha',
      RZ: 'Richard Zenith',
      JP: 'Jerónimo Pizarro',
      sourceInterDtoList_0: 'Testemunho',
      sourceInterDtoList_1: 'Testemunho',
      sourceInterDtoList_2: 'Testemunho',
    },
    title: 'Título',
    heteronym: 'Heterónimo',
    volume: 'Volume',
    number: 'Número',
    startPage: 'Página',
    notes: 'Nota',

    altIdentifier: 'Identificação',
    form: 'Formato',
    material: 'Material',
    columns: 'Colunas',
    hadLdoDLabel: 'Marca LdoD',
    surfaceString: 'Fac-símiles',
    typeNoteDto: (arg) => `<strong>Datiloscrito</strong> <em>(${arg})</em><strong> : </strong>`,
    handNoteDto: (arg) => `<strong>Manuscrito</strong> <em>(${arg})</em><strong> : </strong>`,
    date: 'Data',
    LEAF: 'Folha',
    PAPER: 'Papel',
    journal: 'Revista',
    issue: 'Número',
    pubPlace: 'Local de publicação',
    notAssigned: 'Não atribuído',
  },
  en: {
    authorial_source: 'Testimonios',
    source_info:
      'Facsimiles of original documents by Fernando Pessoa (handwritten, typewritten or printed)',
    sourceTableLabels: {
      title: 'Documents',
      transcription: 'Transcription',
      date: 'Date',
      sourceType: 'Type',
      hadLdoDLabel: 'LdoD Label',
      dimensionDtoList: 'Dimensions',
      surfaceString: 'Facsimiles',
    },
    otherType: {
      PRINTED: 'Printed',
      MANUSCRIPT: 'Manuscript()',
    },
    MANUSCRIPT: {
      pen: 'Manuscript(PEN)',
      pencil: 'Manuscript(PENCIL)',
      'black-ink': 'Typescript(BLACK_INK)',
      'blue-ink': 'Typescript(BLUE_INK)',
    },
    false: 'No',
    true: 'yes',

    fragment_codified: 'Encoded Fragments',
    fragmentsTableLabels: {
      title: 'Title',
      JPC: 'Jacinto do Prado Coelho',
      TSC: 'Teresa Sobral Cunha',
      RZ: 'Richard Zenith',
      JP: 'Jerónimo Pizarro',
      sourceInterDtoList_0: 'Witness',
      sourceInterDtoList_1: 'Witness',
      sourceInterDtoList_2: 'Witness',
    },
    title: 'Title',
    heteronym: 'Heteronym',
    volume: 'Volume',
    number: 'Number',
    startPage: 'Page',
    notes: 'Note',

    altIdentifier: 'Identification',
    form: 'Format',
    material: 'Material',
    columns: 'Columns',
    hadLdoDLabel: 'LdoD Mark',
    surfaceString: 'Facsimiles',
    typeNoteDto: (arg) => `<strong>TypeScript</strong> <em>(${arg})</em><strong> : </strong>`,
    handNoteDto: (arg) => `<strong>Manuscript</strong> <em>(${arg})</em><strong> : </strong>`,
    date: 'Date',
    LEAF: 'Leaf',
    PAPER: 'Paper',
    journal: 'Journal',
    issue: 'Number',
    pubPlace: 'Publication place',
    notAssigned: 'Not assigned',
  },
  es: {
    authorial_source: 'Witnesses',
    source_info:
      'Facsímiles de los documentos originales de Fernando Pessoa (manuscritos, mecanografiados o impresos)',
    sourceTableLabels: {
      title: 'Documentos',
      transcription: 'Transcripción',
      date: 'Fecha',
      sourceType: 'Tipo',
      hadLdoDLabel: 'Marca LdoD',
      dimensionDtoList: 'Dimensiones',
      surfaceString: 'Facsimiles',
    },
    otherType: {
      PRINTED: 'Impreso',
      MANUSCRIPT: 'Manuscrito()',
    },
    MANUSCRIPT: {
      pen: 'Manuscrito(PEN)',
      pencil: 'Manuscrito(PENCIL)',
      'black-ink': 'Mecanografiado(BLACK_INK)',
      'blue-ink': 'Mecanografiado(BLUE_INK)',
    },
    false: 'No',
    true: 'Si',

    fragment_codified: 'Fragmentos Codificados',
    fragmentsTableLabels: {
      title: 'Título',
      JPC: 'Jacinto do Prado Coelho',
      TSC: 'Teresa Sobral Cunha',
      RZ: 'Richard Zenith',
      JP: 'Jerónimo Pizarro',
      sourceInterDtoList_0: 'Testimonio',
      sourceInterDtoList_1: 'Testimonio',
      sourceInterDtoList_2: 'Testimonio',
    },
    title: 'Título',
    heteronym: 'Heterónimo',
    volume: 'Volumen',
    number: 'Número',
    startPage: 'Página',
    notes: 'Nota',

    altIdentifier: 'Identificación',
    heteronym: 'Heterónimo',
    form: 'Formato',
    material: 'Material',
    columns: 'Columnas',
    hadLdoDLabel: 'Marca LdoD',
    surfaceString: 'Facsimiles',
    typeNoteDto: (arg) => `<strong>Mecanografiado</strong> <em>(${arg})</em><strong> : </strong>`,
    handNoteDto: (arg) => `<strong>Manuscrito</strong> <em>(${arg})</em><strong> : </strong>`,
    date: 'Fecha',
    LEAF: 'Hoja',
    PAPER: 'Papel',
    journal: 'Revista',
    issue: 'Número',
    pubPlace: 'Lugar de la Publicación',
    notAssigned: 'No assignado',

  },
};
