/** @format */

export default {
	membersHeaders: ['username', 'firstname', 'lastname', 'email', 'role', 'remove'],
	pendentHeaders: ['username', 'firstname', 'lastname', 'email', 'add'],
	pt: {
		addMember: 'Adicionar membro',
		username: 'Nome de utilizador',
		firstname: 'Primeiro nome',
		lastname: 'Apelido',
		email: 'e-mail',
		role: 'Papel',
		admin: 'Gestor',
		member: 'Editor',
		remove: 'Remover',
		add: 'Adicionar',
		pendingRequests: 'Pedidos de adesão',
		editionMembers: 'Membros da Edição',
		editors: 'Editores',
	},
	en: {
		addMember: 'Add member',
		username: 'Username',
		firstname: 'First name',
		lastname: 'Surname',
		email: 'e-mail',
		role: 'Role',
		admin: 'Manager',
		member: 'Editor',
		remove: 'Remove',
		add: 'Add',
		pendingRequests: 'Membership applications',
		editionMembers: 'Edition Members',
		editors: 'Editors',
	},
	es: {
		addMember: 'Añadir miembro',
		username: 'Nome de utilizador',
		firstname: 'Primeiro nome',
		lastname: 'Apelido',
		email: 'e-mail',
		role: 'Papel',
		admin: 'Gestor',
		member: 'Editor',
		remove: 'Remover',
		add: 'Adicionar',
		pendingRequests: 'Solicitud de Adhesión ',
		editionMembers: 'Miembros de la Edicíon ',
		editors: 'Editores',
	},
};
