import { useEffect } from 'react';

export default ({ posY }) => {
  useEffect(() => window.scrollTo({ top: posY }), []);
  return (
    <div>
      <p>
        The virtual editing and the virtual writing functionalities are provided
        as part of the dynamic layers of the textual collaborative environment
        of the <em>LdoD Archive</em>. They are meant to be used for learning,
        research, and creative practices. Registered users are free to create,
        annotate, and publish their own virtual editions. Once the writing
        functionality becomes available, they are also free to write and publish
        variations based on particular textual references from the{' '}
        <em>Book of Disquiet</em>. All registered users of the{' '}
        <em>LdoD Archive</em> must respect its code of conduct as laid out in
        this document.{' '}
      </p>
      <p>&nbsp;</p>
      <p>
        By registering as a user of the<em> LdoD Archive,</em> you agree to not
        use the platform to:
      </p>
      <ol>
        <li>
          publish any content that is unlawful, harmful, abusive, defamatory,
          obscene, invasive of another's privacy, hateful, or which does not
          respect sexual and gender rights, as well as ethnic and racial rights.
        </li>
        <li>
          publish any content that you do not have a right to make available
          under any law or under specific contractual relationships.
        </li>
        <li>
          publish any content that infringes any patent, trademark, copyright or
          other proprietary rights of any party.
        </li>
        <li>
          publish any advertising, promotional materials, &ldquo;spam,&rdquo; or
          any other form of solicitation.
        </li>
        <li>
          publish any material that contains software viruses or any other
          computer code, files or programs designed to interrupt, destroy or
          limit the functionality of any computer software or hardware or
          telecommunications equipment.
        </li>
        <li>
          interfere with or disrupt the site or servers or networks connected to
          the site, or disobey any requirements, procedures, policies or
          regulations of networks connected to the site.
        </li>
        <li>collect or store personal data about other users.</li>
      </ol>
      <p>&nbsp;</p>
      <p>You also agree that:</p>
      <ol>
        <li>
          any user-generated content (such as a virtual edition, annotations to
          a virtual edition, and virtual writing texts) can be used by others
          within the context of the platform.{' '}
          <em>
            <br />
            Note that the infrastructure is designed so that authorship of all
            virtual editing and virtual writing content is preserved.{' '}
          </em>
          <br />
          All further reproduction, in any media, of content generated by users
          of the <em>LdoD Archive</em> must be attributed.
        </li>
        <li>
          all user-generated content in the <em>LdoD Archive</em> may be shared
          in accordance with the Creative Commons &ldquo;
          <a href="https://creativecommons.org/licenses/by-nc/4.0/">
            Attribution-NonCommercial 4.0 International
          </a>
          &rdquo; license (CC BY-NC 4.0).{' '}
        </li>
        <li>
          the four experts' editions transcribed in the <em>LdoD Archive</em>{' '}
          may only be used in the context of the platform, as defined in the{' '}
          <a href="https://ldod.uc.pt/about/copyright">Copyright Notice</a>.
        </li>
      </ol>
      <p>&nbsp;</p>
      <p>
        The editors of the <em>LdoD Archive</em> reserve the right to:
      </p>
      <ol>
        <li>
          delete any user-generated content that does not comply with this code
          of conduct.
        </li>
        <li>
          prevent registered users who fail to comply with its code of conduct
          from accessing the virtual editing and virtual writing functionalities
          of the platform.
        </li>
      </ol>
      <p>&nbsp;</p>
      <p>[updated 14-08-2017]</p>
    </div>
  );
};
