export default {
  headers: ['title', 'jpc', 'tsc', 'rz', 'jp', 'wit1', 'wit2', 'wit3'],
  pt: {
    encodedFragments: (value) => `Fragmentos Codificados (${value})`,
    title: 'Título',
    colTitle: 'Título: ',
    heteronym: 'Heterónimo: ',
    notAssigned: 'Não atribuído',
    volume: 'Volume: ',
    number: 'Número: ',
    page: 'Página: ',
    date: 'Data: ',
    notes: 'Notas: ',
    nota: 'Nota: ',
    jpc: 'Jacinto do Prado Coelho',
    tsc: 'Teresa Sobral Cunha',
    rz: 'Richard Zenith',
    jp: 'Jerónimo Pizarro',
    wit1: 'Testemunho',
    wit2: 'Testemunho',
    wit3: 'Testemunho',
    identification: 'Identificação: ',
    form: 'Formato: ',
    leaf: 'Folha',
    material: 'Material: ',
    paper: 'Papel',
    columns: 'Colunas: ',
    ldodLabel: 'Marca LdoD: ',
    hadLdoDLabel: (bool) => `${Boolean(bool) ? 'Com' : 'Sem'} marca LdoD`,
    handNote: 'Manuscript',
    typeNote: 'Datiloscrito',
    journal: 'Revista: ',
    pubPlace: 'Lugar de Publicação: ',
    facs: 'Facsimiles: ',
  },
  en: {
    encodedFragments: (value) => `Encoded Fragments (${value})`,
    title: 'Title',
    colTitle: 'Title: ',
    heteronym: 'Heteronym: ',
    notAssigned: 'Not assigned',
    volume: 'Volume: ',
    number: 'Number: ',
    page: 'Page: ',
    date: 'Date: ',
    notes: 'Notes: ',
    nota: 'Note: ',
    jpc: 'Jacinto do Prado Coelho',
    tsc: 'Teresa Sobral Cunha',
    rz: 'Richard Zenith',
    jp: 'Jerónimo Pizarro',
    wit1: 'Witness',
    wit2: 'Witness',
    wit3: 'Witness',
    identification: 'Identification: ',
    form: 'Form: ',
    leaf: 'Leaf',
    material: 'Material: ',
    paper: 'Paper',
    columns: 'Columns: ',
    ldodLabel: 'LdoD Mark: ',
    hadLdoDLabel: (bool) => `${Boolean(bool) ? 'With' : 'Without'} LdoD Mark`,
    handNote: 'Manuscript',
    typeNote: 'Datiloscrito',
    journal: 'Journal: ',
    pubPlace: 'Publication Place: ',
    facs: 'Facsimiles: ',
  },
  es: {
    encodedFragments: (value) => `Fragmentos Codificados (${value})`,
    title: 'Título',
    colTitle: 'Título: ',
    heteronym: 'Heterónimo: ',
    notAssigned: 'No assignado',
    volume: 'Volumen: ',
    number: 'Número: ',
    page: 'Página: ',
    date: 'Data: ',
    notes: 'Notas: ',
    nota: 'Nota: ',
    jpc: 'Jacinto do Prado Coelho',
    tsc: 'Teresa Sobral Cunha',
    rz: 'Richard Zenith',
    jp: 'Jerónimo Pizarro',
    wit1: 'Testimonio',
    wit2: 'Testimonio',
    wit3: 'Testimonio',
    identification: 'Identificación: ',
    form: 'Form: ',
    leaf: 'Hoja',
    material: 'Material: ',
    paper: 'Papel',
    columns: 'Columnas: ',
    ldodLabel: 'Marca LdoD: ',
    hadLdoDLabel: (bool) => `${Boolean(bool) ? 'Com' : 'Sin'} marca LdoD`,
    handNote: 'Manuscrito',
    typeNote: 'Mecanografiado',
    journal: 'Revista: ',
    pubPlace: 'Lugar de la Publicacion: ',
    facs: 'Facsimiles: ',
  },
};
