<h3>1. A norma XML-TEI</h3>
<p>Todas as transcri&ccedil;&otilde;es do <em>Arquivo LdoD</em> est&atilde;o codificadas de acordo com as <a href="http://www.tei-c.org/Guidelines/" target="new"><em>TEI  Guidelines</em></a> (Text Encoding and Interchange). Estas diretrizes designam uma norma de codifica&ccedil;&atilde;o de textos desenvolvida desde 1988 por um cons&oacute;rcio de institui&ccedil;&otilde;es &mdash; o <a href="http://www.tei-c.org/index.xml" target="new">Text Encoding Initiative Consortium</a>. A norma TEI define um conjunto vasto de elementos e atributos na linguagem XML (<a href="https://en.wikipedia.org/wiki/XML" target="new">Extensible Markup Language</a>) que permitem representar carater&iacute;sticas estruturais, concetuais e de visualiza&ccedil;&atilde;o dos textos. Tendo em conta que o formato XML &eacute; uma linguagem de codifica&ccedil;&atilde;o de textos leg&iacute;vel por m&aacute;quinas e por humanos, a norma TEI pode ser descrita como um m&eacute;todo de an&aacute;lise textual para processamento digital. Tira partido da interoperabilidade do formato XML de modo a descrever detalhadamente factos e eventos textuais, atrav&eacute;s de uma sintaxe e sem&acirc;ntica espec&iacute;ficas. Trata-se de uma conven&ccedil;&atilde;o muito poderosa, composta por m&oacute;dulos de codifica&ccedil;&atilde;o para todos os tipos de problemas de representa&ccedil;&atilde;o de estruturas e formas textuais &mdash; desde os prim&oacute;rdios da escrita at&eacute; aos documentos eletr&oacute;nicos atuais. A vers&atilde;o atual das <em>Guidelines for Electronic Text Encoding and Interchange</em> (TEI P5) foi publicada em novembro de 2007 e continua a ser atualizada periodicamente. No momento em que escrevemos, a &uacute;ltima atualiza&ccedil;&atilde;o foi realizada em julho de 2017 (vers&atilde;o 3.2.0).</p>
<p>
<strong>&nbsp;</strong>
</p>
<h3>2. XML-TEI aplicado ao <em>Livro do Desassossego</em></h3>
<p>No caso do <em>Arquivo LdoD</em>, o esquema de codifica&ccedil;&atilde;o desenvolvido implicou a ado&ccedil;&atilde;o do m&eacute;todo de segmenta&ccedil;&atilde;o paralela e a cria&ccedil;&atilde;o de um aparato cr&iacute;tico que trata todas as transcri&ccedil;&otilde;es como varia&ccedil;&otilde;es textuais. Deste modo, &eacute; poss&iacute;vel comparar automaticamente entre si n&atilde;o apenas varia&ccedil;&otilde;es que ocorrem nos testemunhos, mas tamb&eacute;m varia&ccedil;&otilde;es que ocorrem entre as transcri&ccedil;&otilde;es de um testemunho nas diferentes edi&ccedil;&otilde;es. Embora os testemunhos estejam marcados enquanto tal, todas varia&ccedil;&otilde;es (sejam dos originais, sejam das edi&ccedil;&otilde;es) s&atilde;o processadas num mesmo plano. Ao n&iacute;vel da codifica&ccedil;&atilde;o textual, esta decis&atilde;o exprime o princ&iacute;pio te&oacute;rico que subjaz ao <em>Arquivo LdoD</em>: o de mostrar o <em>Livro do Desassossego</em> como projeto autoral e como projeto editorial, tornando poss&iacute;vel observar a transforma&ccedil;&atilde;o do arquivo em edi&ccedil;&otilde;es como um processo din&acirc;mico de gera&ccedil;&atilde;o de varia&ccedil;&otilde;es textuais. </p>

<p>A matriz de codifica&ccedil;&atilde;o XML-TEI permite compreender aquilo que no nosso modelo de virtualiza&ccedil;&atilde;o do <em>Livro do Desassossego</em> descrevemos como a dimens&atilde;o gen&eacute;tica, isto &eacute;, o processo de inscri&ccedil;&atilde;o autoral (escrita e reescrita), e aquilo que design&aacute;mos como a dimens&atilde;o social, isto &eacute;, o processo hist&oacute;rico de reinscri&ccedil;&atilde;o editorial e socializa&ccedil;&atilde;o dos textos (edi&ccedil;&atilde;o e reedi&ccedil;&atilde;o) sob formas editoriais e bibliogr&aacute;ficas espec&iacute;ficas (Portela e Silva, 2014). Por seu turno, a dimens&atilde;o virtual (que &eacute; uma designa&ccedil;&atilde;o da socializa&ccedil;&atilde;o textual do <em>Livro do Desassossego</em> no contexto espec&iacute;fico do <em>Arquivo LdoD</em>) consiste na possibilidade de construir edi&ccedil;&otilde;es virtuais atrav&eacute;s da combina&ccedil;&atilde;o das unidades textuais definidas pelas interpreta&ccedil;&otilde;es autorais e/ou pelas interpreta&ccedil;&otilde;es editoriais (herdando portanto a estrutura XML-TEI dessas unidades). O dinamismo do <em>Arquivo LdoD</em> depende da modulariza&ccedil;&atilde;o produzida pelo seu modelo de dados, mas tamb&eacute;m da versatilidade na compara&ccedil;&atilde;o de transcri&ccedil;&otilde;es garantida pelo seu modelo de codifica&ccedil;&atilde;o textual.</p>

<p>Deste modo, a codifica&ccedil;&atilde;o XML-TEI &eacute; usada simultaneamente no seu potencial representacional &mdash; isto &eacute;, na possibilidade de descri&ccedil;&atilde;o granular de eventos espec&iacute;ficos na superf&iacute;cie de inscri&ccedil;&atilde;o &mdash; e no seu potencial relacional &mdash; isto &eacute;, na possibilidade de leitura instant&acirc;nea de micro e macro-varia&ccedil;&otilde;es a diferentes escalas textuais dentro do corpus. &Eacute; como se todas as transcri&ccedil;&otilde;es de todos os testemunhos e edi&ccedil;&otilde;es fizessem parte de uma &uacute;nica &aacute;rvore, tornando palavras, sinais de pontua&ccedil;&atilde;o, espa&ccedil;os, divis&otilde;es de par&aacute;grafo e divis&otilde;es de texto compar&aacute;veis entre si. A exaustividade e complexidade da codifica&ccedil;&atilde;o das varia&ccedil;&otilde;es permite transitar recursivamente entre tr&ecirc;s escalas: escala do carater, do sinal de pontua&ccedil;&atilde;o e do espa&ccedil;o em branco como unidades m&iacute;nimas de inscri&ccedil;&atilde;o; escala da palavra, da frase, do par&aacute;grafo e do bloco textual como unidades sem&acirc;nticas; e escala da sequ&ecirc;ncia ordenada de textos e do livro enquanto instancia&ccedil;&atilde;o discursiva e material de uma certa ideia da obra. </p>
<p>
<strong>&nbsp;</strong>
</p>
<h3>3. Crit&eacute;rios de codifica&ccedil;&atilde;o</h3>
<p>A equipa do <em>Arquivo LdoD</em> definiu um conjunto de crit&eacute;rios de codifica&ccedil;&atilde;o dos diversos atos de inscri&ccedil;&atilde;o autoral e editorial. Estes crit&eacute;rios foram, por vezes, condicionados pela necessidade de simplificar o processamento e a visualiza&ccedil;&atilde;o das marca&ccedil;&otilde;es. Esta sec&ccedil;&atilde;o explica as principais op&ccedil;&otilde;es tomadas para garantir o equil&iacute;brio entre o rigor textual e sem&acirc;ntico da marca&ccedil;&atilde;o, por um lado, e a legibilidade da visualiza&ccedil;&atilde;o da camada gen&eacute;tica e das compara&ccedil;&otilde;es entre transcri&ccedil;&otilde;es, por outro. Ainda que haja uma componente mim&eacute;tica topogr&aacute;fica nas marca&ccedil;&otilde;es dos testemunhos, ela est&aacute; subordinada ao modelo abstrato de dados cuja fun&ccedil;&atilde;o principal &eacute; garantir a comparabilidade das transcri&ccedil;&otilde;es e ordena&ccedil;&otilde;es dos documentos em cada edi&ccedil;&atilde;o. O objetivo principal n&atilde;o &eacute; imitar os documentos mas model&aacute;-los para efeitos de processamento.</p>

<p><strong>Codifica&ccedil;&atilde;o de espa&ccedil;os e de tra&ccedil;os de divis&atilde;o</strong><br>
Os espa&ccedil;os entre par&aacute;grafos, entre t&iacute;tulo e texto, e entre blocos de texto <em>foram marcados nas suas propor&ccedil;&otilde;es relativas</em>, quer no que diz respeito aos testemunhos, quer no que diz respeito &agrave;s edi&ccedil;&otilde;es. Em vez de uma indenta&ccedil;&atilde;o da primeira linha do par&aacute;grafo, opt&aacute;mos por um espa&ccedil;o de intervalo entre todos os par&aacute;grafos, com o objetivo de melhorar a legibilidade das transcri&ccedil;&otilde;es na leitura em ecr&atilde;. Todos os outros espa&ccedil;os correspondem a espa&ccedil;os que constam dos testemunhos e das edi&ccedil;&otilde;es. Todos os tra&ccedil;os de divis&atilde;o correspondem tamb&eacute;m a tra&ccedil;os que constam dos testemunhos e das edi&ccedil;&otilde;es. Espa&ccedil;os e tra&ccedil;os s&atilde;o elementos importantes na articula&ccedil;&atilde;o das divis&otilde;es internas e externas de cada texto.</p>

<p><strong>Codifica&ccedil;&atilde;o de apagados</strong><br>
A marca&ccedil;&atilde;o de texto cancelado (&lt;del&gt;) foi feita com os valores &ldquo;overstrike&rdquo; e &ldquo;overtyped&rdquo;. Ambos s&atilde;o visualizados atrav&eacute;s de um tra&ccedil;o sobre a palavra apagada.</p>

<p><strong>Codifica&ccedil;&atilde;o de inseridos</strong><br>
A marca&ccedil;&atilde;o dos inseridos (&lt;add&gt;) foi feita com os valores &ldquo;below&rdquo;, &ldquo;above&rdquo;, &ldquo;inline&rdquo;, &ldquo;top&rdquo;, &ldquo;bottom&rdquo; e &ldquo;margin&rdquo;, que definem a posi&ccedil;&atilde;o (&lt;place&gt;) do acrescento relativamente ao segmento de texto a que se aplica ou ao lugar em que surge na p&aacute;gina. O valor &ldquo;margin&rdquo; foi geralmente reservado para texto acrescentado nas margens, mas <em>n&atilde;o para texto que continua nas margens</em>, como frequentemente acontece. Nestes casos a mudan&ccedil;a de lugar do texto na p&aacute;gina &eacute; assinalada apenas por quebra de linha ou por quebra de linha e um espa&ccedil;o.</p>

<p><strong>Codifica&ccedil;&atilde;o de substitui&ccedil;&otilde;es</strong><br>
A codifica&ccedil;&atilde;o de substitui&ccedil;&otilde;es (&lt;subst&gt;) implica a marca&ccedil;&atilde;o de um elemento apagado (&lt;del&gt;) e de um elemento acrescentado (&lt;add&gt;). A visualiza&ccedil;&atilde;o simples da transcri&ccedil;&atilde;o do testemunho pode, por vezes, sugerir que dado elemento &eacute; um acrescento, uma vez que &eacute; antecedido pelo sinal &#8743;, usado para assinalar os inseridos. Nesses casos, a ambiguidade pode ser clarificada se se selecionarem, em simult&acirc;neo, as caixas &ldquo;mostrar apagados&rdquo;, &ldquo;real&ccedil;ar inseridos&rdquo; e &ldquo;real&ccedil;ar substitui&ccedil;&otilde;es&rdquo;. No segundo par&aacute;grafo do testemunho <a href="https://ldod.uc.pt/fragments/fragment/Fr044/inter/Fr044_WIT_MS_Fr044a_51" target="new">BNP/E3 1-50r</a>, por exemplo, a interface mostra um acrescento (dean- teira &#8743;d'ella) quando o testemunho tem apenas o cancelamento da termina&ccedil;&atilde;o plural (dean- teira d&rsquo;ellas). Neste caso, a op&ccedil;&atilde;o de marca&ccedil;&atilde;o implicou explicitar a substitui&ccedil;&atilde;o de &ldquo;d&rsquo;ellas&rdquo; por &ldquo;d&rsquo;ella&rdquo; (como se houvesse, de facto, um acrescento), uma vez que &eacute; essa a implica&ccedil;&atilde;o sem&acirc;ntica do cancelamento. Esta regra de marca&ccedil;&atilde;o <em>foi aplicada a todas as ocorr&ecirc;ncias em que o cancelamento de uma parte da palavra a transforma noutra palavra &mdash; por exemplo, um n&uacute;mero plural num n&uacute;mero singular ou um g&eacute;nero masculino num g&eacute;nero feminino</em>. Embora n&atilde;o haja um acrescento, a altera&ccedil;&atilde;o est&aacute; gr&aacute;fica e semanticamente marcada como se houvesse. A desambigua&ccedil;&atilde;o destas op&ccedil;&otilde;es de codifica&ccedil;&atilde;o implica assinalar, em simult&acirc;neo, as caixas &ldquo;mostrar apagados&rdquo;, &ldquo;real&ccedil;ar inseridos&rdquo; e &ldquo;mostrar substitui&ccedil;&otilde;es&rdquo;, assim como a cola&ccedil;&atilde;o com o fac-s&iacute;mile digital. Esta op&ccedil;&atilde;o foi tomada por motivos de visualiza&ccedil;&atilde;o, uma vez que a marca&ccedil;&atilde;o de letras isoladas resultaria na apresenta&ccedil;&atilde;o de um espa&ccedil;o antes e depois da letra, prejudicando a legibilidade. As op&ccedil;&otilde;es &ldquo;mostrar apagados&rdquo; e &ldquo;real&ccedil;ar inseridos&rdquo; n&atilde;o foram sincronizadas (o que ajudaria a esclarecer aquela ambiguidade) pois a sua aplica&ccedil;&atilde;o separada permite observar mais claramente os v&aacute;rios lugares de revis&atilde;o.</p>

<p><strong>Codifica&ccedil;&atilde;o de variantes</strong><br>
A marca&ccedil;&atilde;o das variantes &eacute; visualizada atrav&eacute;s da presen&ccedil;a simult&acirc;nea das alternativas numa cor diferente da do resto do texto. Al&eacute;m disso, quando se passa sobre cada variante, surge o valor de probabilidade que lhe est&aacute; associado, que resulta da divis&atilde;o da unidade pelo n&uacute;mero de variantes textuais. No primeiro par&aacute;grafo do testemunho <a href="https://ldod.uc.pt/fragments/fragment/Fr044/inter/Fr044_WIT_MS_Fr044a_51" target="new">BNP/E3 1-50r</a>, por exemplo, a interface mostra as variantes &ldquo;rancor&rdquo; e &ldquo;torpor&rdquo; com uma probabilidade de serem exclu&iacute;das de 0.5 cada uma (&ldquo;excl 0.5&rdquo;). Quando h&aacute; tr&ecirc;s variantes, a distribui&ccedil;&atilde;o &eacute; geralmente uma combina&ccedil;&atilde;o de 0.3, 0.3 e 0.4. No entanto, h&aacute; casos em que a necessidade de combinar a marca&ccedil;&atilde;o topogr&aacute;fica com a marca&ccedil;&atilde;o de variantes <em>implicou a utiliza&ccedil;&atilde;o de mais valores do que o n&uacute;mero de variantes efetivas</em>, uma vez que as quebras de linha n&atilde;o podem ser marcadas dentro dos valores de probabilidade e &eacute; necess&aacute;rio voltar a marcar a variante como variante depois de cada quebra de linha. Nestes casos, o valor da probabilidade indicado &eacute; arbitr&aacute;rio e deve ser ajustado de modo a refletir o n&uacute;mero de variantes e n&atilde;o o n&uacute;mero de quebras de linha, como acontece. Trata-se de uma situa&ccedil;&atilde;o que decorre da impossibilidade de encaixar aquelas duas hierarquias de marca&ccedil;&atilde;o.</p>

<p><strong>Codifica&ccedil;&atilde;o de varia&ccedil;&otilde;es</strong><br>
A codifica&ccedil;&atilde;o adotada permite ainda observar todas as varia&ccedil;&otilde;es existentes entre as interpreta&ccedil;&otilde;es, ou seja, permite comparar a nova transcri&ccedil;&atilde;o dos testemunhos com a transcri&ccedil;&atilde;o Prado Coelho-1982 com a transcri&ccedil;&atilde;o Sobral Cunha-2008 com a transcri&ccedil;&atilde;o Zenith-2012 com a transcri&ccedil;&atilde;o Pizarro-2010 para cada fragmento do <em>Livro do Desassossego</em>. O aparato cr&iacute;tico (&lt;app&gt;) destas varia&ccedil;&otilde;es foi classificado de acordo com cinco tipologias (&lt;type&gt;): &ldquo;orthographic&rdquo; para identificar varia&ccedil;&otilde;es ortogr&aacute;ficas; &ldquo;punctuation&rdquo; para assinalar varia&ccedil;&otilde;es de pontua&ccedil;&atilde;o; &ldquo;paragraph&rdquo; para marcar varia&ccedil;&otilde;es na divis&atilde;o de par&aacute;grafos; &ldquo;style&rdquo; para identificar varia&ccedil;&otilde;es de estilo tipogr&aacute;fico (por exemplo, uso de it&aacute;licos ou de mai&uacute;sculas); e &ldquo;substantive&rdquo; para indicar diferen&ccedil;as na palavra transcrita (por exemplo, quando os peritos optam por variantes divergentes ou leem de forma diferente determinado passo). As varia&ccedil;&otilde;es marcadas (que dizem respeito &agrave;s diferen&ccedil;as existentes <em>no conjunto de todas as interpreta&ccedil;&otilde;es de um dado fragmento</em>) s&atilde;o visualiz&aacute;veis quer atrav&eacute;s do realce de cor, quer atrav&eacute;s da tabela de varia&ccedil;&otilde;es relativa a cada compara&ccedil;&atilde;o.</p>
<p>
<strong>&nbsp;</strong>
</p>
<h3>4. Informa&ccedil;&atilde;o adicional</h3>
<p>Quem estiver interessado numa descri&ccedil;&atilde;o detalhada das op&ccedil;&otilde;es de codifica&ccedil;&atilde;o pode consultar a matriz de um ficheiro XML comentado <strong><a target="_blank" href="/encoding/LdoD_XML-Template_PT.xml">AQUI</a></strong>. Sugere-se ainda a leitura do artigo seguinte: Ant&oacute;nio Rito Silva e Manuel Portela, &ldquo;<a href="http://jtei.revues.org/1171" target="new">TEI4LdoD:  Textual Encoding and Social Editing in Web 2.0 Environments</a>.&rdquo; <em>Journal of the Text Encoding Initiative</em> 8 (2014-2015).</p> 
<p>
<strong>&nbsp;</strong>
</p>
<p>
[atualizado 08-09-2017]
</p>
