export default {
  headersVe: ['acronym', 'title', 'date', 'access', 'actions'],
  headersManage: [
    'acronym',
    'title',
    'editors',
    'categories',
    'annotations',
    'remove',
  ],
  gameTable: ['position', 'username', 'score'],
  JPC: 'Jacinto Prado Coelho',
  RZ: 'Richard Zennith',
  TSC: 'Teresa Sobral Cunha',
  JP: 'Jerónimo Pizarro',

  pt: {
    acronym: 'Sigla',
    title: 'Título',
    date: 'Data',
    access: 'Acesso',
    manage: 'Gerir',
    participate: 'Participar',
    public: 'Público',
    private: 'Privado',
    virtualEditions: 'Edições Virtuais',
    virtualEditionsTitleInfo:
      'Para criar uma edição virtual ou colaborar numa edição virtual existente é necessário autenticar-se',
    createVirtualEdition: 'Criar uma nova Edição Virtual',
    modalTitle: 'Criar Edição Virtual',
    veCreate: 'Criar',
    useEdition: 'Usa Edição',
    headerVeInfo_1: 'Sigla única que identifica a edição',
    headerVeInfo_2: 'Título da Edição',
    headerVeInfo_3: 'Data da criação da edição',
    headerVeInfo_4:
      'Privado: A edição apenas pode ser visualizada pelos seus editores;\nPúblico: A edição é publicamente visível',
    headerVeInfo_5:
      'A edição virtual usa todas as transcrições da edição escolhida',
    manageVE: 'Gerir Edições Virtuais',
    uploadVeCorpus: 'Carregar Corpus das Edições Virtuais',
    uploadVeFragments: 'Carregar Fragmentos das Edições Virtuais',
    exportVe: 'Exportar Edições Virtuais',
    editors: 'Editores',
    categories: 'Categorias',
    annotations: 'Anotações',
    remove: 'Remover',
    removeVE: 'Remover Edição Virtual',
    actions: 'Acções',
    action_1: 'Selecionar / desselecionar edição do menu de topo das Edições',
    action_2: 'Gerir a edição',
    action_3: 'Solicitar para participar na edição',
    action_4: 'Cancelar pedido de participar na edição',
    createVeInfo:
      'Cria uma edição que pode ser colaborativamente construída pelos seus editores',
    game: 'Jogo de Classificação',
    taxonomy: 'Taxonomia',
    manualSort: 'Ordenação Manual',
    assisted: 'Ordenação Assistida',
    edit: 'Editar Edição Virtual',
    winner: 'Vencendor',
    category: 'Categoria',
    position: '#',
    username: 'Nome de Utilizador',
    score: 'Pontos',
  },

  en: {
    acronym: 'Acronym',
    title: 'Title',
    date: 'Date',
    access: 'Access',
    manage: 'Manage',
    participate: 'Join',
    public: 'Public',
    private: 'Private',
    virtualEditions: 'Virtual Editions',
    virtualEditionsTitleInfo:
      'To create a new virtual edition or collaborate in an existing virtual edition, it is necessary to authenticate',
    createVirtualEdition: 'Create a new Virtual Edition',
    modalTitle: 'Virtual Edition Creation',
    veCreate: 'Create',
    useEdition: 'Uses Edition',
    headerVeInfo_1: 'Unique acronym that identifies an edition',
    headerVeInfo_2: 'Edition Title',
    headerVeInfo_3: 'Data da criação da edição',
    headerVeInfo_4:
      'Private: The edition can only be seen by its editors. Public: The edition is publicly visible',
    headerVeInfo_5:
      'The virtual edition uses all the transcriptions from the selected edition',
    manageVE: 'Manage Virtual Editions',
    uploadVeCorpus: 'Load Virtual Editions Corpus',
    uploadVeFragments: 'Load Virtual Editions Fragments',
    exportVe: 'Virtual Editions export',
    editors: 'Editors',
    categories: 'Categories',
    annotations: 'Annotations',
    remove: 'Remove',
    removeVE: 'Remove Virtual Edition',
    actions: 'Actions',
    action_1: 'Select / unselect the edition from the top editions menu',
    action_2: 'Edition management',
    action_3: 'Submit edition participation request',
    action_4: 'Cancel edition participation request',
    createVeInfo:
      'Creates an edition tha can be collaboratively constructed by its editors',
    game: 'Classification Game',
    taxonomy: 'Taxonomy',
    manualSort: 'Manual Sort',
    assisted: 'Assisted Sort',
    edit: 'Edit Virtual Edition',
    winner: 'Winner',
    category: 'Category',
    position: '#',
    username: 'Username',
    score: 'Points',
  },
  es: {
    acronym: 'Sigla',
    title: 'Título',
    date: 'Fecha',
    access: 'Accesso',
    manage: 'Gerir',
    participate: 'Participar',
    public: 'Público',
    private: 'Privado',
    virtualEditions: 'Ediciónes Virtuales',
    virtualEditionsTitleInfo:
      'Para crear una edición virtual o colaborar en una edición virtual existente, debe autenticarse',
    createVirtualEdition: 'Crear una nueva Edición Virtual',
    modalTitle: 'Crear Edicióne Virtual',
    veCreate: 'Crear',
    useEdition: 'Utiliza Edicion',
    headerVeInfo_1: 'Sigla única que identifica la edición',
    headerVeInfo_2: 'Título de la Edición',
    headerVeInfo_3: 'Data da criação da edição',

    headerVeInfo_4:
      'Privado: La edición sólo puede ser visualizada por sus editores; Público: La edición es públicamente visible',
    headerVeInfo_5:
      'La edición virtual usa todas las transcripciones de la edicion escogida',
    manageVE: 'Administrar Ediciónes Virtuales',
    uploadVeCorpus: 'Cargar el corpus de ediciones virtuales',
    uploadVeFragments: 'Cargar fragmentos de ediciones virtuales',
    exportVe: 'Exportación de ediciones virtuales',
    editors: 'Editores',
    categories: 'Categorias',
    annotations: 'Anotaciónes',
    remove: 'Remover',
    removeVE: 'Remover Ediccióne virtuale',
    actions: 'Acciónes',
    action_1:
      'Seleccionar / deseleccionar la edición en el menú superior de ediciones',
    action_2: 'Acceder a la gestión de la edición',
    action_3: 'Enviar solicitud de participación',
    action_4: 'Cancelar solicitud de participación',

    createVeInfo:
      'Crear una edición que puede ser colaborativamente construida por sus editores',
    game: 'Juego de clasificación',
    taxonomy: 'Taxonomía',
    manualSort: 'Ordenación Manual',
    assisted: 'Ordenación Asistida',
    edit: 'Editar la edición virtual',
    winner: 'Ganador',
    category: 'Categoría',
    position: '#',
    username: 'Nombre de usuario	',
    score: 'Puntos',
  },
};
