export default {
  headers: [
    'date',
    'fragment',
    'sourceLink',
    'tweetText',
    'location',
    'country',
    'username',
  ],
  pt: {
    title: (val) => `Citações no Twitter (${val})`,
    date: 'Data',
    fragment: 'Fragmento',
    sourceLink: 'Tweet',
    tweetText: 'Texto',
    location: 'Localização Geográfica',
    country: 'País',
    username: 'Utilizador',
  },
  en: {
    title: (val) => `Citations on Twitter (${val})`,
    date: 'Date',
    fragment: 'Fragment',
    sourceLink: 'Tweet',
    tweetText: 'Text',
    location: 'Geographic Location',
    country: 'Country',
    username: 'User',
  },
  es: {
    title: (val) => `Citas en Twitter (${val})`,
    date: 'Fechas',
    fragment: 'Fragmento',
    sourceLink: 'Tweet',
    tweetText: 'Texto',
    location: 'Localización Geográfica',
    country: 'País',
    username: 'Usuario',
  },
};
