export default {
  pt: {
    expert_edition_info:
      'O mesmo testemunho pode ser interpretado como mais do que um texto pelos editores. Estas variações na divisão de fragmentos baseiam-se quer em marcações autógrafas (traços horizontais ou espaços entre blocos de texto), quer em interpretações sobre a proximidade semântica dos blocos textuais.',
    witnesses: 'Testemunhos',
    expert_editions: 'Edições dos Peritos',
    virtual_editions_info:
      'As edições virtuais contêm fragmentos escolhidos pelos seus editores a partir de outras edições.',
    virtual_editions: 'Edições Virtuais',

    altIdentifier: 'Identificação',
    heteronym: 'Heterónimo',
    form: 'Formato',
    material: 'Material',
    columns: 'Colunas',
    hadLdoDLabel: 'Marca LdoD',
    surfaceString: 'Fac-símiles',
    typeNoteDto: (arg) =>
      `<strong>Datiloscrito</strong> <em>(${arg})</em><strong> : </strong>`,
    handNoteDto: (arg) =>
      `<strong>Manuscrito</strong> <em>(${arg})</em><strong> : </strong>`,
    date: 'Data',
    LEAF: 'Folha',
    PAPER: 'Papel',
    journal: 'Revista',
    issue: 'Número',
    pubPlace: 'Local de publicação',
    notAssigned: 'Não atribuído',
    notes: 'Nota',
    true: 'Com marca LdoD',
    no: 'Sem marca LdoD',

    title: 'Título',
    volume: 'Volume',
    number: 'Número',
    startPage: 'Página',

    diff: 'Realçar Diferenças',
    diff_info: 'Realça variações entre as transcrições em comparação',
    del: 'Mostrar Apagados',
    del_info: 'Mostra texto apagado por Fernando Pessoa',
    ins: 'Realçar Inseridos',
    ins_info: 'Realça texto inserido por Fernando Pessoa',
    sub: 'Realçar Substituições',
    sub_info: 'Realça texto apagado e substituído por Fernando Pessoa',
    note: 'Mostrar Notas',
    note_info: 'Mostra a informação sobre as fontes das transcrições',
    fac: 'Fac-símile',
    fac_info: 'imagem dos documentos originais',

    uses: 'Usa',
    line: 'Linha-a-linha',
    align: 'Alinhar Espaços',

    variations: 'Tabela de Variações',
    virtual_edition_comparison: 'Comparação de anotações de edições virtuais',
    edition: 'Edição',
    citation: 'Citação',
    comment: 'Comentário',
    user: 'Utilizador',
    tags: 'Etiquetas',
    line_by_line_info:
      'O gradiente de cor aumenta consoante o número de diferenças entre as transcrições em comparação',
  },
  en: {
    expert_edition_info:
      'The same witness can be interpreted as more than one text by the editors. Variations in fragment division are based either upon autograph marks (such as horizontal rulers or spaces between text blocks) or upon interpretations about semantic relations between text blocks.',
    witnesses: 'Witnesses',
    expert_editions: 'Expert Editions',
    virtual_editions_info:
      'Virtual editions contain fragments selected by their editors from other editions.',
    virtual_editions: 'Virtual Editions',

    altIdentifier: 'Identification',
    heteronym: 'Heteronym',
    form: 'Format',
    material: 'Material',
    columns: 'Columns',
    hadLdoDLabel: 'LdoD Mark',
    surfaceString: 'Facsimiles',
    typeNoteDto: (arg) =>
      `<strong>TypeScript</strong> <em>(${arg})</em><strong> : </strong>`,
    handNoteDto: (arg) =>
      `<strong>Manuscript</strong> <em>(${arg})</em><strong> : </strong>`,
    date: 'Date',
    LEAF: 'Leaf',
    PAPER: 'Paper',
    journal: 'Journal',
    issue: 'Number',
    pubPlace: 'Publication place',
    notAssigned: 'Not assigned',
    notes: 'Nota',
    true: 'With LdoD mark',
    no: 'No LdoD mark',

    title: 'Title',
    volume: 'Volume',
    number: 'Number',
    startPage: 'Page',

    diff: 'Highlight Differences',
    diff_info: 'Highlights variations in compared transcriptions',
    del: 'Show Deleted',
    del_info: 'Show deletions by Fernando Pessoa',
    ins: 'Highligh Inserted',
    ins_info: 'Highlights additions by Fernando Pessoa',
    sub: 'Highlight Substitutions',
    sub_info: 'Highlights passages deleted for substituiton by Fernando Pessoa',
    note: 'Show Notes',
    note_info: 'Show information about transcription sources',
    fac: 'Facsimile',
    fac_info: 'Image of the original documents',
    line: 'Line-by-line',
    align: 'Align Spaces',

    uses: 'Uses',
    variations: 'Variations Table',
    virtual_edition_comparison: 'Comparação de anotações de edições virtuais',
    edition: 'Edition',
    citation: 'Citation',
    comment: 'Comment',
    user: 'User',
    tags: 'Tags',
    line_by_line_info:
      'Colour gradient increases according to the number of differences across compared editions',
  },
  es: {
    expert_edition_info:
      'El mismo testimonio puede ser interpretado como más de un texto según los editores. Estas variaciones en la división de los fragmentos se basan bien en marcaciones autógrafas (trazos horizontales o espacios entre bloques del texto), bien en interpretaciones sobre la proximidad semántica de los bloques textuales.',
    witnesses: 'Testimonios',
    expert_editions: 'Ediciones de los Especialistas',
    virtual_editions_info:
      'Las ediciones virtuales contienen fragmentos escogidos por sus editores a partir de otras ediciones.',
    virtual_editions: 'Ediciónes Virtuales',

    altIdentifier: 'Identificación',
    heteronym: 'Heterónimo',
    form: 'Formato',
    material: 'Material',
    columns: 'Columnas',
    hadLdoDLabel: 'Marca LdoD',
    surfaceString: 'Facsimiles',
    typeNoteDto: (arg) =>
      `<strong>Mecanografiado</strong> <em>(${arg})</em><strong> : </strong>`,
    handNoteDto: (arg) =>
      `<strong>Manuscrito</strong> <em>(${arg})</em><strong> : </strong>`,
    date: 'Fecha',
    LEAF: 'Hoja',
    PAPER: 'Papel',
    journal: 'Revista',
    issue: 'Número',
    pubPlace: 'Lugar de la Publicación',
    notAssigned: 'No assignado',
    
    notes: 'Nota',
    true: 'Con marca LdoD',
    no: 'Sin marca LdoD',

    title: 'Título',
    volume: 'Volume',
    number: 'Número',
    startPage: 'Página',

    diff: 'Realzar Diferencias',
    diff_info: 'Realza variaciones entre las transcripciones en comparación',
    del: 'Mostrar Eliminados',
    del_info: 'Muestra texto eliminado por Fernando Pessoa',
    ins: 'Realzar Acrecentados',
    ins_info: 'Realza texto añadido por Fernando Pessoa',
    sub: 'Realzar Sustituciones',
    sub_info: 'Realza texto eliminado y substituido por Fernando Pessoa',
    note: 'Mostrar Notas',
    note_info:
      'Muestra la información sobre las fuentes de las transcripciones',
    fac: 'Facsimile',
    fac_info: 'Imagen de los documentos originales',
    line: 'Línea a línea',
    align: 'Alinear Espacios',

    uses: 'Usa',
    variations: 'Tabla de Variaciones',
    virtual_edition_comparison:
      'Comparación de anotaciones de ediciones virtuales',
    edition: 'Edición',
    citation: 'Cita',
    comment: 'Comentario',
    user: 'Usuario',
    tags: 'Etiquetas',
    line_by_line_info:
      'El gradiente de color aumenta según el número de diferencias entre las transcripciones en comparación',
  },
};
