/** @format */

export default {
	gamesHeaders: [
		'description',
		'title',
		'date',
		'publicAnnotation',
		'category',
		'players',
		'winner',
		'responsible',
		'remove',
	],
	pt: {
		createCG: 'Criar Jogo de Classificação',
		create: 'Criar',
		description: 'Descrição',
		title: 'Título',
		date: 'Data',
		publicAnnotation: 'Anotar fragmentos',
		category: 'Categoria',
		players: 'Jogadores',
		winner: 'Vencedor',
		responsible: 'Responsável',
		remove: 'Apagar',
		all: 'Utilizadores Registados',
		members: 'Editores da Edição',
		inter: 'Interpretação',
		game: 'Jogo de Classificação',
	},
	en: {
		createCG: 'Create Classification Game',
		create: 'Create',
		description: 'description',
		title: 'title',
		date: 'date',
		publicAnnotation: 'Annotate fragments',
		category: 'Category',
		players: 'Players',
		winner: 'Winner',
		responsible: 'Responsible',
		remove: 'Delete',
		all: 'Registered Users',
		members: 'Edition Editors',
		inter: 'Interpretation',
		game: 'Classification Game',
	},
	es: {
		create: 'create',
		createCG: 'Criar Juego de Classificatión',
		description: 'Descrição',
		title: 'Título',
		date: 'Data',
		publicAnnotation: 'Anotar fragmentos',
		category: 'Categoria',
		players: 'Jogadores',
		winner: 'Vencedor',
		responsible: 'Responsável',
		remove: 'Apagar',
		all: 'Usuarios Registrados',
		members: 'Editores de la Edicíon',
		inter: 'Interpretación',
		game: 'Juego de Classificatión',
	},
};
