export const SET_MODULE_CONFIG = 'SET_MODULE_CONFIG';

export const SET_COMPARE_IDS_TYPE = 'SET_COMPARE_IDS_TYPE';

export const SET_INTER_ID = 'SET_INTER_ID';

export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';

export const SET_USER_INFO = 'SET_USER_INFO';
