export default {
  headers: ['xmlId', 'title', 'remove', 'export'],
  pt: {
    manageFragments: (value) => `Gerir Fragmentos (${value})`,
    xmlId: 'XML ID',
    title: 'Título',
    remove: 'Remover',
    export: 'Exportar',
    removeFragment: 'Remover fragmento',
    removeAll: 'Remover todos os fragmentos',
    exportAll: 'Exportar arquivo completo',
    exportSelected: 'Exportar Fragmentos selecionados',
    exportRandom: 'Exportar 3 fragmentos aleatórios',
    select: 'Clique para selecionar/desselecionar',
    unselectAll: 'Clique para desselecionar todos',
    uploadSingle: 'Carregar ficheiro TEI com Fragmento',
    uploadMultiple: 'Carregar vários ficheiros TEI Fragmentos',
    uploadCorpus: 'Carregar ficheiro TEI com Corpus',
  },
  en: {
    manageFragments: (value) => `Manage Fragments (${value})`,
    xmlId: 'XML ID',
    title: 'Title',
    remove: 'Remove',
    export: 'Export',
    removeFragment: 'Remove Fragment',
    removeAll: 'Remove all fragments',
    exportAll: 'Export entire archive',
    exportSelected: 'Export selected Fragments',
    exportRandom: 'Export 3 random fragments',
    select: 'Click to select/unselect',
    unselectAll: 'Click to unselect all',
    uploadSingle: 'Upload TEI Fragment file',
    uploadMultiple: 'Upload multiple TEI Fragment files',
    uploadCorpus: 'Upload TEI Corpus file',
  },
  es: {
    manageFragments: (value) => `Administrar Fragmentos (${value})`,
    xmlId: 'XML ID',
    title: 'Título',
    remove: 'Remover',
    export: 'Exportar',
    removeFragment: 'Eliminar fragmento',
    removeAll: 'Remover todos os fragmentos',
    exportAll: 'Exportar todos os Fragmentos',
    exportSelected: 'Exportar Fragmentos selecionados',
    exportRandom: 'Exportar 3 fragmentos aleatórios',
    select: 'Clique para selecionar/desselecionar',
    unselectAll: 'Clique para desselecionar todos',
    uploadSingle: 'Carregar Fragmento',
    uploadMultiple: 'Carregar vários Fragmentos',
    uploadCorpus: 'Carregar ficheiro TEI com Corpus',
  },
};
