export default {
  veHeaders: ['number', 'title', 'category', 'useEdition'],
  userVeHeaders: ['title', 'edition', 'category', 'useEdition'],
  categoryVeHeaders: ['title', 'virtualEdition', 'user', 'useEdition'],
  taxonomyHeaders: ['category', 'users', 'editions', 'inters'],

  pt: {
    virtualEdition: 'Edição Virtual',
    synopse: 'Sinopse',
    fragments: 'Fragmentos',
    number: 'Número',
    category: 'Categoria',
    editions: 'Edições',
    edition: 'Edição',
    participant: 'Participante',
    score: 'Pontos',
    position: 'Posição',
    users: 'Utilizadores',
    user: 'Utilizador',
    inters: 'Interpretações',
  },
  en: {
    virtualEdition: 'Virtual Edition',
    synopse: 'Sinopsis',
    fragments: 'Fragments',
    number: 'Number',
    category: 'Category',
    editions: 'Editions',
    edition: 'Edition',
    participant: 'Participant',
    score: 'Points',
    position: 'Position',
    users: 'Users',
    user: 'User',
    inters: 'Interpretations',
  },
  es: {
    virtualEdition: 'Edicióne Virtual',
    synopse: 'Sinopsis',
    fragments: 'Fragmentos',
    number: 'Número',
    category: 'Categoria',
    editions: 'Ediciónes',
    edition: 'Edición',
    participant: 'Participant',
    points: 'Puntos',
    position: 'Posición',
    users: 'Usuários',
    user: 'Usuário',
    inters: 'Interpretaciónes',
  },
};
