export default {
	en: {
		title: 'LdoD Archive',
		username: 'Username',
		password: 'Password',
		signin: 'Sign in',
		signup: 'Register as a LdoD Archive user',
		register: 'Sign up',
		firstname: 'First name',
		lastname: 'Surname',
		email: 'Email',
		alphabetic: 'Alphabetic field required',
		alphanumeric: 'Alphanumeric field required',
		passwordLength: 'Required and must be at least 6 characters',
		invalidEmail: 'Invalid Email',
		conductCode: 'Code of conduct',
		conduct: 'By registering as a user of the LdoD Archive, I accept the code of conduct',
		conductCheck: 'Must accept the code of conduct',
		authorization:
			'Your request was submitted for authorization. In case of approval, an email from the e-address ldod.archive@gmail.com will be sent to your mailbox. The confirmation should occur within the next 24 hours.',
		googleAssociation: 'Your Google account is not associated with a LdoD Archive account. Please sign up.',
		changePassword: 'Change Password',
		update: 'Update',
		currentPassword: 'Current password',
		newPassword: 'New password',
		confirmPassword: 'Retype password',
		currentNew: 'The new password must differ from the current one',
		confirmPattern: 'The passwords do not match',
	},
	pt: {
		title: 'Arquivo LdoD',
		username: 'Nome de utilizador',
		password: 'Senha',
		signin: 'Entrar',
		signup: 'Registar-se como utilizador do Arquivo LdoD',
		register: 'Registo',
		firstname: 'Primeiro nome',
		lastname: 'Apelido',
		email: 'Endereço electrónico',
		alphabetic: 'Campo alfabético obrigatório',
		alphanumeric: 'Campo alfanumérico obrigatório',
		passwordLength: 'Obrigatório e deve conter no mínimo 6 caracteres',
		invalidEmail: 'Correio electrónico inválido',
		conductCode: 'Código de conducta',
		conductCheck: 'Deve aceitar o código de conduta',
		conduct: 'Ao registar-me como utilizador do Arquivo LdoD, aceito o código de conduta',
		authorization:
			'O seu pedido foi submetido para autorização. Em caso de aceitação, um email de confirmação será enviado para a sua caixa de correio a partir do endereço ldod.archive@gmail.com. A confirmação deve ocorrer no espaço de 24 horas.',
		googleAssociation:
			'A sua conta Google ainda não está associada com uma conta do Arquivo do LdoD. Registe-se por favor.',
		changePassword: 'Alterar Senha',
		update: 'Atualizar',
		currentPassword: 'Senha actual',
		newPassword: 'Nova senha',
		confirmPassword: 'Digite novamente a senha',
		currentNew: 'A nova senha deve diferir da atual',
		confirmPattern: 'As palavras-passe não coincidem',
	},
	es: {
		title: 'Archivo LdoD',
		username: 'Nombre de utilizador',
		password: 'Contraseña',
		signin: 'Ingressar',
		signup: 'Registrarse como usuario del Archivo LdoD',
		register: 'Regístrar',
		firstname: 'Primer nombre',
		lastname: 'Apellido',
		email: 'Correo electrónico',
		alphabetic: 'Campo alfabético obligatorio',
		alphanumeric: 'Campo alfanumérico obligatorio',
		passwordLength: 'Obligatorio y debe contener al menos 6 caracteres',
		invalidEmail: 'Correo electrónico inválido',
		conductCode: 'Código de conducta',
		conduct: 'Al registrarme como usuario del Archivo LdoD, acepto el código de conducta',
		conductCheck: 'Debe aceptar el código de conducta',
		authorization:
			'Su solicitud fue enviada para autorización. En caso de aprobación, un correo electrónico de la dirección electrónica ldod.archive@gmail.com será enviado a su buzón de correo. La confirmación debe ocurrir dentro de las próximas 24 horas',
		googleAssociation: 'Su cuenta Google no está asociada con una cuenta de Archivo LdoD. Por favor regístrese.',
		changePassword: 'Cambiar la Contraseña',
		update: 'Atualizar',
		currentPassword: 'Contraseña actual',
		newPassword: 'Nueva constraseña',
		confirmPassword: 'Vuelva a escribir la contraseña',
		currentNew: 'La nueva contraseña debe ser diferente de la actual',
		confirmPattern: 'Las contraseñas no coinciden',
	},
};
