export default {
  header_title: 'Archivo LdoD',
  user_password: 'Cambiar la Contraseña',
  header_login: 'Iniciar Sesión',
  header_logout: 'Cerrar',

  header_about: 'Acerca',
  header_videos: 'Vídeos',
  header_tutorials: 'Tutoriales y Talleres',
  header_faq: 'Preguntas Frecuentes',
  header_encoding: 'Codificación de Texto',
  header_bibliography: 'Bibliografía',
  header_book: 'Libro',
  header_conduct: 'Código de Conducta',
  header_contact: 'Contacto',
  header_copyright: 'Copyright',
  header_privacy: 'Política de Privacidad',
  header_team: 'Equipo Editorial',
  header_acknowledgements: 'Agradecimientos',

  general_reading: 'Lectura',
  general_reading_sequences: 'Secuencias de lectura',
  general_reading_visual_externo: 'Libro Visual (Externo)',
  general_reading_visual_integrado: 'Libro Visual (Integrado)',

  general_citations_twitter: 'Citas en Twitter',

  header_documents: 'Documentos',
  authorial_source: 'Testimonios',
  fragment_codified: 'Fragmentos Codificados',

  header_editions: 'Ediciones',
  general_editor_prado: 'Jacinto do Prado Coelho',
  general_editor_zenith: 'Richard Zenith',
  general_editor_cunha: 'Teresa Sobral Cunha',
  general_editor_pizarro: 'Jerónimo Pizarro',
  anot: 'LdoD-JPC-Anot',
  mallet: 'LdoD-Jogo-Class',
  class: 'LdoD-Mallet,',
  twitter: 'LdoD-Twitter',

  header_search: 'Búsqueda',
  header_search_simple: 'Búsqueda Sencilla',
  header_search_advanced: 'Búsqueda Avanzada',

  header_virtual: 'Virtual',
  header_virtualeditions: 'Ediciones Virtuales',
  general_classificationGame: 'Juego de Clasificación',

  header_admin: 'Admin',
  fragments_management: 'Administrar Fragmentos',
  user_management: 'Administrar Usuarios',
  virtual_editions_management: 'Administrar Ediciones Virtuales',
  tweets_management: 'Administrar Tweets',
  error: 'Algo salió mal. Vuelve a intentarlo más tarde',
};
