/** @format */

export default {
	pt: {
		witnesses: 'Testemunhos',
		experts: 'Edições dos Peritos',
		expertsTooltip:
			'O mesmo testemunho pode ser interpretado como mais do que um texto pelos editores. Estas variações na divisão de fragmentos baseiam-se quer em marcações autógrafas (traços horizontais ou espaços entre blocos de texto), quer em interpretações sobre a proximidade semântica dos blocos textuais.',
		diff: 'Realçar Diferenças',
		diffInfo: 'Realça variações entre as transcrições em comparação',
		del: 'Mostrar Apagados',
		delInfo: 'Mostra texto apagado por Fernando Pessoa',
		ins: 'Realçar Inseridos',
		insInfo: 'Realça texto inserido por Fernando Pessoa',
		sub: 'Realçar Substituições',
		subInfo: 'Realça texto apagado e substituído por Fernando Pessoa',
		note: 'Mostrar Notas',
		noteInfo: 'Mostra a informação sobre as fontes das transcrições',
		fac: 'Fac-símile',
		facInfo: 'imagem dos documentos originais',
		line: 'Linha-a-linha',
		align: 'Alinhar Espaços',
		variations: 'Tabela de Variações',
		lineByLineInfo:
			'O gradiente de cor aumenta consoante o número de diferenças entre as transcrições em comparação',
	},
	en: {
		witnesses: 'Witnesses',
		experts: 'Expert Editions',
		expertsTooltip:
			'The same witness can be interpreted as more than one text by the editors. Variations in fragment division are based either upon autograph marks (such as horizontal rulers or spaces between text blocks) or upon interpretations about semantic relations between text blocks.',
		diff: 'Highlight Differences',
		diffInfo: 'Highlights variations in compared transcriptions',
		del: 'Show Deleted',
		delInfo: 'Show deletions by Fernando Pessoa',
		ins: 'Highligh Inserted',
		insInfo: 'Highlights additions by Fernando Pessoa',
		sub: 'Highlight Substitutions',
		subInfo: 'Highlights passages deleted for substituiton by Fernando Pessoa',
		note: 'Show Notes',
		noteInfo: 'Show information about transcription sources',
		fac: 'Facsimile',
		facInfo: 'Image of the original documents',
		line: 'Line-by-line',
		align: 'Align Spaces',
		variations: 'Variations Table',
		lineByLineInfo:
			'Colour gradient increases according to the number of differences across compared editions',
	},
	es: {
		witnesses: 'Testimonios',
		experts: 'Ediciones de los Especialistas ',
		expertsTooltip:
			'El mismo testimonio puede ser interpretado como más de un texto según los editores. Estas variaciones en la división de los fragmentos se basan bien en marcaciones autógrafas (trazos horizontales o espacios entre bloques del texto), bien en interpretaciones sobre la proximidad semántica de los bloques textuales.',
		diff: 'Realzar Diferencias',
		diffInfo: 'Realza variaciones entre las transcripciones en comparación',
		del: 'Mostrar Eliminados',
		delInfo: 'Muestra texto eliminado por Fernando Pessoa',
		ins: 'Realzar Acrecentados',
		insInfo: 'Realza texto añadido por Fernando Pessoa',
		sub: 'Realzar Sustituciones',
		subInfo: 'Realza texto eliminado y substituido por Fernando Pessoa',
		note: 'Mostrar Notas',
		noteInfo: 'Muestra la información sobre las fuentes de las transcripciones',
		fac: 'Facsimile',
		facInfo: 'Imagen de los documentos originales',
		line: 'Línea a línea',
		align: 'Alinear Espacios',
		variations: 'Tabla de Variaciones',
		lineByLineInfo:
			'El gradiente de color aumenta según el número de diferencias entre las transcripciones en comparación',
	},
};
