export const NAME_MIN_LENGTH = 4;
export const NAME_MAX_LENGTH = 40;
export const USERNAME_MIN_LENGTH = 3;
export const USERNAME_MAX_LENGTH = 15;
export const EMAIL_MAX_LENGTH = 40;
export const PASSWORD_MIN_LENGTH = 6;
export const PASSWORD_MAX_LENGTH = 20;
export const ALPHABETICAL_REGEX = new RegExp(/^[-'a-zA-ZÀ-ÖØ-öø-ÿ]+$/);
export const ALPHANUMERIC_REGEX = new RegExp(/^[0-9a-zA-Z]+$/);
export const EMAIL_REGEX = new RegExp(/^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$/)