export default {
  pt: {
    reading_tt_recom:
      'Na coluna de recomendação são sugeridos de forma automática os fragmentos mais similares ao fragmento selecionado na coluna da edição. A similaridade entre o fragmento da edição e o fragmento da recomendação é calculada segundo uma combinação de quatro critérios (ajustáveis pelos utilizadores): heterónimo, data, texto e taxonomia.',
    book_disquiet: 'Livro do Desassossego de Fernando Pessoa',
    general_recommendation: 'Recomendação',
    recommendation_criteria: 'Critérios de Ordenação',
    general_recommendation_config: 'Configuração das Recomendações',
    general_close: 'Recomendar',
    general_reset: 'Reiniciar',
    heteronym: 'Heterónimo',
    date: 'Data',
    text: 'Texto',
    taxonomy: 'Taxonomia',
    general_citations_twitter: 'Citações no Twitter',
    citationsTableLabels: {
      date: 'Data',
      title: 'Fragmento',
      sourceLink: 'Tweet',
      tweetText: 'Texto',
      location: 'Localização Geográfica',
      country: 'País',
      username: 'Utilizador',
    },
  },
  en: {
    reading_tt_recom:
      'The most similar fragments to the selected fragment in the edition column are automatically suggested in the recommendation column. Similarity between the edition fragment and the recommendation fragment is calculated according to a combination of four criteria (adjustable by users): heteronym, date, text, and taxonomy.',
    book_disquiet: 'Book of Disquiet by Fernando Pessoa',
    general_recommendation: 'Recommendation',
    recommendation_criteria: 'Sorting Criteria',
    general_recommendation_config: 'Configuration of Recommendations',
    general_close: 'Recommend',
    general_reset: 'Reset',
    heteronym: 'Heteronym',
    date: 'Date',
    text: 'Text',
    taxonomy: 'Taxonomy',
    general_citations_twitter: 'Citations on Twitter',
    citationsTableLabels: {
      date: 'Date',
      title: 'Fragment',
      sourceLink: 'Tweet',
      tweetText: 'Text',
      location: 'Geographic Location',
      country: 'Country',
      username: 'User',
    },
  },
  es: {
    reading_tt_recom:
      'En la columna de recomendación se sugieren de forma automática los fragmentos más similares al fragmento seleccionado en la columna de la edición. La similitud entre el fragmento de la edición y el fragmento de la recomendación se calcula según una combinación de cuatro criterios (ajustables por los usuarios): heterónimo, fecha, texto y taxonomí­a.',
    book_disquiet: 'Libro del Desasosiego de Fernando Pessoa',
    general_recommendation: 'Recomendación',
    recommendation_criteria: 'Criterios de Ordenación',
    general_recommendation_config: 'Configuración de las Recomendaciones',
    general_close: 'Recomendar',
    general_reset: 'Reiniciar',
    heteronym: 'Heterónimo',
    date: 'Fecha',
    text: 'Texto',
    taxonomy: 'Taxonomía',
    general_citations_twitter: 'Citas en Twitter',
    citationsTableLabels: {
      date: 'Fecha',
      title: 'Fragmento',
      sourceLink: 'Tweet',
      tweetText: 'Texto',
      location: 'Localización Geográfica',
      country: 'País',
      username: 'Usuario',
    },
  },
};
