export default {
  pt: {
    edition_of: 'Edição de',
    expertTableHeaders: {
      number: 'Número',
      title: 'Título',
      read: 'Leitura',
      volume: 'Volume',
      page: 'Página',
      date: 'data',
      heteronym: 'Heterónimo',
    },
    number_info: 'Número do fragmento na edição',
    title_info: 'Título ou incipit do fragmento',
    read_info: 'Começar a ler o LdoD com recomendações',
    volume_info: 'Volume em que o fragmento se encontra',
    page_info: 'Página em que o fragmento se encontra',
    date_info: 'Data inscrita ou atribuída ao fragmento',
    heteronym_info: 'Atribuição de heterónimo segundo o editor',

    editors: 'Editores',
    synopse: 'Sinopse',
    taxonomy: 'Taxonomia',
    fragments: 'Fragmentos',
    virtualTableHeaders: {
      number: 'Número',
      title: 'Título',
      category: 'Categoria',
      useEditions: 'Usa Edições',
    },
    virtualEdition: 'Edição Virtual'

  },
  en: {
    edition_of: 'Edition of',
    expertTableHeaders: {
      number: 'Number',
      title: 'Title',
      read: 'Reading',
      volume: 'Volume',
      page: 'Page',
      date: 'Date',
      heteronym: 'Heteronym',
    },
    number_info: 'Fragment number in the edition',
    title_info: 'Title or incipt of the fragment',
    read_info: 'Start reading the LdoD with recommendations',
    volume_info: 'Volume where the fragment can be found',
    page_info: 'Page where the fragment can be found',
    date_info: 'Date inscribed or ascribed to the fragment',
    heteronym_info: 'Heteronym attribution according to the editor',

    editors: 'Editors',
    synopse: 'Synopse',
    taxonomy: 'Taxonomy',
    fragments: 'Fragments',
    virtualTableHeaders: {
      number: 'Number',
      title: 'Title',
      category: 'Category',
      useEditions: 'Use Editions',
    },
    virtualEdition: 'Virtual Edition'
  },
  es: {
    edition_of: 'Edición de',
    expertTableHeaders: {
      number: 'Número',
      title: 'Título',
      read: 'Lectura',
      volume: 'Volume',
      page: 'Página',
      date: 'Fecha',
      heteronym: 'Heterónimo',
    },
    number_info: 'Número del fragmento en la edicion',
    title_info: 'Título o incipit del fragmento',
    read_info: 'Empezar a leet el LdoD com recomendaciones',
    volume_info: 'Volume en que el fragmento se encuentra',
    page_info: 'Página en que el fragmento se encuentra',
    date_info: 'Fech inscrita o atribuída al fragmento',
    heteronym_info: 'Atribuicion de heterónimo según el editor',
  },
};
