export default {
  pt: {
    edition_of: 'Edição de',
    expertTableLabels: {
      number: 'Número',
      title: 'Título',
      read: 'Leitura',
      volume: 'Volume',
      page: 'Página',
      date: 'data',
      heteronym: 'Heterónimo',
      number_info: 'Número do fragmento na edição',
      title_info: 'Título ou incipit do fragmento',
      read_info: 'Começar a ler o LdoD com recomendações',
      volume_info: 'Volume em que o fragmento se encontra',
      page_info: 'Página em que o fragmento se encontra',
      date_info: 'Data inscrita ou atribuída ao fragmento',
      heteronym_info: 'Atribuição de heterónimo segundo o editor',
    },


    editors: 'Editores',
    synopse: 'Sinopse',
    taxonomy: 'Taxonomia',
    fragments: 'Fragmentos',
    virtualTableLabels: {
      number: 'Número',
      title: 'Título',
      category: 'Categoria',
      useEditions: 'Usa Edições',
      number_info: 'Número do fragmento na edição',
      title_info: 'Título ou incipit do fragmento',
      category_info: 'Taxonomia usada na edição',
      useEditions_info: 'Edições cuja transcrição e anotação são usadas',
    },
    virtualEdition: 'Edição Virtual',
    editions: 'Edições',
    participant: 'Participante',
    points: 'Pontos',
    position: 'Posição',
    
    userTableLabels: {
      title: 'Titúlo',
      edition: 'Edição',
      category: 'Categoria',
      useEditions: 'Usa Edicões',
    },
    categories: 'Categorias',
    taxonomyTableLabels: {
      category: 'Categoria',
      users: 'Utilizadores',
      editions: 'Edições',
      interpts: 'Interpretações',
    },
    category: 'Categoria',
    categoryTableLabels: {
      title: 'Título',
      virtualEdition: 'Edição Virtual',
      user: 'Utilizador',
      useEditions: 'Utiliza Edicões',
    },
  },
  en: {
    edition_of: 'Edition of',
    expertTableLabels: {
      number: 'Number',
      title: 'Title',
      read: 'Reading',
      volume: 'Volume',
      page: 'Page',
      date: 'Date',
      heteronym: 'Heteronym',
      number_info: 'Fragment number in the edition',
      title_info: 'Title or incipt of the fragment',
      read_info: 'Start reading the LdoD with recommendations',
      volume_info: 'Volume where the fragment can be found',
      page_info: 'Page where the fragment can be found',
      date_info: 'Date inscribed or ascribed to the fragment',
      heteronym_info: 'Heteronym attribution according to the editor',
    },
    editors: 'Editors',
    synopse: 'Synopse',
    taxonomy: 'Taxonomy',
    fragments: 'Fragments',
    virtualTableLabels: {
      number: 'Number',
      title: 'Title',
      category: 'Category',
      useEditions: 'Use Editions',
      number_info: 'Fragment number in the edition',
      title_info: 'Title or incipt of the fragment',
      category_info: 'Taxonomy used in the edição',
      useEditions_info: 'Editions whose transcription and annotation are used',
    },
    virtualEdition: 'Virtual Edition',
    editions: 'Editions',
    participant: 'Participant',
    points: 'Points',
    position: 'Position',

    userTableLabels: {
      title: 'Title',
      edition: 'Edition',
      category: 'Category',
      useEditions: 'Use Editions',
    },
    categories: 'Categories',
    taxonomyTableLabels: {
      category: 'Category',
      users: 'Users',
      editions: 'Editions',
      interpts: 'Interpretations',
    },
    category: 'Category',
    categoryTableLabels: {
      title: 'Title',
      virtualEdition: 'Virtual Edition',
      user: 'User',
      useEditions: 'Use Editions',
    },
  },
  es: {
    edition_of: 'Edición de',
    expertTableLabels: {
      number: 'Número',
      title: 'Título',
      read: 'Lectura',
      volume: 'Volume',
      page: 'Página',
      date: 'Fecha',
      heteronym: 'Heterónimo',
      number_info: 'Número del fragmento en la edicion',
      title_info: 'Título o incipit del fragmento',
      read_info: 'Empezar a leet el LdoD com recomendaciones',
      volume_info: 'Volume en que el fragmento se encuentra',
      page_info: 'Página en que el fragmento se encuentra',
      date_info: 'Fech inscrita o atribuída al fragmento',
      heteronym_info: 'Atribuicion de heterónimo según el editor',
    },
    editors: 'Editores',
    synopse: 'Sinopsis',
    taxonomy: 'Taxonomia',
    fragments: 'Fragmentos',
    virtualTableLabels: {
      number: 'Número',
      title: 'Titúlo',
      category: 'Categoria',
      useEditions: 'Utiliza Ediciones',
      number_info: 'Número del fragmento en la edicion',
      title_info: 'Título o incipit del fragmento',
      category_info: 'Taxonomia utilizada en la edición',
      useEditions_info: 'Ediciónes cuya transcripción y anotación se utilizan',
    },
    virtualEdition: 'Edición Virtual',
    editions: 'Ediciones',
    participant: 'PartÃ­cipe',
    points: 'Puntos',
    position: 'Posición',
    userTableLabels: {
      title: 'Titúlo',
      edition: 'Edición',
      category: 'Categoria',
      useEditions: 'Utiliza Ediciones',
    },
    categories: 'Categorías',
    taxonomyTableLabels: {
      category: 'Categoría',
      users: 'Usuarios',
      editions: 'Ediciónes',
      interpts: 'Interpretaciones',
    },
    category: 'Categoría',
    categoryTableLabels: {
      title: 'Titúlo',
      virtualEdition: 'Edición Virtual',
      user: 'Usuario',
      useEditions: 'Utiliza Ediciones',
    },
  },
};
